In [1]:
import os
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt

In [3]:
os.getcwd()

'C:\\Users\\SAMSUNG\\Documents\\dev\\Main_project_police\\processing_code'

In [13]:
mcz_kr = pd.read_csv('C:\\Users\SAMSUNG\Desktop\SSAC\머신러닝\메인프로젝트/마창진_인구.csv', encoding = 'cp949', thousands = ',')
mcz_kr.head()

     기준년월     행정동코드   시도명       시군구명 행정동명  한국인 소계  한국인 남  한국인 여  한국인 세대수
0  201102  48123570  경상남도    창원시 성산구  웅남동   10346   5486   4860     3883
1  201102  48121530  경상남도    창원시 의창구  명곡동   53120  27013  26107    18968
2  201102  48129530  경상남도    창원시 진해구  충무동    4888   2481   2407     2161
3  201102  48121550  경상남도    창원시 의창구  용지동   37057  18613  18444    13779
4  201105  48127250  경상남도  창원시 마산회원구  내서읍   73367  36961  36406    23663

In [14]:
mcz_fr = pd.read_csv('C:\\Users\SAMSUNG\Desktop\SSAC\머신러닝\메인프로젝트/마창진_외국인구.csv', encoding = 'cp949', thousands = ',')
mcz_fr

        기준년월     행정동코드   시도명       시군구명  행정동명  외국인 소계  외국인 남  외국인 여
0     201203  48125340  경상남도  창원시 마산합포구   진전면     101     66     35
1     201102  48123530  경상남도    창원시 성산구   상남동     224    136     88
2     201011  48123520  경상남도    창원시 성산구   중앙동     524    303    221
3     201007  48127590  경상남도  창원시 마산회원구  합성2동     242    115    127
4     201102  48129530  경상남도    창원시 진해구   충무동      32     14     18
...      ...       ...   ...        ...   ...     ...    ...    ...
6827  202004  48129610  경상남도    창원시 진해구   덕산동      42     15     27
6828  202004  48129620  경상남도    창원시 진해구   풍호동      72     30     42
6829  202004  48129630  경상남도    창원시 진해구   웅천동     285    245     40
6830  202004  48129640  경상남도    창원시 진해구  웅동1동     714    670     44
6831  202004  48129650  경상남도    창원시 진해구  웅동2동    1544    804    740

[6832 rows x 8 columns]

In [16]:
mcz_fr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6832 entries, 0 to 6831
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기준년월    6832 non-null   int64
 1   행정동코드   6832 non-null   int64
 2   시도명     6832 non-null   object
 3   시군구명    6832 non-null   object
 4   행정동명    6832 non-null   object
 5   외국인 소계  6832 non-null   int64
 6   외국인 남   6832 non-null   int64
 7   외국인 여   6832 non-null   int64
dtypes: int64(5), object(3)
memory usage: 427.1+ KB

In [22]:
mcz_fr.기준년월.unique()

array([201203, 201102, 201011, 201007, 201204, 201106, 201104, 201108,
       201111, 201211, 201008, 201306, 201404, 201609, 201009, 201010,
       201704, 201012, 201309, 201103, 201410, 201202, 201101, 201302,
       201107, 201504, 201705, 201109, 201112, 201201, 201711, 201811,
       201407, 201212, 201411, 201708, 201105, 201209, 201312, 201207,
       201206, 201503, 201110, 201506, 201208, 201210, 201305, 201510,
       201308, 201403, 201810, 201301, 201602, 201610, 201703, 201501,
       201205, 201907, 201310, 201806, 201502, 201405, 201303, 201908,
       201909, 201910, 201505, 201911, 201406, 201912, 201508, 201409,
       201304, 201311, 201307, 201603, 201412, 201402, 201401, 201604,
       201611, 201605, 201701, 201509, 201408, 201511, 201601, 201901,
       201707, 201709, 201702, 201804, 201801, 201802, 201507, 201803,
       201512, 202001, 202002, 201606, 201809, 201607, 202003, 201706,
       201608, 202004, 201710, 201612, 201906, 201712, 201805, 201807,
       201812, 201808, 201904, 201902, 201905, 201903], dtype=int64)

In [30]:
mcz_fr_20 = mcz_fr[mcz_fr['기준년월'].apply(lambda x : x > 202003)]
mcz_fr_20

        기준년월     행정동코드   시도명       시군구명   행정동명  외국인 소계  외국인 남  외국인 여
4372  202004  48127510  경상남도  창원시 마산회원구   회원1동      67     20     47
6727  202004  48121550  경상남도    창원시 의창구    용지동     307    123    184
6733  202004  48123510  경상남도    창원시 성산구    반송동     250    112    138
6762  202004  48123520  경상남도    창원시 성산구    중앙동    1038    617    421
6769  202004  48123530  경상남도    창원시 성산구    상남동     299     88    211
6776  202004  48127570  경상남도  창원시 마산회원구   양덕2동     123     74     49
6783  202004  48123540  경상남도    창원시 성산구    사파동     298    121    177
6784  202004  48121250  경상남도    창원시 의창구     동읍     197    114     83
6785  202004  48123550  경상남도    창원시 성산구   가음정동     306    167    139
6786  202004  48121310  경상남도    창원시 의창구     북면     271    133    138
6787  202004  48125565  경상남도  창원시 마산합포구  반월중앙동      74     19     55
6788  202004  48121320  경상남도    창원시 의창구    대산면     344    287     57
6789  202004  48121510  경상남도    창원시 의창구    의창동     238     81    157
6790  202004  48125530  경상남도  창원시 마산합포구    월영동     429    189    240
6791  202004  48121520  경상남도    창원시 의창구    팔룡동    1003    755    248
6792  202004  48121530  경상남도    창원시 의창구    명곡동     638    291    347
6793  202004  48121540  경상남도    창원시 의창구    봉림동     607    271    336
6794  202004  48123560  경상남도    창원시 성산구    성주동     485    406     79
6795  202004  48123570  경상남도    창원시 성산구    웅남동     961    910     51
6796  202004  48125310  경상남도  창원시 마산합포구    구산면     219    206     13
6797  202004  48125320  경상남도  창원시 마산합포구    진동면     188     93     95
6798  202004  48125330  경상남도  창원시 마산합포구    진북면     391    351     40
6799  202004  48125340  경상남도  창원시 마산합포구    진전면     111     86     25
6800  202004  48125540  경상남도  창원시 마산합포구    문화동     140     63     77
6801  202004  48125510  경상남도  창원시 마산합포구     현동     117     71     46
6802  202004  48125520  경상남도  창원시 마산합포구    가포동      35     32      3
6803  202004  48125650  경상남도  창원시 마산합포구    산호동     126     46     80
6804  202004  48127250  경상남도  창원시 마산회원구    내서읍     473    263    210
6805  202004  48125570  경상남도  창원시 마산합포구    완월동      40      9     31
6806  202004  48125580  경상남도  창원시 마산합포구    자산동      48     11     37
6807  202004  48125610  경상남도  창원시 마산합포구    교방동      54     12     42
6808  202004  48125630  경상남도  창원시 마산합포구    오동동     143     57     86
6809  202004  48125640  경상남도  창원시 마산합포구    합포동      43     12     31
6810  202004  48127520  경상남도  창원시 마산회원구   회원2동      26      5     21
6811  202004  48127545  경상남도  창원시 마산회원구    석전동     113     40     73
6812  202004  48127550  경상남도  창원시 마산회원구    회성동      39      9     30
6813  202004  48127560  경상남도  창원시 마산회원구   양덕1동     103     52     51
6814  202004  48127580  경상남도  창원시 마산회원구   합성1동      60     22     38
6815  202004  48127590  경상남도  창원시 마산회원구   합성2동     183     76    107
6816  202004  48127600  경상남도  창원시 마산회원구   구암1동      73     17     56
6817  202004  48127610  경상남도  창원시 마산회원구   구암2동     145     70     75
6818  202004  48127620  경상남도  창원시 마산회원구    봉암동     595    449    146
6819  202004  48129530  경상남도    창원시 진해구    충무동     111     65     46
6820  202004  48129540  경상남도    창원시 진해구    여좌동     100     44     56
6821  202004  48129550  경상남도    창원시 진해구    태백동      27     11     16
6822  202004  48129560  경상남도    창원시 진해구    경화동      65     27     38
6823  202004  48129570  경상남도    창원시 진해구    병암동      41     11     30
6824  202004  48129580  경상남도    창원시 진해구     석동     137     70     67
6825  202004  48129590  경상남도    창원시 진해구     이동     119     50     69
6826  202004  48129600  경상남도    창원시 진해구    자은동     106     28     78
6827  202004  48129610  경상남도    창원시 진해구    덕산동      42     15     27
6828  202004  48129620  경상남도    창원시 진해구    풍호동      72     30     42
6829  202004  48129630  경상남도    창원시 진해구    웅천동     285    245     40
6830  202004  48129640  경상남도    창원시 진해구   웅동1동     714    670     44
6831  202004  48129650  경상남도    창원시 진해구   웅동2동    1544    804    740

In [35]:
# 진해 경찰서뽑기 
jinhe = mcz_fr_20[mcz_fr_20['시군구명'] == '창원시 진해구'].drop(['행정동코드','시도명','행정동명','외국인 남','외국인 여'], axis = 1)
jinhe = jinhe.reset_index(drop = True)
jinhe

      기준년월     시군구명  외국인 소계
0   202004  창원시 진해구     111
1   202004  창원시 진해구     100
2   202004  창원시 진해구      27
3   202004  창원시 진해구      65
4   202004  창원시 진해구      41
5   202004  창원시 진해구     137
6   202004  창원시 진해구     119
7   202004  창원시 진해구     106
8   202004  창원시 진해구      42
9   202004  창원시 진해구      72
10  202004  창원시 진해구     285
11  202004  창원시 진해구     714
12  202004  창원시 진해구    1544

In [50]:
masan = mcz_fr_20[mcz_fr_20['시군구명'].str.contains('마산')].drop(['행정동코드','시도명','행정동명','외국인 남','외국인 여'], axis = 1)
masan = masan.reset_index(drop = True)
masan.head()

     기준년월       시군구명  외국인 소계
0  202004  창원시 마산회원구      67
1  202004  창원시 마산회원구     123
2  202004  창원시 마산합포구      74
3  202004  창원시 마산합포구     429
4  202004  창원시 마산합포구     219

In [101]:
chang = mcz_fr_20[mcz_fr_20['시군구명'].isin(['창원시 성산구', '창원시 의창구'])].drop(['행정동코드','시도명','행정동명','외국인 남','외국인 여'], axis = 1)
chang = chang.reset_index(drop = True)
chang

      기준년월     시군구명  외국인 소계
0   202004  창원시 의창구     307
1   202004  창원시 성산구     250
2   202004  창원시 성산구    1038
3   202004  창원시 성산구     299
4   202004  창원시 성산구     298
5   202004  창원시 의창구     197
6   202004  창원시 성산구     306
7   202004  창원시 의창구     271
8   202004  창원시 의창구     344
9   202004  창원시 의창구     238
10  202004  창원시 의창구    1003
11  202004  창원시 의창구     638
12  202004  창원시 의창구     607
13  202004  창원시 성산구     485
14  202004  창원시 성산구     961

### 창원

In [102]:
# 창원 외국인 합계
# 중부가 성산구
# 서부가 의창구
chang['jur_stn'] = chang['시군구명'].replace('창원시 의창구','창원서부경찰서').replace('창원시 성산구','창원중부경찰서')
chang

      기준년월     시군구명  외국인 소계  jur_stn
0   202004  창원시 의창구     307  창원서부경찰서
1   202004  창원시 성산구     250  창원중부경찰서
2   202004  창원시 성산구    1038  창원중부경찰서
3   202004  창원시 성산구     299  창원중부경찰서
4   202004  창원시 성산구     298  창원중부경찰서
5   202004  창원시 의창구     197  창원서부경찰서
6   202004  창원시 성산구     306  창원중부경찰서
7   202004  창원시 의창구     271  창원서부경찰서
8   202004  창원시 의창구     344  창원서부경찰서
9   202004  창원시 의창구     238  창원서부경찰서
10  202004  창원시 의창구    1003  창원서부경찰서
11  202004  창원시 의창구     638  창원서부경찰서
12  202004  창원시 의창구     607  창원서부경찰서
13  202004  창원시 성산구     485  창원중부경찰서
14  202004  창원시 성산구     961  창원중부경찰서

In [73]:
#chang['시군구명'] = chang['시군구명']#.replace('창원시 의창구','창원시').replace('창원시 성산구','창원시')

      기준년월 시군구명  외국인 소계  jur_stn
0   202004  창원시     307  창원서부경찰서
1   202004  창원시     250  창원중부경찰서
2   202004  창원시    1038  창원중부경찰서
3   202004  창원시     299  창원중부경찰서
4   202004  창원시     298  창원중부경찰서
5   202004  창원시     197  창원서부경찰서
6   202004  창원시     306  창원중부경찰서
7   202004  창원시     271  창원서부경찰서
8   202004  창원시     344  창원서부경찰서
9   202004  창원시     238  창원서부경찰서
10  202004  창원시    1003  창원서부경찰서
11  202004  창원시     638  창원서부경찰서
12  202004  창원시     607  창원서부경찰서
13  202004  창원시     485  창원중부경찰서
14  202004  창원시     961  창원중부경찰서

In [103]:
# 창원시 외국인 합계
changwon = chang.groupby(['jur_stn','시군구명'],as_index = False).sum().drop(['기준년월'], axis = 1)
changwon['year'] = chang['기준년월']
changwon

   jur_stn     시군구명  외국인 소계    year
0  창원서부경찰서  창원시 의창구    3605  202004
1  창원중부경찰서  창원시 성산구    3637  202004

In [104]:
changwon['year'] = changwon['year'].apply(lambda x : str(x)[:4])
changwon

   jur_stn     시군구명  외국인 소계  year
0  창원서부경찰서  창원시 의창구    3605  2020
1  창원중부경찰서  창원시 성산구    3637  2020

### 마산

In [77]:
masan.head()

     기준년월       시군구명  외국인 소계
0  202004  창원시 마산회원구      67
1  202004  창원시 마산회원구     123
2  202004  창원시 마산합포구      74
3  202004  창원시 마산합포구     429
4  202004  창원시 마산합포구     219

In [78]:
masan['jur_stn'] = masan['시군구명'].replace('창원시 마산회원구','마산동부경찰서').replace('창원시 마산합포구','마산중부경찰서')
masan.head()

     기준년월       시군구명  외국인 소계  jur_stn
0  202004  창원시 마산회원구      67  마산동부경찰서
1  202004  창원시 마산회원구     123  마산동부경찰서
2  202004  창원시 마산합포구      74  마산중부경찰서
3  202004  창원시 마산합포구     429  마산중부경찰서
4  202004  창원시 마산합포구     219  마산중부경찰서

In [79]:
# 마산 외국인 합계
masan_p = masan.groupby(['jur_stn','시군구명'],as_index = False).sum().drop(['기준년월'], axis = 1)
masan_p['year'] = masan['기준년월']
masan_p

   jur_stn       시군구명  외국인 소계    year
0  마산동부경찰서  창원시 마산회원구    2000  202004
1  마산중부경찰서  창원시 마산합포구    2158  202004

In [86]:
masan_p['year'] = masan_p['year'].apply(lambda x : str(x)[:4])
masan_p

   jur_stn       시군구명  외국인 소계  year
0  마산동부경찰서  창원시 마산회원구    2000  2020
1  마산중부경찰서  창원시 마산합포구    2158  2020

### 진해

In [80]:
jinhe.head()

     기준년월     시군구명  외국인 소계
0  202004  창원시 진해구     111
1  202004  창원시 진해구     100
2  202004  창원시 진해구      27
3  202004  창원시 진해구      65
4  202004  창원시 진해구      41

In [90]:
jinhe['jur_stn'] = jinhe['시군구명'].replace('창원시 진해구','진해경찰서')
jinhe.head()

     기준년월     시군구명  외국인 소계 jur_stn
0  202004  창원시 진해구     111   진해경찰서
1  202004  창원시 진해구     100   진해경찰서
2  202004  창원시 진해구      27   진해경찰서
3  202004  창원시 진해구      65   진해경찰서
4  202004  창원시 진해구      41   진해경찰서

In [91]:
# 진해 외국인 합계
jinhe_p = jinhe.groupby(['jur_stn','시군구명'],as_index = False).sum().drop(['기준년월'], axis = 1)
jinhe_p['year'] = jinhe['기준년월']
jinhe_p

  jur_stn     시군구명  외국인 소계    year
0   진해경찰서  창원시 진해구    3363  202004

In [93]:
jinhe_p['year'] = jinhe_p['year'].apply(lambda x : str(x)[:4])
jinhe_p

  jur_stn     시군구명  외국인 소계  year
0   진해경찰서  창원시 진해구    3363  2020

### 수원

In [94]:
suwon = pd.DataFrame()

raw_data = {
    'jur_stn' : ['수원남부경찰서','수원서부경찰서','수원중부경찰서'],
    '시군구명' : ['수원시 영통구','수원시 팔달구','수원시 장안구'],
    '외국인 소계' : [6962,12809,6548],
    'year' : [2020,2020,2020]
}

suwon = pd.DataFrame(raw_data)
suwon.head()

   jur_stn     시군구명  외국인 소계  year
0  수원남부경찰서  수원시 영통구    6962  2020
1  수원서부경찰서  수원시 팔달구   12809  2020
2  수원중부경찰서  수원시 장안구    6548  2020

In [146]:
df_fr = pd.concat([suwon,changwon,masan_p,jinhe_p]).reset_index(drop = True)
df_fr

   jur_stn       시군구명  외국인 소계  year
0  수원남부경찰서    수원시 영통구    6962  2020
1  수원서부경찰서    수원시 팔달구   12809  2020
2  수원중부경찰서    수원시 장안구    6548  2020
3  창원서부경찰서    창원시 의창구    3605  2020
4  창원중부경찰서    창원시 성산구    3637  2020
5  마산동부경찰서  창원시 마산회원구    2000  2020
6  마산중부경찰서  창원시 마산합포구    2158  2020
7    진해경찰서    창원시 진해구    3363  2020

In [106]:
os.getcwd()

'C:\\Users\\SAMSUNG\\Documents\\dev\\Main_project_police\\processing_code'

In [107]:
df_fr.to_csv('./외국인인구수.csv', index = False)

### 국내 인구 수

In [108]:
mcz_kr.head()

     기준년월     행정동코드   시도명       시군구명 행정동명  한국인 소계  한국인 남  한국인 여  한국인 세대수
0  201102  48123570  경상남도    창원시 성산구  웅남동   10346   5486   4860     3883
1  201102  48121530  경상남도    창원시 의창구  명곡동   53120  27013  26107    18968
2  201102  48129530  경상남도    창원시 진해구  충무동    4888   2481   2407     2161
3  201102  48121550  경상남도    창원시 의창구  용지동   37057  18613  18444    13779
4  201105  48127250  경상남도  창원시 마산회원구  내서읍   73367  36961  36406    23663

In [110]:
mcz_kr_20 = mcz_kr[mcz_kr['기준년월'].apply(lambda x : x > 202003)]
mcz_kr_20.head()

        기준년월     행정동코드   시도명       시군구명   행정동명  한국인 소계  한국인 남  한국인 여  한국인 세대수
6322  202004  48123550  경상남도    창원시 성산구   가음정동   41907  21281  20626    15634
6366  202004  48127590  경상남도  창원시 마산회원구   합성2동    8046   4030   4016     4258
6373  202004  48125565  경상남도  창원시 마산합포구  반월중앙동   15415   7531   7884     6570
6374  202004  48121250  경상남도    창원시 의창구     동읍   20477  10424  10053     8823
6375  202004  48121310  경상남도    창원시 의창구     북면   42606  21538  21068    15978

In [111]:
# 진해 경찰서뽑기 
jinhe_kr = mcz_kr_20[mcz_kr_20['시군구명'] == '창원시 진해구'].drop(['행정동코드','시도명','행정동명','한국인 남','한국인 여'], axis = 1)
jinhe_kr = jinhe_kr.reset_index(drop = True)
jinhe_kr

      기준년월     시군구명  한국인 소계  한국인 세대수
0   202004  창원시 진해구   17656     7719
1   202004  창원시 진해구    9009     4392
2   202004  창원시 진해구    5264     2700
3   202004  창원시 진해구   11538     4623
4   202004  창원시 진해구    7689     3352
5   202004  창원시 진해구   17469     6786
6   202004  창원시 진해구    8575     4432
7   202004  창원시 진해구   21703     8670
8   202004  창원시 진해구   10294     4098
9   202004  창원시 진해구   26322     9099
10  202004  창원시 진해구   12434     5121
11  202004  창원시 진해구    6592     2743
12  202004  창원시 진해구   38214    16559

In [126]:
# 마산 뽑기
masan_kr = mcz_kr_20[mcz_kr_20['시군구명'].str.contains('마산')].drop(['행정동코드','시도명','행정동명','한국인 남','한국인 여'], axis = 1)
masan_kr = masan_kr.reset_index(drop = True)
masan_kr.head()

     기준년월       시군구명  한국인 소계  한국인 세대수
0  202004  창원시 마산회원구    8046     4258
1  202004  창원시 마산합포구   15415     6570
2  202004  창원시 마산합포구    9606     4087
3  202004  창원시 마산합포구   11265     4958
4  202004  창원시 마산합포구    4392     2300

In [113]:
# 창원 뽑기
chang_kr = mcz_kr_20[mcz_kr_20['시군구명'].isin(['창원시 성산구', '창원시 의창구'])].drop(['행정동코드','시도명','행정동명','한국인 남','한국인 여'], axis = 1)
chang_kr = chang_kr.reset_index(drop = True)
chang_kr

      기준년월     시군구명  한국인 소계  한국인 세대수
0   202004  창원시 성산구   41907    15634
1   202004  창원시 의창구   20477     8823
2   202004  창원시 의창구   42606    15978
3   202004  창원시 의창구    7372     3689
4   202004  창원시 의창구   50440    20334
5   202004  창원시 의창구   36323    14272
6   202004  창원시 의창구   43511    17995
7   202004  창원시 성산구   26971     9524
8   202004  창원시 의창구   30864    15228
9   202004  창원시 의창구   30648    13016
10  202004  창원시 성산구   42589    15340
11  202004  창원시 성산구   23174    12913
12  202004  창원시 성산구   28674    10456
13  202004  창원시 성산구   46518    18201
14  202004  창원시 성산구    8115     3428

In [114]:
chang_kr['jur_stn'] = chang_kr['시군구명'].replace('창원시 의창구','창원서부경찰서').replace('창원시 성산구','창원중부경찰서')
chang_kr

      기준년월     시군구명  한국인 소계  한국인 세대수  jur_stn
0   202004  창원시 성산구   41907    15634  창원중부경찰서
1   202004  창원시 의창구   20477     8823  창원서부경찰서
2   202004  창원시 의창구   42606    15978  창원서부경찰서
3   202004  창원시 의창구    7372     3689  창원서부경찰서
4   202004  창원시 의창구   50440    20334  창원서부경찰서
5   202004  창원시 의창구   36323    14272  창원서부경찰서
6   202004  창원시 의창구   43511    17995  창원서부경찰서
7   202004  창원시 성산구   26971     9524  창원중부경찰서
8   202004  창원시 의창구   30864    15228  창원서부경찰서
9   202004  창원시 의창구   30648    13016  창원서부경찰서
10  202004  창원시 성산구   42589    15340  창원중부경찰서
11  202004  창원시 성산구   23174    12913  창원중부경찰서
12  202004  창원시 성산구   28674    10456  창원중부경찰서
13  202004  창원시 성산구   46518    18201  창원중부경찰서
14  202004  창원시 성산구    8115     3428  창원중부경찰서

### 창원

In [115]:
#창원 한국 인구 수
changwon_kr = chang_kr.groupby(['jur_stn','시군구명'],as_index = False).sum().drop(['기준년월'], axis = 1)
changwon_kr['year'] = chang_kr['기준년월']
changwon_kr

   jur_stn     시군구명  한국인 소계  한국인 세대수    year
0  창원서부경찰서  창원시 의창구  262241   109335  202004
1  창원중부경찰서  창원시 성산구  217948    85496  202004

In [117]:
changwon_kr['year'] = changwon_kr['year'].apply(lambda x : str(x)[:4])
changwon_kr.drop(['한국인 세대수'], axis = 1, inplace = True)
changwon_kr

   jur_stn     시군구명  한국인 소계  year
0  창원서부경찰서  창원시 의창구  262241  2020
1  창원중부경찰서  창원시 성산구  217948  2020

### 마산

In [129]:
# 마산 뽑기
masan_kr = mcz_kr_20[mcz_kr_20['시군구명'].str.contains('마산')].drop(['행정동코드','시도명','행정동명','한국인 남','한국인 여'], axis = 1)
masan_kr = masan_kr.reset_index(drop = True)
masan_kr.head()

     기준년월       시군구명  한국인 소계  한국인 세대수
0  202004  창원시 마산회원구    8046     4258
1  202004  창원시 마산합포구   15415     6570
2  202004  창원시 마산합포구    9606     4087
3  202004  창원시 마산합포구   11265     4958
4  202004  창원시 마산합포구    4392     2300

In [130]:
masan_kr['jur_stn'] = masan_kr['시군구명'].replace('창원시 마산회원구','마산동부경찰서').replace('창원시 마산합포구','마산중부경찰서')
masan_kr.head()

     기준년월       시군구명  한국인 소계  한국인 세대수  jur_stn
0  202004  창원시 마산회원구    8046     4258  마산동부경찰서
1  202004  창원시 마산합포구   15415     6570  마산중부경찰서
2  202004  창원시 마산합포구    9606     4087  마산중부경찰서
3  202004  창원시 마산합포구   11265     4958  마산중부경찰서
4  202004  창원시 마산합포구    4392     2300  마산중부경찰서

In [131]:
# 마산 한국인 합계
masan_kra = masan_kr.groupby(['jur_stn','시군구명'],as_index = False).sum().drop(['기준년월'], axis = 1)
masan_kra['year'] = masan_kr['기준년월']
masan_kra

   jur_stn       시군구명  한국인 소계  한국인 세대수    year
0  마산동부경찰서  창원시 마산회원구  193101    81229  202004
1  마산중부경찰서  창원시 마산합포구  175504    78575  202004

In [132]:
masan_kra['year'] = masan_kra['year'].apply(lambda x : str(x)[:4])
masan_kra.drop(['한국인 세대수'], axis = 1, inplace = True)
masan_kra

   jur_stn       시군구명  한국인 소계  year
0  마산동부경찰서  창원시 마산회원구  193101  2020
1  마산중부경찰서  창원시 마산합포구  175504  2020

### 진해

In [133]:
jinhe_kr.head()

     기준년월     시군구명  한국인 소계  한국인 세대수
0  202004  창원시 진해구   17656     7719
1  202004  창원시 진해구    9009     4392
2  202004  창원시 진해구    5264     2700
3  202004  창원시 진해구   11538     4623
4  202004  창원시 진해구    7689     3352

In [136]:
jinhe_kr['jur_stn'] = jinhe_kr['시군구명'].replace('창원시 진해구','진해경찰서')
jinhe_kr.head()

     기준년월     시군구명  한국인 소계  한국인 세대수 jur_stn
0  202004  창원시 진해구   17656     7719   진해경찰서
1  202004  창원시 진해구    9009     4392   진해경찰서
2  202004  창원시 진해구    5264     2700   진해경찰서
3  202004  창원시 진해구   11538     4623   진해경찰서
4  202004  창원시 진해구    7689     3352   진해경찰서

In [137]:
jinhe_kra = jinhe_kr.groupby(['jur_stn','시군구명'],as_index = False).sum().drop(['기준년월'], axis = 1)
jinhe_kra['year'] = jinhe_kr['기준년월']
jinhe_kra

  jur_stn     시군구명  한국인 소계  한국인 세대수    year
0   진해경찰서  창원시 진해구  192759    80294  202004

In [138]:
jinhe_kra['year'] = jinhe_kra['year'].apply(lambda x : str(x)[:4])
jinhe_kra.drop(['한국인 세대수'], axis = 1, inplace = True)
jinhe_kra

  jur_stn     시군구명  한국인 소계  year
0   진해경찰서  창원시 진해구  192759  2020

In [142]:
# 마창진 df 합치기
mcz_df = pd.concat([changwon_kr, masan_kra, jinhe_kra])
mcz_df

   jur_stn       시군구명  한국인 소계  year
0  창원서부경찰서    창원시 의창구  262241  2020
1  창원중부경찰서    창원시 성산구  217948  2020
0  마산동부경찰서  창원시 마산회원구  193101  2020
1  마산중부경찰서  창원시 마산합포구  175504  2020
0    진해경찰서    창원시 진해구  192759  2020

### 수원

In [143]:
# 통계값이 '휴먼시티수원' 사이트에 공개되어있기 때문에 그대로 가져옴
raw_data = {
    'jur_stn' : ['수원남부경찰서','수원서부경찰서','수원중부경찰서'],
    '시군구명' : ['수원시 영통구','수원시 팔달구','수원시 장안구'],
    '한국인 소계' : [368842,174930,273661],
    'year' : [2020,2020,2020]
}

suwon_kr = pd.DataFrame(raw_data)
suwon_kr.head()

   jur_stn     시군구명  한국인 소계  year
0  수원남부경찰서  수원시 영통구  368842  2020
1  수원서부경찰서  수원시 팔달구  174930  2020
2  수원중부경찰서  수원시 장안구  273661  2020

In [145]:
df_merge2 = pd.concat([mcz_df, suwon_kr]).reset_index(drop = True)
df_merge2

   jur_stn       시군구명  한국인 소계  year
0  창원서부경찰서    창원시 의창구  262241  2020
1  창원중부경찰서    창원시 성산구  217948  2020
2  마산동부경찰서  창원시 마산회원구  193101  2020
3  마산중부경찰서  창원시 마산합포구  175504  2020
4    진해경찰서    창원시 진해구  192759  2020
5  수원남부경찰서    수원시 영통구  368842  2020
6  수원서부경찰서    수원시 팔달구  174930  2020
7  수원중부경찰서    수원시 장안구  273661  2020

In [147]:
df_merge2.to_csv('./마창진수원인구수.csv', index = False)