In [65]:
# 경찰서별 담당 행정구역
sgg_nm_transfer = {
    '마산동부경찰서' : '창원시마산회원구'  ,
    '마산중부경찰서' : '창원시마산합포구'  ,
    '서울강남경찰서' : '강남구'  , 
    '서울강동경찰서' : '강동구' , 
    '서울강북경찰서' :'강북구'  , 
    '서울강서경찰서' :  '강서구',
    '서울관악경찰서' : '관악구' ,
      '서울광진경찰서' : '광진구', 
     '서울구로경찰서' : '구로구' , 
     '서울금천경찰서' : '금천구' , 
    '서울남대문경찰서' : '중구' , 
    '서울노원경찰서' : '노원구' ,
    '서울도봉경찰서' : '도봉구'  , 
    '서울동대문경찰서' : '동대문구'  , 
    '서울동작경찰서' : '동작구'  , 
    '서울마포경찰서' : '마포구' , 
    '서울방배경찰서' : '서초구', 
    '서울서대문경찰서' : '서대문구' ,
    '서울서부경찰서' : '은평구' , 
    '서울서초경찰서' : '서초구' , 
    '서울성동경찰서' : '성동구' , 
    '서울성북경찰서' :'성북구' , 
    '서울송파경찰서' :'송파구' , 
    '서울수서경찰서' : '강남구' ,
     '서울양천경찰서': '양천구'  , 
    '서울영등포경찰서' : '영등포구' , 
    '서울용산경찰서': '용산구'  , 
    '서울은평경찰서' : '은평구' , 
    '서울종로경찰서': '종로구', 
    '서울종암경찰서' : '성북구'  ,
     '서울중랑경찰서' : '중랑구'   , 
    '서울중부경찰서' : '중구'  , 
    '서울혜화경찰서': '종로구'  , 
    '세종경찰서' : '세종시'  , 
    '수원남부경찰서': '수원시영통구'  ,
   '수원서부경찰서' : '수원시팔달구'  ,  
    '수원중부경찰서' :'수원시장안구'   , 
    '진주경찰서' : '진주시'  ,
    '진해경찰서' : '창원시진해구'  , 
    '창원서부경찰서' : '창원시의창구' , 
    '창원중부경찰서': '창원시성산구'
    
}

### 14. 연령별 인구 데이터

- popu_합계: 전체 인구
- for_합계: 외국인 인구
- popu_u20: 20세 미만 인구
- popu_2030: 2030대 인구
- popu_4050: 4050대 인구
- popu_o60: 60세 이상 인구
- for_u20: 20세 미만 외국인 인구
- for_2030: 2030대 외국인 인구
- for_4050: 4050대 외국인 인구
- for_o60: 60세 이상 외국인 인구

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv('report.txt', sep = '\t', thousands = ',')

In [17]:
df

,기간,행정구역별,구분,계,0~4세,5~9세,10~14세,15~19세,20~24세,25~29세,...,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85~89세,90~94세,95~99세,100세 이상
0,2020,합계,계,9911088,277293,359387,375617,416854,666221,858648,...,766358,726905,533767,406116,300147,188621,90072,"33,584","9,211","6,813"
1,2020,합계,한국인,9668465,270481,353264,371652,410214,630115,830296,...,738826,714460,529494,404546,299530,188219,89875,"33,503","9,180","6,792"
2,2020,합계,등록외국인,242623,6812,6123,3965,6640,36106,28352,...,27532,12445,4273,1570,617,402,197,81,31,21
3,2020,종로구,계,158996,3197,4596,5261,6463,13721,14261,...,13120,11780,8569,6784,5787,4011,1985,804,291,276
4,2020,종로구,한국인,149384,3080,4447,5152,5861,10474,12942,...,12567,11484,8464,6732,5768,3999,1979,802,291,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2020,송파구,한국인,667960,21984,28760,29061,30007,40237,53882,...,49750,48265,35919,24716,15724,9165,4967,"1,984",535,299
74,2020,송파구,등록외국인,5966,163,173,99,68,290,618,...,736,319,102,37,19,11,3,2,-,-
75,2020,강동구,계,463998,15408,19549,19381,19703,26857,35248,...,36536,36774,26769,18646,12027,6925,3531,"1,486",379,256
76,2020,강동구,한국인,459970,15301,19449,19321,19640,26636,34821,...,35990,36542,26702,18615,12017,6920,3530,"1,485",379,255
77,2020,강동구,등록외국인,4028,107,100,60,63,221,427,...,546,232,67,31,10,5,1,1,-,1

In [18]:
df = df.replace('-', 0)

In [19]:
df

,기간,행정구역별,구분,계,0~4세,5~9세,10~14세,15~19세,20~24세,25~29세,...,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85~89세,90~94세,95~99세,100세 이상
0,2020,합계,계,9911088,277293,359387,375617,416854,666221,858648,...,766358,726905,533767,406116,300147,188621,90072,"33,584","9,211","6,813"
1,2020,합계,한국인,9668465,270481,353264,371652,410214,630115,830296,...,738826,714460,529494,404546,299530,188219,89875,"33,503","9,180","6,792"
2,2020,합계,등록외국인,242623,6812,6123,3965,6640,36106,28352,...,27532,12445,4273,1570,617,402,197,81,31,21
3,2020,종로구,계,158996,3197,4596,5261,6463,13721,14261,...,13120,11780,8569,6784,5787,4011,1985,804,291,276
4,2020,종로구,한국인,149384,3080,4447,5152,5861,10474,12942,...,12567,11484,8464,6732,5768,3999,1979,802,291,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2020,송파구,한국인,667960,21984,28760,29061,30007,40237,53882,...,49750,48265,35919,24716,15724,9165,4967,"1,984",535,299
74,2020,송파구,등록외국인,5966,163,173,99,68,290,618,...,736,319,102,37,19,11,3,2,0,0
75,2020,강동구,계,463998,15408,19549,19381,19703,26857,35248,...,36536,36774,26769,18646,12027,6925,3531,"1,486",379,256
76,2020,강동구,한국인,459970,15301,19449,19321,19640,26636,34821,...,35990,36542,26702,18615,12017,6920,3530,"1,485",379,255
77,2020,강동구,등록외국인,4028,107,100,60,63,221,427,...,546,232,67,31,10,5,1,1,0,1

In [20]:
df.columns

Index(['기간', '행정구역별', '구분', '계', '0~4세', '5~9세', '10~14세', '15~19세', '20~24세',
       '25~29세', '30~34세', '35~39세', '40~44세', '45~49세', '50~54세', '55~59세',
       '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85~89세', '90~94세',
       '95~99세', '100세 이상'],
      dtype='object')

In [21]:
df.dtypes

기간          int64
행정구역별      object
구분         object
계           int64
0~4세        int64
5~9세        int64
10~14세      int64
15~19세      int64
20~24세      int64
25~29세      int64
30~34세      int64
35~39세      int64
40~44세      int64
45~49세      int64
50~54세      int64
55~59세      int64
60~64세      int64
65~69세      int64
70~74세      int64
75~79세      int64
80~84세      int64
85~89세      int64
90~94세     object
95~99세     object
100세 이상    object
dtype: object

In [24]:
df = df[df['구분'].isin(['계', '등록외국인'])]

In [25]:
dfa = df[df['구분'].isin(['계'])]

In [26]:
dff = df[df['구분'].isin(['등록외국인'])]

In [29]:
dfa.columns

Index(['기간', '행정구역별', '구분', '계', '0~4세', '5~9세', '10~14세', '15~19세', '20~24세',
       '25~29세', '30~34세', '35~39세', '40~44세', '45~49세', '50~54세', '55~59세',
       '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85~89세', '90~94세',
       '95~99세', '100세 이상'],
      dtype='object')

In [27]:
dfa

,기간,행정구역별,구분,계,0~4세,5~9세,10~14세,15~19세,20~24세,25~29세,...,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85~89세,90~94세,95~99세,100세 이상
0,2020,합계,계,9911088,277293,359387,375617,416854,666221,858648,...,766358,726905,533767,406116,300147,188621,90072,"33,584","9,211","6,813"
3,2020,종로구,계,158996,3197,4596,5261,6463,13721,14261,...,13120,11780,8569,6784,5787,4011,1985,804,291,276
6,2020,중구,계,134635,3540,3827,3288,4006,9510,12167,...,11141,10431,7669,5988,4858,3202,1668,700,205,205
9,2020,용산구,계,244645,6897,7981,7775,8851,14684,21248,...,18813,17332,12245,9547,7842,5666,2939,"1,197",438,373
12,2020,성동구,계,300505,10197,10503,9180,10996,21368,26519,...,23842,21893,14994,11569,9065,5878,2654,935,254,254
15,2020,광진구,계,360109,8719,11536,12429,14278,29342,38579,...,27775,25518,17703,12896,9593,6118,2752,991,288,219
18,2020,동대문구,계,357014,9720,11422,11153,13154,31905,33057,...,26762,26681,20102,15656,12591,7868,3680,"1,224",362,313
21,2020,중랑구,계,399562,10726,12677,12480,14497,24114,33161,...,35797,34092,24394,18118,13364,8099,3665,"1,274",327,206
24,2020,성북구,계,447056,12400,16743,17432,20356,35905,36514,...,32962,31714,23440,18599,15024,9758,4490,"1,658",416,385
27,2020,강북구,계,311569,6706,9169,10082,12057,20228,23779,...,26457,26106,20006,16575,13553,8107,3417,"1,176",337,251
30,2020,도봉구,계,327361,7975,10890,11729,13961,20677,23339,...,28435,28958,20884,15534,12187,7866,3742,"1,354",317,175
33,2020,노원구,계,527032,13583,19728,24300,29159,38754,36247,...,41304,39316,28634,21248,16311,10940,5558,"2,013",496,289
36,2020,은평구,계,484043,12961,16953,18148,20737,29987,37868,...,37891,37198,27543,22050,17132,11072,4850,"1,661",454,425
39,2020,서대문구,계,322952,9170,11272,11092,13280,26000,29760,...,24250,22628,16454,13382,11100,7734,3577,"1,287",371,299
42,2020,마포구,계,381858,11660,13573,13907,14951,28016,38160,...,26019,23274,16757,13350,11075,7439,3685,"1,319",358,348
45,2020,양천구,계,457781,12013,19711,24885,26107,29147,31170,...,36492,33403,24414,17220,11420,7133,3598,"1,344",353,188
48,2020,강서구,계,585901,17688,22220,21262,23550,34309,53505,...,43904,44379,32417,23479,15525,9801,4999,"2,031",493,239
51,2020,구로구,계,432488,13947,16162,15166,15787,24139,33477,...,36830,33960,24947,18906,13135,7951,3553,"1,210",317,179
54,2020,금천구,계,247835,6470,7310,6957,8123,14724,23499,...,23713,20573,14079,10539,7655,4446,2061,693,191,178
57,2020,영등포구,계,407367,13798,13930,11971,13142,22614,38449,...,33666,29284,20735,15922,11715,7677,3732,"1,252",368,287
60,2020,동작구,계,401572,11143,13778,13211,15036,30100,40304,...,29838,28598,21314,17112,12711,8126,3794,"1,435",382,316
63,2020,관악구,계,509803,10314,12801,12927,16178,40485,71836,...,35677,34181,26323,21260,16031,9313,3864,"1,409",352,323
66,2020,서초구,계,429025,13239,20913,23247,22318,25343,30404,...,28729,27136,20838,16353,11114,6470,3329,"1,412",420,233
69,2020,강남구,계,544055,13675,23210,29194,30089,33765,41597,...,35919,33112,26516,20630,13589,7845,3979,"1,733",507,297
72,2020,송파구,계,673926,22147,28933,29160,30075,40527,54500,...,50486,48584,36021,24753,15743,9176,4970,"1,986",535,299
75,2020,강동구,계,463998,15408,19549,19381,19703,26857,35248,...,36536,36774,26769,18646,12027,6925,3531,"1,486",379,256

In [30]:
dfa['popu_합계'] = dfa['계']
dfa['popu_u20'] = dfa['0~4세'] + dfa['5~9세'] + dfa['10~14세'] + dfa['15~19세']
dfa['popu_2030'] = dfa['20~24세'] + dfa['25~29세'] + dfa['30~34세'] + dfa['35~39세']
dfa['popu_4050'] = dfa['40~44세'] + dfa['45~49세'] + dfa['50~54세'] + dfa['55~59세']

<ipython-input-30-a0b40e796818>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['popu_합계'] = dfa['계']
<ipython-input-30-a0b40e796818>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['popu_u20'] = dfa['0~4세'] + dfa['5~9세'] + dfa['10~14세'] + dfa['15~19세']
<ipython-input-30-a0b40e796818>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['popu_2030'] = dfa['20~24세'] + dfa['25~29세'] + dfa['30~34세'] + dfa['35~39세']
<ipython-input-30-a0b40e796818>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['popu_4050'] = dfa['40~44세'] + dfa['45~49세'] + dfa['50~54세'] + dfa['55~59세']

In [32]:
dfa['popu_o60'] = dfa['계'] - dfa['popu_u20'] - dfa['popu_2030'] - dfa['popu_4050']

<ipython-input-32-827e73a79a05>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['popu_o60'] = dfa['계'] - dfa['popu_u20'] - dfa['popu_2030'] - dfa['popu_4050']

In [34]:
dfa.drop(columns = ['계', '0~4세', '5~9세', '10~14세', '15~19세', '20~24세',
       '25~29세', '30~34세', '35~39세', '40~44세', '45~49세', '50~54세', '55~59세',
       '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85~89세', '90~94세',
       '95~99세', '100세 이상'], inplace = True)

C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [48]:
dfa.drop(columns = ['구분'], inplace = True)

C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [51]:
dfa.columns = ['date', 'sgg_nm', 'popu_합계', 'popu_u20', 'popu_2030', 'popu_4050', 'popu_o60']

In [52]:
dfa

    date sgg_nm  popu_합계  popu_u20  popu_2030  popu_4050  popu_o60
3   2020    종로구   158996     19517      49389      49803     40287
6   2020     중구   134635     14661      43617      41431     34926
9   2020    용산구   244645     31504      77841      77721     57579
12  2020    성동구   300505     40876      98023      94110     67496
15  2020    광진구   360109     46962     126154     110915     76078
18  2020   동대문구   357014     45449     117051     106037     88477
21  2020    중랑구   399562     50380     116644     128999    103539
24  2020    성북구   447056     66931     133917     140724    105484
27  2020    강북구   311569     38014      83593     100434     89528
30  2020    도봉구   327361     44555      85573     106216     91017
33  2020    노원구   527032     86770     140542     174915    124805
36  2020    은평구   484043     68799     137442     155417    122385
39  2020   서대문구   322952     44814     102566      98740     76832
42  2020    마포구   381858     54091     132749     117413     77605
45  2020    양천구   457781     82716     118961     157031     99073
48  2020    강서구   585901     84720     188455     179363    133363
51  2020    구로구   432488     61062     126095     141173    104158
54  2020    금천구   247835     28860      76651      81909     60415
57  2020   영등포구   407367     52841     135357     128197     90972
60  2020    동작구   401572     53168     134146     120470     93788
63  2020    관악구   509803     52220     202127     142400    113056
66  2020    서초구   429025     79717     120067     141936     87305
69  2020    강남구   544055     96168     158744     180935    108208
72  2020    송파구   673926    110315     207220     214324    142067
75  2020    강동구   463998     74041     135154     148010    106793

In [43]:
dff

,기간,행정구역별,구분,계,0~4세,5~9세,10~14세,15~19세,20~24세,25~29세,...,80~84세,85~89세,90~94세,95~99세,100세 이상,popu_합계,popu_u20,popu_2030,popu_4050,popu_o60
2,2020,합계,등록외국인,242623,6812,6123,3965,6640,36106,28352,...,402,197,81,31,21,242623,23540,112561,86885,19637
5,2020,종로구,등록외국인,9612,117,149,109,602,3247,1319,...,12,6,2,0,0,9612,977,6030,2113,492
8,2020,중구,등록외국인,9395,259,272,196,325,1856,1235,...,22,12,3,2,0,9395,1052,4924,2718,701
11,2020,용산구,등록외국인,14605,599,783,583,434,927,1520,...,26,7,4,4,2,14605,2399,6287,4953,966
14,2020,성동구,등록외국인,6949,136,115,63,298,1778,1066,...,7,5,2,2,3,6949,612,4075,1842,420
17,2020,광진구,등록외국인,13427,368,315,192,584,3149,1832,...,13,7,1,1,1,13427,1459,7231,3892,845
20,2020,동대문구,등록외국인,14177,203,151,95,565,5874,2757,...,17,10,4,0,0,14177,1014,10545,2145,473
23,2020,중랑구,등록외국인,4860,195,144,100,118,492,671,...,2,4,0,0,0,4860,557,2408,1588,307
26,2020,성북구,등록외국인,9903,180,141,92,551,3544,1903,...,12,7,0,1,1,9903,964,7102,1504,333
29,2020,강북구,등록외국인,3514,91,70,34,78,557,506,...,5,3,3,1,2,3514,273,1892,1074,275
32,2020,도봉구,등록외국인,2104,60,30,26,37,269,335,...,4,1,0,0,0,2104,153,1168,661,122
35,2020,노원구,등록외국인,3995,80,49,26,198,1148,671,...,3,1,1,0,1,3995,353,2620,847,175
38,2020,은평구,등록외국인,4208,122,88,71,138,305,492,...,17,8,3,0,0,4208,419,1882,1515,392
41,2020,서대문구,등록외국인,10779,110,157,177,573,3362,2042,...,42,23,4,3,1,10779,1017,7101,1886,775
44,2020,마포구,등록외국인,9968,157,177,137,349,2354,1918,...,20,8,6,2,2,9968,820,6359,2163,626
47,2020,양천구,등록외국인,3530,90,82,70,50,200,343,...,6,4,3,1,1,3530,292,1367,1543,328
50,2020,강서구,등록외국인,5716,207,141,60,58,248,575,...,13,9,2,0,0,5716,466,2402,2279,569
53,2020,구로구,등록외국인,28080,1078,832,480,284,788,1413,...,44,17,7,4,0,28080,2674,7533,14640,3233
56,2020,금천구,등록외국인,16102,695,537,272,139,359,737,...,15,13,2,3,1,16102,1643,4043,8714,1702
59,2020,영등포구,등록외국인,27887,1010,882,527,308,694,1293,...,49,21,16,6,0,27887,2727,7036,14828,3296
62,2020,동작구,등록외국인,10352,201,156,100,326,2497,1362,...,18,7,3,0,3,10352,783,5505,3215,849
65,2020,관악구,등록외국인,14743,416,327,196,309,1265,1921,...,21,15,7,1,0,14743,1248,6211,5864,1420
68,2020,서초구,등록외국인,3899,114,187,144,92,199,457,...,9,3,3,0,1,3899,537,1752,1384,226
71,2020,강남구,등록외국인,4824,54,65,56,93,483,939,...,9,2,2,0,1,4824,268,2966,1319,271
74,2020,송파구,등록외국인,5966,163,173,99,68,290,618,...,11,3,2,0,0,5966,503,2511,2459,493
77,2020,강동구,등록외국인,4028,107,100,60,63,221,427,...,5,1,1,0,1,4028,330,1611,1739,348

In [41]:
dff['popu_합계'] = dff['계']
dff['popu_u20'] = dff['0~4세'] + dff['5~9세'] + dff['10~14세'] + dff['15~19세']
dff['popu_2030'] = dff['20~24세'] + dff['25~29세'] + dff['30~34세'] + dff['35~39세']
dff['popu_4050'] = dff['40~44세'] + dff['45~49세'] + dff['50~54세'] + dff['55~59세']

<ipython-input-41-5fb90d7497d9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['popu_합계'] = dff['계']
<ipython-input-41-5fb90d7497d9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['popu_u20'] = dff['0~4세'] + dff['5~9세'] + dff['10~14세'] + dff['15~19세']
<ipython-input-41-5fb90d7497d9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['popu_2030'] = dff['20~24세'] + dff['25~29세'] + dff['30~34세'] + dff['35~39세']
<ipython-input-41-5fb90d7497d9>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['popu_4050'] = dff['40~44세'] + dff['45~49세'] + dff['50~54세'] + dff['55~59세']

In [42]:
dff['popu_o60'] = dff['계'] - dff['popu_u20'] - dff['popu_2030'] - dff['popu_4050']

<ipython-input-42-b3297b17b830>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['popu_o60'] = dff['계'] - dff['popu_u20'] - dff['popu_2030'] - dff['popu_4050']

In [44]:
dff.drop(columns = ['계', '0~4세', '5~9세', '10~14세', '15~19세', '20~24세',
       '25~29세', '30~34세', '35~39세', '40~44세', '45~49세', '50~54세', '55~59세',
       '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85~89세', '90~94세',
       '95~99세', '100세 이상'], inplace = True)

C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [46]:
dff.drop(columns = ['구분'], inplace = True)

C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [53]:
dff.columns = ['date', 'sgg_nm', 'for_합계', 'for_u20', 'for_2030', 'for_4050', 'for_o60']

In [56]:
dff = dff[1:]

In [58]:
dfn = pd.merge(left = dfa, right = dff, how = 'left', on = ['date', 'sgg_nm'])
dfn

,date,sgg_nm,popu_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_합계,for_u20,for_2030,for_4050,for_o60
0,2020,종로구,158996,19517,49389,49803,40287,9612,977,6030,2113,492
1,2020,중구,134635,14661,43617,41431,34926,9395,1052,4924,2718,701
2,2020,용산구,244645,31504,77841,77721,57579,14605,2399,6287,4953,966
3,2020,성동구,300505,40876,98023,94110,67496,6949,612,4075,1842,420
4,2020,광진구,360109,46962,126154,110915,76078,13427,1459,7231,3892,845
5,2020,동대문구,357014,45449,117051,106037,88477,14177,1014,10545,2145,473
6,2020,중랑구,399562,50380,116644,128999,103539,4860,557,2408,1588,307
7,2020,성북구,447056,66931,133917,140724,105484,9903,964,7102,1504,333
8,2020,강북구,311569,38014,83593,100434,89528,3514,273,1892,1074,275
9,2020,도봉구,327361,44555,85573,106216,91017,2104,153,1168,661,122
10,2020,노원구,527032,86770,140542,174915,124805,3995,353,2620,847,175
11,2020,은평구,484043,68799,137442,155417,122385,4208,419,1882,1515,392
12,2020,서대문구,322952,44814,102566,98740,76832,10779,1017,7101,1886,775
13,2020,마포구,381858,54091,132749,117413,77605,9968,820,6359,2163,626
14,2020,양천구,457781,82716,118961,157031,99073,3530,292,1367,1543,328
15,2020,강서구,585901,84720,188455,179363,133363,5716,466,2402,2279,569
16,2020,구로구,432488,61062,126095,141173,104158,28080,2674,7533,14640,3233
17,2020,금천구,247835,28860,76651,81909,60415,16102,1643,4043,8714,1702
18,2020,영등포구,407367,52841,135357,128197,90972,27887,2727,7036,14828,3296
19,2020,동작구,401572,53168,134146,120470,93788,10352,783,5505,3215,849
20,2020,관악구,509803,52220,202127,142400,113056,14743,1248,6211,5864,1420
21,2020,서초구,429025,79717,120067,141936,87305,3899,537,1752,1384,226
22,2020,강남구,544055,96168,158744,180935,108208,4824,268,2966,1319,271
23,2020,송파구,673926,110315,207220,214324,142067,5966,503,2511,2459,493
24,2020,강동구,463998,74041,135154,148010,106793,4028,330,1611,1739,348

In [62]:
dfn = dfn[['date', 'sgg_nm', 'popu_합계', 'for_합계', 'popu_u20', 'popu_2030', 'popu_4050', 'popu_o60', 'for_u20', 'for_2030', 'for_4050', 'for_o60']]

In [63]:
dfn

,date,sgg_nm,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,2020,종로구,158996,9612,19517,49389,49803,40287,977,6030,2113,492
1,2020,중구,134635,9395,14661,43617,41431,34926,1052,4924,2718,701
2,2020,용산구,244645,14605,31504,77841,77721,57579,2399,6287,4953,966
3,2020,성동구,300505,6949,40876,98023,94110,67496,612,4075,1842,420
4,2020,광진구,360109,13427,46962,126154,110915,76078,1459,7231,3892,845
5,2020,동대문구,357014,14177,45449,117051,106037,88477,1014,10545,2145,473
6,2020,중랑구,399562,4860,50380,116644,128999,103539,557,2408,1588,307
7,2020,성북구,447056,9903,66931,133917,140724,105484,964,7102,1504,333
8,2020,강북구,311569,3514,38014,83593,100434,89528,273,1892,1074,275
9,2020,도봉구,327361,2104,44555,85573,106216,91017,153,1168,661,122
10,2020,노원구,527032,3995,86770,140542,174915,124805,353,2620,847,175
11,2020,은평구,484043,4208,68799,137442,155417,122385,419,1882,1515,392
12,2020,서대문구,322952,10779,44814,102566,98740,76832,1017,7101,1886,775
13,2020,마포구,381858,9968,54091,132749,117413,77605,820,6359,2163,626
14,2020,양천구,457781,3530,82716,118961,157031,99073,292,1367,1543,328
15,2020,강서구,585901,5716,84720,188455,179363,133363,466,2402,2279,569
16,2020,구로구,432488,28080,61062,126095,141173,104158,2674,7533,14640,3233
17,2020,금천구,247835,16102,28860,76651,81909,60415,1643,4043,8714,1702
18,2020,영등포구,407367,27887,52841,135357,128197,90972,2727,7036,14828,3296
19,2020,동작구,401572,10352,53168,134146,120470,93788,783,5505,3215,849
20,2020,관악구,509803,14743,52220,202127,142400,113056,1248,6211,5864,1420
21,2020,서초구,429025,3899,79717,120067,141936,87305,537,1752,1384,226
22,2020,강남구,544055,4824,96168,158744,180935,108208,268,2966,1319,271
23,2020,송파구,673926,5966,110315,207220,214324,142067,503,2511,2459,493
24,2020,강동구,463998,4028,74041,135154,148010,106793,330,1611,1739,348

In [64]:
df_b = pd.read_csv('base_df.csv')

In [66]:
df_b['sgg_nm'] = df_b['jur_stn'].apply(lambda x : sgg_nm_transfer[x])
df_b

      jur_stn       year    sgg_nm
0     서울중부경찰서   2016(이전)        중구
1     서울종로경찰서   2016(이전)       종로구
2    서울남대문경찰서   2016(이전)        중구
3    서울서대문경찰서   2016(이전)      서대문구
4     서울혜화경찰서   2016(이전)       종로구
..        ...        ...       ...
364   창원서부경찰서  2020(하반기)    창원시의창구
365   마산중부경찰서  2020(하반기)  창원시마산합포구
366   마산동부경찰서  2020(하반기)  창원시마산회원구
367     진주경찰서  2020(하반기)       진주시
368     진해경찰서  2020(하반기)    창원시진해구

[369 rows x 3 columns]

In [67]:
df_b['date'] = df_b['year'].apply(lambda x : int(x[:4]))
df_b

      jur_stn       year    sgg_nm  date
0     서울중부경찰서   2016(이전)        중구  2016
1     서울종로경찰서   2016(이전)       종로구  2016
2    서울남대문경찰서   2016(이전)        중구  2016
3    서울서대문경찰서   2016(이전)      서대문구  2016
4     서울혜화경찰서   2016(이전)       종로구  2016
..        ...        ...       ...   ...
364   창원서부경찰서  2020(하반기)    창원시의창구  2020
365   마산중부경찰서  2020(하반기)  창원시마산합포구  2020
366   마산동부경찰서  2020(하반기)  창원시마산회원구  2020
367     진주경찰서  2020(하반기)       진주시  2020
368     진해경찰서  2020(하반기)    창원시진해구  2020

[369 rows x 4 columns]

In [69]:
dfnn = pd.merge(df_b, dfn, on =['sgg_nm', 'date'])

In [70]:
dfnn

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2020(상반기),중구,2020,134635,9395,14661,43617,41431,34926,1052,4924,2718,701
1,서울남대문경찰서,2020(상반기),중구,2020,134635,9395,14661,43617,41431,34926,1052,4924,2718,701
2,서울중부경찰서,2020(하반기),중구,2020,134635,9395,14661,43617,41431,34926,1052,4924,2718,701
3,서울남대문경찰서,2020(하반기),중구,2020,134635,9395,14661,43617,41431,34926,1052,4924,2718,701
4,서울종로경찰서,2020(상반기),종로구,2020,158996,9612,19517,49389,49803,40287,977,6030,2113,492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,서울송파경찰서,2020(하반기),송파구,2020,673926,5966,110315,207220,214324,142067,503,2511,2459,493
58,서울노원경찰서,2020(상반기),노원구,2020,527032,3995,86770,140542,174915,124805,353,2620,847,175
59,서울노원경찰서,2020(하반기),노원구,2020,527032,3995,86770,140542,174915,124805,353,2620,847,175
60,서울도봉경찰서,2020(상반기),도봉구,2020,327361,2104,44555,85573,106216,91017,153,1168,661,122
61,서울도봉경찰서,2020(하반기),도봉구,2020,327361,2104,44555,85573,106216,91017,153,1168,661,122

In [73]:
dfnn.iloc[dfnn[dfnn['sgg_nm'].isin(['중구', '강남구', '종로구', '성북구', '서초구', '은평구'])].index, 4:] = dfnn.iloc[dfnn[dfnn['sgg_nm'].isin(['중구', '강남구', '종로구', '성북구', '서초구', '은평구'])].index, 4:] / 2

In [74]:
dfnn

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2020(상반기),중구,2020,67317.5,4697.5,7330.5,21808.5,20715.5,17463.0,526.0,2462.0,1359.0,350.5
1,서울남대문경찰서,2020(상반기),중구,2020,67317.5,4697.5,7330.5,21808.5,20715.5,17463.0,526.0,2462.0,1359.0,350.5
2,서울중부경찰서,2020(하반기),중구,2020,67317.5,4697.5,7330.5,21808.5,20715.5,17463.0,526.0,2462.0,1359.0,350.5
3,서울남대문경찰서,2020(하반기),중구,2020,67317.5,4697.5,7330.5,21808.5,20715.5,17463.0,526.0,2462.0,1359.0,350.5
4,서울종로경찰서,2020(상반기),종로구,2020,79498.0,4806.0,9758.5,24694.5,24901.5,20143.5,488.5,3015.0,1056.5,246.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,서울송파경찰서,2020(하반기),송파구,2020,673926.0,5966.0,110315.0,207220.0,214324.0,142067.0,503.0,2511.0,2459.0,493.0
58,서울노원경찰서,2020(상반기),노원구,2020,527032.0,3995.0,86770.0,140542.0,174915.0,124805.0,353.0,2620.0,847.0,175.0
59,서울노원경찰서,2020(하반기),노원구,2020,527032.0,3995.0,86770.0,140542.0,174915.0,124805.0,353.0,2620.0,847.0,175.0
60,서울도봉경찰서,2020(상반기),도봉구,2020,327361.0,2104.0,44555.0,85573.0,106216.0,91017.0,153.0,1168.0,661.0,122.0
61,서울도봉경찰서,2020(하반기),도봉구,2020,327361.0,2104.0,44555.0,85573.0,106216.0,91017.0,153.0,1168.0,661.0,122.0

In [75]:
df1 = pd.read_csv('14번.연령별인구_total.csv')

In [81]:
dfbbb = pd.read_csv('base_df.csv')
dfbbb

      jur_stn       year
0     서울중부경찰서   2016(이전)
1     서울종로경찰서   2016(이전)
2    서울남대문경찰서   2016(이전)
3    서울서대문경찰서   2016(이전)
4     서울혜화경찰서   2016(이전)
..        ...        ...
364   창원서부경찰서  2020(하반기)
365   마산중부경찰서  2020(하반기)
366   마산동부경찰서  2020(하반기)
367     진주경찰서  2020(하반기)
368     진해경찰서  2020(하반기)

[369 rows x 2 columns]

In [82]:
pd.concat([df1[:-82], dfnn]).drop(columns = ['sgg_nm', 'date'])

,jur_stn,year,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,서울종로경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울남대문경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울서대문경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울혜화경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
57,서울송파경찰서,2020(하반기),673926.0,5966.0,110315.0,207220.0,214324.0,142067.0,503.0,2511.0,2459.0,493.0
58,서울노원경찰서,2020(상반기),527032.0,3995.0,86770.0,140542.0,174915.0,124805.0,353.0,2620.0,847.0,175.0
59,서울노원경찰서,2020(하반기),527032.0,3995.0,86770.0,140542.0,174915.0,124805.0,353.0,2620.0,847.0,175.0
60,서울도봉경찰서,2020(상반기),327361.0,2104.0,44555.0,85573.0,106216.0,91017.0,153.0,1168.0,661.0,122.0
61,서울도봉경찰서,2020(하반기),327361.0,2104.0,44555.0,85573.0,106216.0,91017.0,153.0,1168.0,661.0,122.0

In [85]:
pd.merge(left = dfbbb, right = pd.concat([df1[:-82], dfnn]).drop(columns = ['sgg_nm', 'date']), how = 'left', on = ['jur_stn', 'year']).to_csv('서울까지.csv', index = False)

In [86]:
df_fffff = pd.read_csv('서울까지.csv')

In [87]:
df_fffff

,jur_stn,year,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,서울종로경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울남대문경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울서대문경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울혜화경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
364,창원서부경찰서,2020(하반기),262241.0,3605.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,마산중부경찰서,2020(하반기),175504.0,2158.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,마산동부경찰서,2020(하반기),193101.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
367,진주경찰서,2020(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
368,진해경찰서,2020(하반기),192759.0,3363.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df1 = gpd.read_file('./data/1.5개시도_경찰서_관할경계.geojson')
df3 = pd.read_csv('./data/14.5개시도_성연령별_총인구분포.csv')
df_b = pd.read_csv('base_df.csv')

C:\Anaconda3\lib\site-packages\geopandas\array.py:85: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  aout[:] = out

In [114]:
df3['age'].unique()

array(['합계', '0~4세', '0세', '1세', '2세', '3세', '4세', '5~9세', '5세', '6세',
       '7세', '8세', '9세', '10~14세', '10세', '11세', '12세', '13세', '14세',
       '15~19세', '15세', '16세', '17세', '18세', '19세', '20~24세', '20세',
       '21세', '22세', '23세', '24세', '25~29세', '25세', '26세', '27세', '28세',
       '29세', '30~34세', '30세', '31세', '32세', '33세', '34세', '35~39세',
       '35세', '36세', '37세', '38세', '39세', '40~44세', '40세', '41세', '42세',
       '43세', '44세', '45~49세', '45세', '46세', '47세', '48세', '49세',
       '50~54세', '50세', '51세', '52세', '53세', '54세', '55~59세', '55세',
       '56세', '57세', '58세', '59세', '60~64세', '60세', '61세', '62세', '63세',
       '64세', '65~69세', '65세', '66세', '67세', '68세', '69세', '70~74세',
       '70세', '71세', '72세', '73세', '74세', '75~79세', '75세', '76세', '77세',
       '78세', '79세', '80~84세', '80세', '81세', '82세', '83세', '84세', '85세이상',
       '85~89세', '85세', '86세', '87세', '88세', '89세', '90~94세', '90세',
       '91세', '92세', '93세', '94세', '95~99세', '95세', '96세', '97세', '98세',
       '99세', '100세이상', '15세미만', '15~64세', '65세이상', '평균연령', '중위연령'],
      dtype=object)

In [115]:
# 중복되지 않는 연령 구간별 합계 가져오기
df3_n = df3[df3['age'].isin(['합계', '15세미만','15~19세', '20~24세', '25~29세', '30~34세','35~39세', '40~44세', '45~49세'
                             , '50~54세', '55~59세', '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85세이상'])]
df3_n

,sido,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate
0,서울특별시,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3
19,서울특별시,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8
25,서울특별시,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8
31,서울특별시,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2
37,서울특별시,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1
...,...,...,...,...,...,...,...,...,...,...,...,...
13781,서울특별시,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3
13787,서울특별시,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0
13793,서울특별시,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0
13799,서울특별시,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7
13819,서울특별시,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0

In [116]:
# 데이터 타입 변경
df3_n = df3_n.astype({'popu_num' : 'int'})
df3_n = df3_n.astype({'local_num' : 'int'})
df3_n = df3_n.astype({'popu_male_num' : 'int'})
df3_n = df3_n.astype({'popu_female_num' : 'int'})
df3_n = df3_n.astype({'local_male_num' : 'int'})
df3_n = df3_n.astype({'local_female_num' : 'int'})

In [117]:
# 내국인 인구로 외국인 인구 구하기
df3_n['foreigner'] = df3_n['popu_num'] - df3_n['local_num']
df3_n['for_male_num'] = df3_n['popu_male_num'] - df3_n['local_male_num']
df3_n['for_female_num'] = df3_n['popu_female_num'] - df3_n['local_female_num']

In [118]:
# 외국인 성비
df3_n['for_sx_rate'] = round(df3_n['for_male_num'] / df3_n['for_female_num'] * 100, 1)

In [119]:
#불필요한 컬럼 제거
df3_n.drop(columns = ['sido'], inplace = True)

In [120]:
df3_n

,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,foreigner,for_male_num,for_female_num,for_sx_rate
0,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3,10979,4913,6066,81.0
19,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8,840,307,533,57.6
25,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8,2757,940,1817,51.7
31,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2,1404,637,767,83.1
37,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1,1096,561,535,104.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13781,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3,98,50,48,104.2
13787,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0,61,25,36,69.4
13793,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0,33,9,24,37.5
13799,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7,20,5,15,33.3
13819,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0,470,270,200,135.0

In [13]:
# 경찰서별 담당 행정구역
sgg_nm_transfer = {
    '마산동부경찰서' : '창원시마산회원구'  ,
    '마산중부경찰서' : '창원시마산합포구'  ,
    '서울강남경찰서' : '강남구'  , 
    '서울강동경찰서' : '강동구' , 
    '서울강북경찰서' :'강북구'  , 
    '서울강서경찰서' :  '강서구',
    '서울관악경찰서' : '관악구' ,
      '서울광진경찰서' : '광진구', 
     '서울구로경찰서' : '구로구' , 
     '서울금천경찰서' : '금천구' , 
    '서울남대문경찰서' : '중구' , 
    '서울노원경찰서' : '노원구' ,
    '서울도봉경찰서' : '도봉구'  , 
    '서울동대문경찰서' : '동대문구'  , 
    '서울동작경찰서' : '동작구'  , 
    '서울마포경찰서' : '마포구' , 
    '서울방배경찰서' : '서초구', 
    '서울서대문경찰서' : '서대문구' ,
    '서울서부경찰서' : '은평구' , 
    '서울서초경찰서' : '서초구' , 
    '서울성동경찰서' : '성동구' , 
    '서울성북경찰서' :'성북구' , 
    '서울송파경찰서' :'송파구' , 
    '서울수서경찰서' : '강남구' ,
     '서울양천경찰서': '양천구'  , 
    '서울영등포경찰서' : '영등포구' , 
    '서울용산경찰서': '용산구'  , 
    '서울은평경찰서' : '은평구' , 
    '서울종로경찰서': '종로구', 
    '서울종암경찰서' : '성북구'  ,
     '서울중랑경찰서' : '중랑구'   , 
    '서울중부경찰서' : '중구'  , 
    '서울혜화경찰서': '종로구'  , 
    '세종경찰서' : '세종시'  , 
    '수원남부경찰서': '수원시영통구'  ,
   '수원서부경찰서' : '수원시팔달구'  ,  
    '수원중부경찰서' :'수원시장안구'   , 
    '진주경찰서' : '진주시'  ,
    '진해경찰서' : '창원시진해구'  , 
    '창원서부경찰서' : '창원시의창구' , 
    '창원중부경찰서': '창원시성산구'
    
}

In [152]:
# 기본 데이터프레임에 담당 행정구역 추가
df_b['sgg_nm'] = df_b['jur_stn'].apply(lambda x : sgg_nm_transfer[x])
df_b

     jur_stn       year  sgg_nm
33   수원서부경찰서   2016(이전)  수원시권선구
74   수원서부경찰서  2017(상반기)  수원시권선구
115  수원서부경찰서  2017(하반기)  수원시권선구
156  수원서부경찰서  2018(상반기)  수원시권선구
197  수원서부경찰서  2018(하반기)  수원시권선구
238  수원서부경찰서  2019(상반기)  수원시권선구
280  수원서부경찰서  2019(하반기)  수원시권선구
320  수원서부경찰서  2020(상반기)  수원시권선구
361  수원서부경찰서  2020(하반기)  수원시권선구

In [153]:
# 연도 추가
df_b['date'] = df_b['year'].apply(lambda x : int(x[:4]))
df_b

     jur_stn       year  sgg_nm  date
33   수원서부경찰서   2016(이전)  수원시권선구  2016
74   수원서부경찰서  2017(상반기)  수원시권선구  2017
115  수원서부경찰서  2017(하반기)  수원시권선구  2017
156  수원서부경찰서  2018(상반기)  수원시권선구  2018
197  수원서부경찰서  2018(하반기)  수원시권선구  2018
238  수원서부경찰서  2019(상반기)  수원시권선구  2019
280  수원서부경찰서  2019(하반기)  수원시권선구  2019
320  수원서부경찰서  2020(상반기)  수원시권선구  2020
361  수원서부경찰서  2020(하반기)  수원시권선구  2020

In [124]:
df3_n

,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,foreigner,for_male_num,for_female_num,for_sx_rate
0,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3,10979,4913,6066,81.0
19,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8,840,307,533,57.6
25,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8,2757,940,1817,51.7
31,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2,1404,637,767,83.1
37,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1,1096,561,535,104.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13781,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3,98,50,48,104.2
13787,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0,61,25,36,69.4
13793,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0,33,9,24,37.5
13799,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7,20,5,15,33.3
13819,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0,470,270,200,135.0

In [125]:
df3_nn

,jur_stn,year,sgg_nm,date,age,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,foreigner,for_male_num,for_female_num,for_sx_rate
0,서울중부경찰서,2017(상반기),중구,2017,합계,127896,62195,65701,94.7,117631,57391,60240,95.3,10265,4804,5461,88.0
1,서울중부경찰서,2017(상반기),중구,2017,15세미만,11035,5604,5431,103.2,10565,5334,5231,102.0,470,270,200,135.0
2,서울중부경찰서,2017(상반기),중구,2017,15~64세,97649,48332,49317,98.0,88374,44025,44349,99.3,9275,4307,4968,86.7
3,서울중부경찰서,2017(상반기),중구,2017,65세이상,19212,8259,10953,75.4,18692,8032,10660,75.3,520,227,293,77.5
4,서울남대문경찰서,2017(상반기),중구,2017,합계,127896,62195,65701,94.7,117631,57391,60240,95.3,10265,4804,5461,88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,진해경찰서,2019(상반기),창원시진해구,2019,65세이상,25405,11045,14360,76.9,25268,10982,14286,76.9,137,63,74,85.1
980,진해경찰서,2019(하반기),창원시진해구,2019,합계,190885,98087,92798,105.7,185968,94938,91030,104.3,4917,3149,1768,178.1
981,진해경찰서,2019(하반기),창원시진해구,2019,15세미만,31522,16267,15255,106.6,31357,16185,15172,106.7,165,82,83,98.8
982,진해경찰서,2019(하반기),창원시진해구,2019,15~64세,133958,70775,63183,112.0,129343,67771,61572,110.1,4615,3004,1611,186.5
983,진해경찰서,2019(하반기),창원시진해구,2019,65세이상,25405,11045,14360,76.9,25268,10982,14286,76.9,137,63,74,85.1

In [126]:
df3_nn = pd.merge(df_b, df3_n, on =['sgg_nm', 'date'])

In [127]:
df_bb = df3_nn[['jur_stn', 'year', 'sgg_nm', 'date']]
df_bb

      jur_stn       year  sgg_nm  date
0     서울중부경찰서  2017(상반기)      중구  2017
1     서울중부경찰서  2017(상반기)      중구  2017
2     서울중부경찰서  2017(상반기)      중구  2017
3     서울중부경찰서  2017(상반기)      중구  2017
4     서울중부경찰서  2017(상반기)      중구  2017
...       ...        ...     ...   ...
4177    진해경찰서  2019(하반기)  창원시진해구  2019
4178    진해경찰서  2019(하반기)  창원시진해구  2019
4179    진해경찰서  2019(하반기)  창원시진해구  2019
4180    진해경찰서  2019(하반기)  창원시진해구  2019
4181    진해경찰서  2019(하반기)  창원시진해구  2019

[4182 rows x 4 columns]

In [128]:
for i in df3_nn['age'].unique() :
    df_bb['popu_'+i] = 0

<ipython-input-128-7c141b5acd54>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bb['popu_'+i] = 0

In [129]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4178,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4179,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4180,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4181,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [130]:
for i in range(len(df3_nn)) :
    bb_nm = df3_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df3_nn['jur_stn'].iloc[i])&(df_bb['date']==df3_nn['date'].iloc[i])]
    bb[bb_nm] = df3_nn['popu_num'].iloc[i]
    df_bb['popu_' + bb_nm].iloc[bb.index] = df3_nn['popu_num'].iloc[i]
df4 = df_bb
df4

<ipython-input-130-8440aac26757>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df3_nn['popu_num'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522

In [131]:
for i in df3_nn['age'].unique() :
    df_bb['for_'+i] = 0

In [132]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0

In [133]:
for i in range(len(df3_nn)) :
    bb_nm = df3_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df3_nn['jur_stn'].iloc[i])&(df_bb['date']==df3_nn['date'].iloc[i])]
    bb[bb_nm] = df3_nn['foreigner'].iloc[i]
    df_bb['for_' + bb_nm].iloc[bb.index] = df3_nn['foreigner'].iloc[i]
df4 = df_bb
df4

<ipython-input-133-066708432911>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df3_nn['foreigner'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [134]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [135]:
df4.drop_duplicates(inplace=True)
df4

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,800,768,638,512,226,81,54,27,22,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,233,213,168,103,51,15,11,7,2,54
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,412,362,260,140,71,22,13,7,4,135
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,412,362,260,140,71,22,13,7,4,135
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [136]:
df4['year'].value_counts()

2017(상반기)    41
2017(하반기)    41
2018(상반기)    41
2018(하반기)    41
2019(상반기)    41
2019(하반기)    41
Name: year, dtype: int64

In [137]:
df4.columns

Index(['jur_stn', 'year', 'sgg_nm', 'date', 'popu_합계', 'popu_15~19세',
       'popu_20~24세', 'popu_25~29세', 'popu_30~34세', 'popu_35~39세',
       'popu_40~44세', 'popu_45~49세', 'popu_50~54세', 'popu_55~59세',
       'popu_60~64세', 'popu_65~69세', 'popu_70~74세', 'popu_75~79세',
       'popu_80~84세', 'popu_85세이상', 'popu_15세미만', 'for_합계', 'for_15~19세',
       'for_20~24세', 'for_25~29세', 'for_30~34세', 'for_35~39세', 'for_40~44세',
       'for_45~49세', 'for_50~54세', 'for_55~59세', 'for_60~64세', 'for_65~69세',
       'for_70~74세', 'for_75~79세', 'for_80~84세', 'for_85세이상', 'for_15세미만'],
      dtype='object')

In [85]:
df4['jur_stn'].unique()

array(['서울중부경찰서', '서울남대문경찰서', '서울종로경찰서', '서울혜화경찰서', '서울서대문경찰서', '서울용산경찰서',
       '서울성북경찰서', '서울종암경찰서', '서울동대문경찰서', '서울마포경찰서', '서울영등포경찰서', '서울성동경찰서',
       '서울동작경찰서', '서울광진경찰서', '서울서부경찰서', '서울은평경찰서', '서울강북경찰서', '서울금천경찰서',
       '서울중랑경찰서', '서울강남경찰서', '서울수서경찰서', '서울관악경찰서', '서울강서경찰서', '서울강동경찰서',
       '서울구로경찰서', '서울서초경찰서', '서울방배경찰서', '서울양천경찰서', '서울송파경찰서', '서울노원경찰서',
       '서울도봉경찰서', '수원중부경찰서', '수원남부경찰서', '수원서부경찰서', '세종경찰서', '창원중부경찰서',
       '창원서부경찰서', '마산중부경찰서', '마산동부경찰서', '진주경찰서', '진해경찰서'], dtype=object)

In [86]:
len(df4['jur_stn'].unique())

41

In [87]:
df4.to_csv('alskd.csv')

In [139]:
df4['popu_u20'] = df4['popu_15세미만'] + df4['popu_15~19세']
df4['popu_2030'] = df4['popu_20~24세'] + df4['popu_25~29세'] + df4['popu_30~34세'] + df4['popu_35~39세']
df4['popu_4050'] = df4['popu_40~44세'] + df4['popu_45~49세'] + df4['popu_50~54세'] + df4['popu_55~59세']

In [140]:
df4['popu_o60'] = df4['popu_합계'] - df4['popu_u20'] - df4['popu_2030'] - df4['popu_4050']

In [141]:
df4

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만,popu_u20,popu_2030,popu_4050,popu_o60
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,226,81,54,27,22,276,23931,50443,49187,33716
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,51,15,11,7,2,54,32856,46112,65987,47491
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,71,22,13,7,4,135,66710,94780,112947,79729
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,71,22,13,7,4,135,66710,94780,112947,79729
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,78,27,16,9,7,165,40507,49459,62622,38297
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,78,27,16,9,7,165,40507,49459,62622,38297

In [142]:
df4['for_u20'] = df4['for_15세미만'] + df4['for_15~19세']
df4['for_2030'] = df4['for_20~24세'] + df4['for_25~29세'] + df4['for_30~34세'] + df4['for_35~39세']
df4['for_4050'] = df4['for_40~44세'] + df4['for_45~49세'] + df4['for_50~54세'] + df4['for_55~59세']

In [143]:
df4['for_o60'] = df4['for_합계'] - df4['for_u20'] - df4['for_2030'] - df4['for_4050']

In [144]:
df4

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_85세이상,for_15세미만,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,22,276,23931,50443,49187,33716,1116,6063,2878,922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,2,54,32856,46112,65987,47491,124,1718,840,189
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,4,135,66710,94780,112947,79729,424,4908,1563,257
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,4,135,66710,94780,112947,79729,424,4908,1563,257
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7,165,40507,49459,62622,38297,212,2834,1570,301
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7,165,40507,49459,62622,38297,212,2834,1570,301

In [146]:
# 필요없는 컬럼 제거
df4_n = df4.drop(['popu_15~19세',
       'popu_20~24세', 'popu_25~29세', 'popu_30~34세', 'popu_35~39세',
       'popu_40~44세', 'popu_45~49세', 'popu_50~54세', 'popu_55~59세',
       'popu_60~64세', 'popu_65~69세', 'popu_70~74세', 'popu_75~79세',
       'popu_80~84세', 'popu_85세이상', 'popu_15세미만','for_15~19세',
       'for_20~24세', 'for_25~29세', 'for_30~34세', 'for_35~39세', 'for_40~44세',
       'for_45~49세', 'for_50~54세', 'for_55~59세', 'for_60~64세', 'for_65~69세',
       'for_70~74세', 'for_75~79세', 'for_80~84세', 'for_85세이상', 'for_15세미만'], axis = 1)

In [147]:
df4_n

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2017(상반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
17,서울남대문경찰서,2017(상반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
34,서울중부경찰서,2017(하반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
51,서울남대문경찰서,2017(하반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10979,23931,50443,49187,33716,1116,6063,2878,922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,2871,32856,46112,65987,47491,124,1718,840,189
4114,진주경찰서,2019(상반기),진주시,2019,354166,7152,66710,94780,112947,79729,424,4908,1563,257
4131,진주경찰서,2019(하반기),진주시,2019,354166,7152,66710,94780,112947,79729,424,4908,1563,257
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,4917,40507,49459,62622,38297,212,2834,1570,301
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,4917,40507,49459,62622,38297,212,2834,1570,301

In [148]:
df4_n.to_csv('중간저장.csv')

In [149]:
# 행정구역을 여러 경찰서가 담당하는 경우 그 수만큼 인구를 나눠줌
'''
df4_n.iloc[0, 4:] = df4_n.iloc[0, 4:] / 2
df4_n.iloc[1, 4:] = df4_n.iloc[1, 4:] / 2
df4_n.iloc[2, 4:] = df4_n.iloc[2, 4:] / 2
df4_n.iloc[3, 4:] = df4_n.iloc[3, 4:] / 2 # 중구

df4_n.iloc[4, 4:] = df4_n.iloc[4, 4:] / 2
df4_n.iloc[5, 4:] = df4_n.iloc[5, 4:] / 2
df4_n.iloc[6, 4:] = df4_n.iloc[6, 4:] / 2
df4_n.iloc[7, 4:] = df4_n.iloc[7, 4:] / 2 # 종로구

df4_n.iloc[12, 4:] = df4_n.iloc[12, 4:] / 2
df4_n.iloc[13, 4:] = df4_n.iloc[13, 4:] / 2
df4_n.iloc[14, 4:] = df4_n.iloc[14, 4:] / 2
df4_n.iloc[15, 4:] = df4_n.iloc[15, 4:] / 2 # 성북구

df4_n.iloc[28, 4:] = df4_n.iloc[28, 4:] / 2
df4_n.iloc[29, 4:] = df4_n.iloc[29, 4:] / 2
df4_n.iloc[30, 4:] = df4_n.iloc[30, 4:] / 2
df4_n.iloc[31, 4:] = df4_n.iloc[31, 4:] / 2 # 은평구

df4_n.iloc[50, 4:] = df4_n.iloc[50, 4:] / 2
df4_n.iloc[51, 4:] = df4_n.iloc[51, 4:] / 2
df4_n.iloc[52, 4:] = df4_n.iloc[52, 4:] / 2
df4_n.iloc[53, 4:] = df4_n.iloc[53, 4:] / 2 # 서초구

df4_n.iloc[38, 4:] = df4_n.iloc[38, 4:] / 2
df4_n.iloc[39, 4:] = df4_n.iloc[39, 4:] / 2
df4_n.iloc[40, 4:] = df4_n.iloc[40, 4:] / 2
df4_n.iloc[41, 4:] = df4_n.iloc[41, 4:] / 2 # 강남구
'''

In [153]:
# 행정구역을 여러 경찰서가 담당하는 경우 그 수만큼 인구를 나눠줌
'''
for i in range(1, 3):
    df4_n.iloc[0 + 82 * i, 4:] = df4_n.iloc[0 + 82 * i, 4:] / 2
    df4_n.iloc[1 + 82 * i, 4:] = df4_n.iloc[1 + 82 * i, 4:] / 2
    df4_n.iloc[2 + 82 * i, 4:] = df4_n.iloc[2 + 82 * i, 4:] / 2
    df4_n.iloc[3 + 82 * i, 4:] = df4_n.iloc[3 + 82 * i, 4:] / 2 # 중구

    df4_n.iloc[4 + 82 * i, 4:] = df4_n.iloc[4 + 82 * i, 4:] / 2
    df4_n.iloc[5 + 82 * i, 4:] = df4_n.iloc[5 + 82 * i, 4:] / 2
    df4_n.iloc[6 + 82 * i, 4:] = df4_n.iloc[6 + 82 * i, 4:] / 2
    df4_n.iloc[7 + 82 * i, 4:] = df4_n.iloc[7 + 82 * i, 4:] / 2 # 종로구

    df4_n.iloc[12 + 82 * i, 4:] = df4_n.iloc[12 + 82 * i, 4:] / 2
    df4_n.iloc[13 + 82 * i, 4:] = df4_n.iloc[13 + 82 * i, 4:] / 2
    df4_n.iloc[14 + 82 * i, 4:] = df4_n.iloc[14 + 82 * i, 4:] / 2
    df4_n.iloc[15 + 82 * i, 4:] = df4_n.iloc[15 + 82 * i, 4:] / 2 # 성북구

    df4_n.iloc[28 + 82 * i, 4:] = df4_n.iloc[28 + 82 * i, 4:] / 2
    df4_n.iloc[29 + 82 * i, 4:] = df4_n.iloc[29 + 82 * i, 4:] / 2
    df4_n.iloc[30 + 82 * i, 4:] = df4_n.iloc[30 + 82 * i, 4:] / 2
    df4_n.iloc[31 + 82 * i, 4:] = df4_n.iloc[31 + 82 * i, 4:] / 2 # 은평구

    df4_n.iloc[50 + 82 * i, 4:] = df4_n.iloc[50 + 82 * i, 4:] / 2
    df4_n.iloc[51 + 82 * i, 4:] = df4_n.iloc[51 + 82 * i, 4:] / 2
    df4_n.iloc[52 + 82 * i, 4:] = df4_n.iloc[52 + 82 * i, 4:] / 2
    df4_n.iloc[53 + 82 * i, 4:] = df4_n.iloc[53 + 82 * i, 4:] / 2 # 서초구

    df4_n.iloc[38 + 82 * i, 4:] = df4_n.iloc[38 + 82 * i, 4:] / 2
    df4_n.iloc[39 + 82 * i, 4:] = df4_n.iloc[39 + 82 * i, 4:] / 2
    df4_n.iloc[40 + 82 * i, 4:] = df4_n.iloc[40 + 82 * i, 4:] / 2
    df4_n.iloc[41 + 82 * i, 4:] = df4_n.iloc[41 + 82 * i, 4:] / 2 # 강남구
'''

In [154]:
df4_n

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2017(상반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
17,서울남대문경찰서,2017(상반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
34,서울중부경찰서,2017(하반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
51,서울남대문경찰서,2017(하반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
68,서울종로경찰서,2017(상반기),종로구,2017,78638.5,5489.5,11965.5,25221.5,24593.5,16858.0,558.0,3031.5,1439.0,461.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446.0,2871.0,32856.0,46112.0,65987.0,47491.0,124.0,1718.0,840.0,189.0
4114,진주경찰서,2019(상반기),진주시,2019,354166.0,7152.0,66710.0,94780.0,112947.0,79729.0,424.0,4908.0,1563.0,257.0
4131,진주경찰서,2019(하반기),진주시,2019,354166.0,7152.0,66710.0,94780.0,112947.0,79729.0,424.0,4908.0,1563.0,257.0
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885.0,4917.0,40507.0,49459.0,62622.0,38297.0,212.0,2834.0,1570.0,301.0
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885.0,4917.0,40507.0,49459.0,62622.0,38297.0,212.0,2834.0,1570.0,301.0

In [157]:
df4_n.to_csv('중간저장3.csv', index = False)

In [159]:
df4_n.sort_values(by = ['jur_stn', 'year'], axis = 0)

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
1292,마산동부경찰서,2017(상반기),창원시마산회원구,2017,202864.0,2770.0,37306.0,51907.0,69877.0,43774.0,79.0,1650.0,865.0,176.0
1309,마산동부경찰서,2017(하반기),창원시마산회원구,2017,202864.0,2770.0,37306.0,51907.0,69877.0,43774.0,79.0,1650.0,865.0,176.0
2686,마산동부경찰서,2018(상반기),창원시마산회원구,2018,197683.0,2770.0,35319.0,49122.0,67932.0,45310.0,82.0,1699.0,815.0,174.0
2703,마산동부경찰서,2018(하반기),창원시마산회원구,2018,197683.0,2770.0,35319.0,49122.0,67932.0,45310.0,82.0,1699.0,815.0,174.0
4080,마산동부경찰서,2019(상반기),창원시마산회원구,2019,192446.0,2871.0,32856.0,46112.0,65987.0,47491.0,124.0,1718.0,840.0,189.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,창원중부경찰서,2017(하반기),창원시성산구,2017,226726.0,4937.0,46726.0,68373.0,86416.0,25211.0,111.0,3420.0,1231.0,175.0
2584,창원중부경찰서,2018(상반기),창원시성산구,2018,225894.0,5101.0,44290.0,68541.0,85492.0,27571.0,141.0,3515.0,1267.0,178.0
2601,창원중부경찰서,2018(하반기),창원시성산구,2018,225894.0,5101.0,44290.0,68541.0,85492.0,27571.0,141.0,3515.0,1267.0,178.0
3978,창원중부경찰서,2019(상반기),창원시성산구,2019,219951.0,5191.0,41200.0,65279.0,83360.0,30112.0,184.0,3394.0,1409.0,204.0
3995,창원중부경찰서,2019(하반기),창원시성산구,2019,219951.0,5191.0,41200.0,65279.0,83360.0,30112.0,184.0,3394.0,1409.0,204.0

In [162]:
df4_n.drop(columns = ['sgg_nm', 'date'], inplace = True)

In [164]:
df4_n.to_csv('14번.연령별인구_processed.csv')

In [63]:
df_b = pd.read_csv('base_df.csv')

In [64]:
df_b

      jur_stn       year
0     서울중부경찰서   2016(이전)
1     서울종로경찰서   2016(이전)
2    서울남대문경찰서   2016(이전)
3    서울서대문경찰서   2016(이전)
4     서울혜화경찰서   2016(이전)
..        ...        ...
364   창원서부경찰서  2020(하반기)
365   마산중부경찰서  2020(하반기)
366   마산동부경찰서  2020(하반기)
367     진주경찰서  2020(하반기)
368     진해경찰서  2020(하반기)

[369 rows x 2 columns]

In [65]:
df_b = pd.merge(left = df_b, right = df4_n, how = 'left', on = ['jur_stn', 'year'])

NameError: name 'df4_n' is not defined

In [171]:
df_b.to_csv('14번.연령별인구_total.csv', index = False)

권선구 인구 따로 구해서 더하기

In [235]:
# 수원서부경찰서는 권선구 + 팔달구, 권선구의 인구를 더해줘야 함
df_g = pd.read_csv('./data/14.5개시도_성연령별_총인구분포.csv')

In [236]:
df_gn = df_g[df_g['age'].isin(['합계', '15세미만','15~19세', '20~24세', '25~29세', '30~34세','35~39세', '40~44세', '45~49세'
                             , '50~54세', '55~59세', '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85세이상'])]

In [237]:
df_gn = df_gn[df_gn['sgg_nm'].isin(['수원시권선구'])]
df_gn

,sido,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate
3328,경기도,수원시권선구,합계,2017,364650,183913,180737,101.8,351909,177344,174565,101.6
3347,경기도,수원시권선구,15~19세,2017,19213,10052,9161,109.7,19113,10010,9103,110.0
3353,경기도,수원시권선구,20~24세,2017,24979,12942,12037,107.5,24483,12667,11816,107.2
3359,경기도,수원시권선구,25~29세,2017,27816,14321,13495,106.1,26405,13637,12768,106.8
3365,경기도,수원시권선구,30~34세,2017,30051,15505,14546,106.6,28203,14503,13700,105.9
3371,경기도,수원시권선구,35~39세,2017,34545,18038,16507,109.3,33313,17336,15977,108.5
3377,경기도,수원시권선구,40~44세,2017,30201,15727,14474,108.7,29134,15130,14004,108.0
3383,경기도,수원시권선구,45~49세,2017,32730,16114,16616,97.0,31336,15398,15938,96.6
3389,경기도,수원시권선구,50~54세,2017,30950,15393,15557,98.9,29457,14647,14810,98.9
3395,경기도,수원시권선구,55~59세,2017,29462,14888,14574,102.2,28261,14281,13980,102.2
3401,경기도,수원시권선구,60~64세,2017,19160,9526,9634,98.9,18072,8954,9118,98.2
3407,경기도,수원시권선구,65~69세,2017,11868,5825,6043,96.4,11405,5613,5792,96.9
3413,경기도,수원시권선구,70~74세,2017,8420,3948,4472,88.3,8286,3896,4390,88.7
3419,경기도,수원시권선구,75~79세,2017,6503,2666,3837,69.5,6427,2649,3778,70.1
3425,경기도,수원시권선구,80~84세,2017,3913,1359,2554,53.2,3863,1348,2515,53.6
3431,경기도,수원시권선구,85세이상,2017,2549,650,1899,34.2,2539,647,1892,34.2
3451,경기도,수원시권선구,15세미만,2017,52290,26959,25331,106.4,51612,26628,24984,106.6
7936,경기도,수원시권선구,합계,2018,379834,191697,188137,101.9,365133,184151,180982,101.8
7955,경기도,수원시권선구,15~19세,2018,18517,9671,8846,109.3,18400,9626,8774,109.7
7961,경기도,수원시권선구,20~24세,2018,25035,12917,12118,106.6,24524,12646,11878,106.5
7967,경기도,수원시권선구,25~29세,2018,29788,15445,14343,107.7,28391,14762,13629,108.3
7973,경기도,수원시권선구,30~34세,2018,30300,15751,14549,108.3,28201,14625,13576,107.7
7979,경기도,수원시권선구,35~39세,2018,36390,19020,17370,109.5,34860,18169,16691,108.9
7985,경기도,수원시권선구,40~44세,2018,30522,16034,14488,110.7,29330,15338,13992,109.6
7991,경기도,수원시권선구,45~49세,2018,33234,16599,16635,99.8,31732,15826,15906,99.5
7997,경기도,수원시권선구,50~54세,2018,32620,15985,16635,96.1,30965,15130,15835,95.5
8003,경기도,수원시권선구,55~59세,2018,31748,15924,15824,100.6,30107,15139,14968,101.1
8009,경기도,수원시권선구,60~64세,2018,21630,10798,10832,99.7,20333,10140,10193,99.5
8015,경기도,수원시권선구,65~69세,2018,12977,6344,6633,95.6,12399,6062,6337,95.7
8021,경기도,수원시권선구,70~74세,2018,9247,4347,4900,88.7,9078,4286,4792,89.4
8027,경기도,수원시권선구,75~79세,2018,6920,2874,4046,71.0,6830,2851,3979,71.7
8033,경기도,수원시권선구,80~84세,2018,4322,1559,2763,56.4,4261,1541,2720,56.7
8039,경기도,수원시권선구,85세이상,2018,2806,727,2079,35.0,2791,724,2067,35.0
8059,경기도,수원시권선구,15세미만,2018,53778,27702,26076,106.2,52931,27286,25645,106.4
12544,경기도,수원시권선구,합계,2019,374770,189282,185488,102.0,359431,181368,178063,101.9
12563,경기도,수원시권선구,15~19세,2019,17440,9115,8325,109.5,17303,9063,8240,110.0
12569,경기도,수원시권선구,20~24세,2019,23795,12275,11520,106.6,23292,12021,11271,106.7
12575,경기도,수원시권선구,25~29세,2019,29601,15528,14073,110.3,28340,14901,13439,110.9
12581,경기도,수원시권선구,30~34세,2019,28720,14953,13767,108.6,26611,13847,12764,108.5
12587,경기도,수원시권선구,35~39세,2019,34518,18103,16415,110.3,32882,17173,15709,109.3
12593,경기도,수원시권선구,40~44세,2019,30214,15874,14340,110.7,28881,15105,13776,109.6
12599,경기도,수원시권선구,45~49세,2019,32260,16407,15853,103.5,30766,15590,15176,102.7
12605,경기도,수원시권선구,50~54세,2019,33144,15999,17145,93.3,31449,15132,16317,92.7
12611,경기도,수원시권선구,55~59세,2019,31800,15957,15843,100.7,29969,15066,14903,101.1
12617,경기도,수원시권선구,60~64세,2019,23604,11767,11837,99.4,22253,11103,11150,99.6
12623,경기도,수원시권선구,65~69세,2019,13908,6812,7096,96.0,13241,6460,6781,95.3
12629,경기도,수원시권선구,70~74세,2019,9779,4653,5126,90.8,9584,4574,5010,91.3
12635,경기도,수원시권선구,75~79세,2019,7063,3002,4061,73.9,6960,2970,3990,74.4
12641,경기도,수원시권선구,80~84세,2019,4642,1688,2954,57.1,4582,1671,2911,57.4
12647,경기도,수원시권선구,85세이상,2019,3116,858,2258,38.0,3094,852,2242,38.0
12667,경기도,수원시권선구,15세미만,2019,51166,26291,24875,105.7,50224,25840,24384,106.0

In [238]:
df_gn.dtypes

sido                 object
sgg_nm               object
age                  object
date                  int64
popu_num             object
popu_male_num        object
popu_female_num      object
popu_sx_rate        float64
local_num            object
local_male_num       object
local_female_num     object
local_sx_rate       float64
dtype: object

In [239]:
df_gn = df_gn.astype({'popu_num' : 'int'})
df_gn = df_gn.astype({'local_num' : 'int'})
df_gn = df_gn.astype({'popu_male_num' : 'int'})
df_gn = df_gn.astype({'popu_female_num' : 'int'})
df_gn = df_gn.astype({'local_male_num' : 'int'})
df_gn = df_gn.astype({'local_female_num' : 'int'})

In [240]:
df_gn['for'] = df_gn['popu_num'] - df_gn['local_num']
df_gn['for_male_num'] = df_gn['popu_male_num'] - df_gn['local_male_num']
df_gn['for_female_num'] = df_gn['popu_female_num'] - df_gn['local_female_num']

In [241]:
df_gn

,sido,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,for,for_male_num,for_female_num
3328,경기도,수원시권선구,합계,2017,364650,183913,180737,101.8,351909,177344,174565,101.6,12741,6569,6172
3347,경기도,수원시권선구,15~19세,2017,19213,10052,9161,109.7,19113,10010,9103,110.0,100,42,58
3353,경기도,수원시권선구,20~24세,2017,24979,12942,12037,107.5,24483,12667,11816,107.2,496,275,221
3359,경기도,수원시권선구,25~29세,2017,27816,14321,13495,106.1,26405,13637,12768,106.8,1411,684,727
3365,경기도,수원시권선구,30~34세,2017,30051,15505,14546,106.6,28203,14503,13700,105.9,1848,1002,846
3371,경기도,수원시권선구,35~39세,2017,34545,18038,16507,109.3,33313,17336,15977,108.5,1232,702,530
3377,경기도,수원시권선구,40~44세,2017,30201,15727,14474,108.7,29134,15130,14004,108.0,1067,597,470
3383,경기도,수원시권선구,45~49세,2017,32730,16114,16616,97.0,31336,15398,15938,96.6,1394,716,678
3389,경기도,수원시권선구,50~54세,2017,30950,15393,15557,98.9,29457,14647,14810,98.9,1493,746,747
3395,경기도,수원시권선구,55~59세,2017,29462,14888,14574,102.2,28261,14281,13980,102.2,1201,607,594
3401,경기도,수원시권선구,60~64세,2017,19160,9526,9634,98.9,18072,8954,9118,98.2,1088,572,516
3407,경기도,수원시권선구,65~69세,2017,11868,5825,6043,96.4,11405,5613,5792,96.9,463,212,251
3413,경기도,수원시권선구,70~74세,2017,8420,3948,4472,88.3,8286,3896,4390,88.7,134,52,82
3419,경기도,수원시권선구,75~79세,2017,6503,2666,3837,69.5,6427,2649,3778,70.1,76,17,59
3425,경기도,수원시권선구,80~84세,2017,3913,1359,2554,53.2,3863,1348,2515,53.6,50,11,39
3431,경기도,수원시권선구,85세이상,2017,2549,650,1899,34.2,2539,647,1892,34.2,10,3,7
3451,경기도,수원시권선구,15세미만,2017,52290,26959,25331,106.4,51612,26628,24984,106.6,678,331,347
7936,경기도,수원시권선구,합계,2018,379834,191697,188137,101.9,365133,184151,180982,101.8,14701,7546,7155
7955,경기도,수원시권선구,15~19세,2018,18517,9671,8846,109.3,18400,9626,8774,109.7,117,45,72
7961,경기도,수원시권선구,20~24세,2018,25035,12917,12118,106.6,24524,12646,11878,106.5,511,271,240
7967,경기도,수원시권선구,25~29세,2018,29788,15445,14343,107.7,28391,14762,13629,108.3,1397,683,714
7973,경기도,수원시권선구,30~34세,2018,30300,15751,14549,108.3,28201,14625,13576,107.7,2099,1126,973
7979,경기도,수원시권선구,35~39세,2018,36390,19020,17370,109.5,34860,18169,16691,108.9,1530,851,679
7985,경기도,수원시권선구,40~44세,2018,30522,16034,14488,110.7,29330,15338,13992,109.6,1192,696,496
7991,경기도,수원시권선구,45~49세,2018,33234,16599,16635,99.8,31732,15826,15906,99.5,1502,773,729
7997,경기도,수원시권선구,50~54세,2018,32620,15985,16635,96.1,30965,15130,15835,95.5,1655,855,800
8003,경기도,수원시권선구,55~59세,2018,31748,15924,15824,100.6,30107,15139,14968,101.1,1641,785,856
8009,경기도,수원시권선구,60~64세,2018,21630,10798,10832,99.7,20333,10140,10193,99.5,1297,658,639
8015,경기도,수원시권선구,65~69세,2018,12977,6344,6633,95.6,12399,6062,6337,95.7,578,282,296
8021,경기도,수원시권선구,70~74세,2018,9247,4347,4900,88.7,9078,4286,4792,89.4,169,61,108
8027,경기도,수원시권선구,75~79세,2018,6920,2874,4046,71.0,6830,2851,3979,71.7,90,23,67
8033,경기도,수원시권선구,80~84세,2018,4322,1559,2763,56.4,4261,1541,2720,56.7,61,18,43
8039,경기도,수원시권선구,85세이상,2018,2806,727,2079,35.0,2791,724,2067,35.0,15,3,12
8059,경기도,수원시권선구,15세미만,2018,53778,27702,26076,106.2,52931,27286,25645,106.4,847,416,431
12544,경기도,수원시권선구,합계,2019,374770,189282,185488,102.0,359431,181368,178063,101.9,15339,7914,7425
12563,경기도,수원시권선구,15~19세,2019,17440,9115,8325,109.5,17303,9063,8240,110.0,137,52,85
12569,경기도,수원시권선구,20~24세,2019,23795,12275,11520,106.6,23292,12021,11271,106.7,503,254,249
12575,경기도,수원시권선구,25~29세,2019,29601,15528,14073,110.3,28340,14901,13439,110.9,1261,627,634
12581,경기도,수원시권선구,30~34세,2019,28720,14953,13767,108.6,26611,13847,12764,108.5,2109,1106,1003
12587,경기도,수원시권선구,35~39세,2019,34518,18103,16415,110.3,32882,17173,15709,109.3,1636,930,706
12593,경기도,수원시권선구,40~44세,2019,30214,15874,14340,110.7,28881,15105,13776,109.6,1333,769,564
12599,경기도,수원시권선구,45~49세,2019,32260,16407,15853,103.5,30766,15590,15176,102.7,1494,817,677
12605,경기도,수원시권선구,50~54세,2019,33144,15999,17145,93.3,31449,15132,16317,92.7,1695,867,828
12611,경기도,수원시권선구,55~59세,2019,31800,15957,15843,100.7,29969,15066,14903,101.1,1831,891,940
12617,경기도,수원시권선구,60~64세,2019,23604,11767,11837,99.4,22253,11103,11150,99.6,1351,664,687
12623,경기도,수원시권선구,65~69세,2019,13908,6812,7096,96.0,13241,6460,6781,95.3,667,352,315
12629,경기도,수원시권선구,70~74세,2019,9779,4653,5126,90.8,9584,4574,5010,91.3,195,79,116
12635,경기도,수원시권선구,75~79세,2019,7063,3002,4061,73.9,6960,2970,3990,74.4,103,32,71
12641,경기도,수원시권선구,80~84세,2019,4642,1688,2954,57.1,4582,1671,2911,57.4,60,17,43
12647,경기도,수원시권선구,85세이상,2019,3116,858,2258,38.0,3094,852,2242,38.0,22,6,16
12667,경기도,수원시권선구,15세미만,2019,51166,26291,24875,105.7,50224,25840,24384,106.0,942,451,491

In [242]:
df_b = pd.read_csv('base_df.csv')

In [243]:
# 경찰서별 담당 행정구역
sgg_nm_transfer = {
   '수원서부경찰서' : '수원시권선구'  
    
}

In [244]:
df_b = df_b[df_b['jur_stn'].isin(['수원서부경찰서'])]

In [245]:
df_b['sgg_nm'] = df_b['jur_stn'].apply(lambda x : sgg_nm_transfer[x])
df_b

     jur_stn       year  sgg_nm
33   수원서부경찰서   2016(이전)  수원시권선구
74   수원서부경찰서  2017(상반기)  수원시권선구
115  수원서부경찰서  2017(하반기)  수원시권선구
156  수원서부경찰서  2018(상반기)  수원시권선구
197  수원서부경찰서  2018(하반기)  수원시권선구
238  수원서부경찰서  2019(상반기)  수원시권선구
280  수원서부경찰서  2019(하반기)  수원시권선구
320  수원서부경찰서  2020(상반기)  수원시권선구
361  수원서부경찰서  2020(하반기)  수원시권선구

In [246]:
df_b['date'] = df_b['year'].apply(lambda x : int(x[:4]))
df_b

     jur_stn       year  sgg_nm  date
33   수원서부경찰서   2016(이전)  수원시권선구  2016
74   수원서부경찰서  2017(상반기)  수원시권선구  2017
115  수원서부경찰서  2017(하반기)  수원시권선구  2017
156  수원서부경찰서  2018(상반기)  수원시권선구  2018
197  수원서부경찰서  2018(하반기)  수원시권선구  2018
238  수원서부경찰서  2019(상반기)  수원시권선구  2019
280  수원서부경찰서  2019(하반기)  수원시권선구  2019
320  수원서부경찰서  2020(상반기)  수원시권선구  2020
361  수원서부경찰서  2020(하반기)  수원시권선구  2020

In [247]:
df_gn = pd.merge(df_b, df_gn, on =['sgg_nm', 'date'])

In [248]:
df_bn = df_gn[['jur_stn', 'year', 'sgg_nm', 'date']]
df_bn

     jur_stn       year  sgg_nm  date
0    수원서부경찰서  2017(상반기)  수원시권선구  2017
1    수원서부경찰서  2017(상반기)  수원시권선구  2017
2    수원서부경찰서  2017(상반기)  수원시권선구  2017
3    수원서부경찰서  2017(상반기)  수원시권선구  2017
4    수원서부경찰서  2017(상반기)  수원시권선구  2017
..       ...        ...     ...   ...
97   수원서부경찰서  2019(하반기)  수원시권선구  2019
98   수원서부경찰서  2019(하반기)  수원시권선구  2019
99   수원서부경찰서  2019(하반기)  수원시권선구  2019
100  수원서부경찰서  2019(하반기)  수원시권선구  2019
101  수원서부경찰서  2019(하반기)  수원시권선구  2019

[102 rows x 4 columns]

In [249]:
df_gn.drop(columns = ['sido'], inplace = True)
df_gn

,jur_stn,year,sgg_nm,date,age,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,for,for_male_num,for_female_num
0,수원서부경찰서,2017(상반기),수원시권선구,2017,합계,364650,183913,180737,101.8,351909,177344,174565,101.6,12741,6569,6172
1,수원서부경찰서,2017(상반기),수원시권선구,2017,15~19세,19213,10052,9161,109.7,19113,10010,9103,110.0,100,42,58
2,수원서부경찰서,2017(상반기),수원시권선구,2017,20~24세,24979,12942,12037,107.5,24483,12667,11816,107.2,496,275,221
3,수원서부경찰서,2017(상반기),수원시권선구,2017,25~29세,27816,14321,13495,106.1,26405,13637,12768,106.8,1411,684,727
4,수원서부경찰서,2017(상반기),수원시권선구,2017,30~34세,30051,15505,14546,106.6,28203,14503,13700,105.9,1848,1002,846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,수원서부경찰서,2019(하반기),수원시권선구,2019,70~74세,9779,4653,5126,90.8,9584,4574,5010,91.3,195,79,116
98,수원서부경찰서,2019(하반기),수원시권선구,2019,75~79세,7063,3002,4061,73.9,6960,2970,3990,74.4,103,32,71
99,수원서부경찰서,2019(하반기),수원시권선구,2019,80~84세,4642,1688,2954,57.1,4582,1671,2911,57.4,60,17,43
100,수원서부경찰서,2019(하반기),수원시권선구,2019,85세이상,3116,858,2258,38.0,3094,852,2242,38.0,22,6,16
101,수원서부경찰서,2019(하반기),수원시권선구,2019,15세미만,51166,26291,24875,105.7,50224,25840,24384,106.0,942,451,491

In [250]:
# 외국인 성비
df_gn['for_sx_rate'] = round(df_gn['for_male_num'] / df_gn['for_female_num'] * 100, 1)

In [251]:
for i in df_gn['age'].unique() :
    df_bn['popu_'+i] = 0

<ipython-input-251-b3dd76aec1ad>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bn['popu_'+i] = 0

In [252]:
df_bn

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,수원서부경찰서,2017(상반기),수원시권선구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,수원서부경찰서,2017(상반기),수원시권선구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,수원서부경찰서,2017(상반기),수원시권선구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,수원서부경찰서,2017(상반기),수원시권선구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,수원서부경찰서,2017(상반기),수원시권선구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,수원서부경찰서,2019(하반기),수원시권선구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,수원서부경찰서,2019(하반기),수원시권선구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,수원서부경찰서,2019(하반기),수원시권선구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,수원서부경찰서,2019(하반기),수원시권선구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101,수원서부경찰서,2019(하반기),수원시권선구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [253]:
for i in range(len(df_gn)) :
    bb_nm = df_gn['age'].iloc[i]
    bb = df_bn[(df_bn['jur_stn']==df_gn['jur_stn'].iloc[i])&(df_bn['date']==df_gn['date'].iloc[i])]
    bb[bb_nm] = df_gn['popu_num'].iloc[i]
    df_bn['popu_' + bb_nm].iloc[bb.index] = df_gn['popu_num'].iloc[i]
dfg = df_bn
dfg

<ipython-input-253-b1507bf7c499>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df_gn['popu_num'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,32730,30950,29462,19160,11868,8420,6503,3913,2549,52290
1,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,32730,30950,29462,19160,11868,8420,6503,3913,2549,52290
2,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,32730,30950,29462,19160,11868,8420,6503,3913,2549,52290
3,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,32730,30950,29462,19160,11868,8420,6503,3913,2549,52290
4,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,32730,30950,29462,19160,11868,8420,6503,3913,2549,52290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,32260,33144,31800,23604,13908,9779,7063,4642,3116,51166
98,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,32260,33144,31800,23604,13908,9779,7063,4642,3116,51166
99,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,32260,33144,31800,23604,13908,9779,7063,4642,3116,51166
100,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,32260,33144,31800,23604,13908,9779,7063,4642,3116,51166
101,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,32260,33144,31800,23604,13908,9779,7063,4642,3116,51166

In [255]:
for i in df_gn['age'].unique() :
    df_bn['for_'+i] = 0

In [257]:
for i in range(len(df_gn)) :
    bb_nm = df_gn['age'].iloc[i]
    bb = df_bn[(df_bn['jur_stn']==df_gn['jur_stn'].iloc[i])&(df_bn['date']==df_gn['date'].iloc[i])]
    bb[bb_nm] = df_gn['for'].iloc[i]
    df_bn['for_' + bb_nm].iloc[bb.index] = df_gn['for'].iloc[i]
dfg = df_bn
dfg

<ipython-input-257-8693f492d489>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df_gn['for'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,1394,1493,1201,1088,463,134,76,50,10,678
1,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,1394,1493,1201,1088,463,134,76,50,10,678
2,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,1394,1493,1201,1088,463,134,76,50,10,678
3,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,1394,1493,1201,1088,463,134,76,50,10,678
4,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,1394,1493,1201,1088,463,134,76,50,10,678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,1494,1695,1831,1351,667,195,103,60,22,942
98,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,1494,1695,1831,1351,667,195,103,60,22,942
99,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,1494,1695,1831,1351,667,195,103,60,22,942
100,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,1494,1695,1831,1351,667,195,103,60,22,942
101,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,1494,1695,1831,1351,667,195,103,60,22,942

In [258]:
dfg.drop_duplicates(inplace=True)
dfg

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,1394,1493,1201,1088,463,134,76,50,10,678
17,수원서부경찰서,2017(하반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,1394,1493,1201,1088,463,134,76,50,10,678
34,수원서부경찰서,2018(상반기),수원시권선구,2018,379834,18517,25035,29788,30300,36390,...,1502,1655,1641,1297,578,169,90,61,15,847
51,수원서부경찰서,2018(하반기),수원시권선구,2018,379834,18517,25035,29788,30300,36390,...,1502,1655,1641,1297,578,169,90,61,15,847
68,수원서부경찰서,2019(상반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,1494,1695,1831,1351,667,195,103,60,22,942
85,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,1494,1695,1831,1351,667,195,103,60,22,942

In [259]:
dfg['popu_u20'] = dfg['popu_15세미만'] + dfg['popu_15~19세']
dfg['popu_2030'] = dfg['popu_20~24세'] + dfg['popu_25~29세'] + dfg['popu_30~34세'] + dfg['popu_35~39세']
dfg['popu_4050'] = dfg['popu_40~44세'] + dfg['popu_45~49세'] + dfg['popu_50~54세'] + dfg['popu_55~59세']

In [260]:
dfg['popu_o60'] = dfg['popu_합계'] - dfg['popu_u20'] - dfg['popu_2030'] - dfg['popu_4050']

In [261]:
dfg['for_u20'] = dfg['for_15세미만'] + dfg['for_15~19세']
dfg['for_2030'] = dfg['for_20~24세'] + dfg['for_25~29세'] + dfg['for_30~34세'] + dfg['for_35~39세']
dfg['for_4050'] = dfg['for_40~44세'] + dfg['for_45~49세'] + dfg['for_50~54세'] + dfg['for_55~59세']

In [262]:
dfg['for_o60'] = dfg['for_합계'] - dfg['for_u20'] - dfg['for_2030'] - dfg['for_4050']

In [263]:
dfg

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_85세이상,for_15세미만,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,10,678,71503,117391,123343,52413,778,4987,5155,1821
17,수원서부경찰서,2017(하반기),수원시권선구,2017,364650,19213,24979,27816,30051,34545,...,10,678,71503,117391,123343,52413,778,4987,5155,1821
34,수원서부경찰서,2018(상반기),수원시권선구,2018,379834,18517,25035,29788,30300,36390,...,15,847,72295,121513,128124,57902,964,5537,5990,2210
51,수원서부경찰서,2018(하반기),수원시권선구,2018,379834,18517,25035,29788,30300,36390,...,15,847,72295,121513,128124,57902,964,5537,5990,2210
68,수원서부경찰서,2019(상반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,22,942,68606,116634,127418,62112,1079,5509,6353,2398
85,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,17440,23795,29601,28720,34518,...,22,942,68606,116634,127418,62112,1079,5509,6353,2398

In [264]:
dfg_n = dfg.drop(['popu_15~19세',
       'popu_20~24세', 'popu_25~29세', 'popu_30~34세', 'popu_35~39세',
       'popu_40~44세', 'popu_45~49세', 'popu_50~54세', 'popu_55~59세',
       'popu_60~64세', 'popu_65~69세', 'popu_70~74세', 'popu_75~79세',
       'popu_80~84세', 'popu_85세이상', 'popu_15세미만','for_15~19세',
       'for_20~24세', 'for_25~29세', 'for_30~34세', 'for_35~39세', 'for_40~44세',
       'for_45~49세', 'for_50~54세', 'for_55~59세', 'for_60~64세', 'for_65~69세',
       'for_70~74세', 'for_75~79세', 'for_80~84세', 'for_85세이상', 'for_15세미만'], axis = 1)

In [268]:
dfg_n

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,수원서부경찰서,2017(상반기),수원시권선구,2017,364650,12741,71503,117391,123343,52413,778,4987,5155,1821
17,수원서부경찰서,2017(하반기),수원시권선구,2017,364650,12741,71503,117391,123343,52413,778,4987,5155,1821
34,수원서부경찰서,2018(상반기),수원시권선구,2018,379834,14701,72295,121513,128124,57902,964,5537,5990,2210
51,수원서부경찰서,2018(하반기),수원시권선구,2018,379834,14701,72295,121513,128124,57902,964,5537,5990,2210
68,수원서부경찰서,2019(상반기),수원시권선구,2019,374770,15339,68606,116634,127418,62112,1079,5509,6353,2398
85,수원서부경찰서,2019(하반기),수원시권선구,2019,374770,15339,68606,116634,127418,62112,1079,5509,6353,2398

In [269]:
dfg_n.drop(columns = ['sgg_nm', 'date'], inplace = True)

In [270]:
dfg_n

,jur_stn,year,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,수원서부경찰서,2017(상반기),364650,12741,71503,117391,123343,52413,778,4987,5155,1821
17,수원서부경찰서,2017(하반기),364650,12741,71503,117391,123343,52413,778,4987,5155,1821
34,수원서부경찰서,2018(상반기),379834,14701,72295,121513,128124,57902,964,5537,5990,2210
51,수원서부경찰서,2018(하반기),379834,14701,72295,121513,128124,57902,964,5537,5990,2210
68,수원서부경찰서,2019(상반기),374770,15339,68606,116634,127418,62112,1079,5509,6353,2398
85,수원서부경찰서,2019(하반기),374770,15339,68606,116634,127418,62112,1079,5509,6353,2398

In [272]:
dfg_n.to_csv('권선구만.csv')

In [271]:
df_o = pd.read_csv('14번.연령별인구_total.csv')
df_o

,jur_stn,year,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,서울종로경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울남대문경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울서대문경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울혜화경찰서,2016(이전),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
364,창원서부경찰서,2020(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,마산중부경찰서,2020(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,마산동부경찰서,2020(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
367,진주경찰서,2020(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
368,진해경찰서,2020(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 성비 X

In [ ]:
df3_n = df3[df3['age'].isin(['합계', '15세미만', '15~64세', '65세이상'])]

In [107]:
for i in df3_nn['age'].unique() :
    df_bb['sx_rate_'+i] = 0

In [110]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,sx_rate_55~59세,sx_rate_60~64세,sx_rate_65~69세,sx_rate_70~74세,sx_rate_75~79세,sx_rate_80~84세,sx_rate_85세이상,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,103.2,98.0,75.4
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0.0,0.0,0.0
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0.0,0.0,0.0
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0.0,0.0,0.0
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,0,0,0,0,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0.0,0.0,0.0

In [ ]:
sgg2police = {
    #seoul
'강남구' : ['서울강남경찰서', '서울수서경찰서'],
'강동구' : '서울강동경찰서',
'강북구' : '서울강북경찰서',
'강서구' : '서울강서경찰서',
'관악구' : '서울관악경찰서',
'광진구' : '서울광진경찰서',
'구로구' : '서울구로경찰서',
'권선구' : '수원서부경찰서',
'금천구' : '서울금천경찰서',
'노원구' : '서울노원경찰서',
'도봉구' : '서울도봉경찰서',
'동대문구' : ['서울동대문경찰서', '서울혜화경찰서'],
'동작구' : '서울동작경찰서',
'서대문구' : '서울서대문경찰서',
'서초구' : ['서울서초경찰서', '서울방배경찰서'],
'성동구' : '서울성동경찰서',
'성북구' : ['서울성북경찰서', '서울종암경찰서'],
'마포구' : '서울마포경찰서',
'송파구' : '서울송파경찰서',
'양천구' : '서울양천경찰서',
'영등포구' : '서울영등포경찰서',
'용산구' : '서울용산경찰서',
'은평구' : ['서울은평경찰서', '서울서부경찰서'],
'종로구' : '서울종로경찰서',
'중구' : ['서울중부경찰서', '서울남대문경찰서'],
'중랑구' : '서울중랑경찰서',
    
    #changwon
'마산합포구' : '마산중부경찰서',
'마산회원구' : '마산동부경찰서',
'성산구' : '창원중부경찰서',
'의창구' : ['창원중부경찰서', '창원서부경찰서'],
'진해구' : '진해경찰서',
'창원시' : ['진해경찰서', '창원서부경찰서', '창원중부경찰서', '마산중부경찰서', '마산동부경찰서'],
'창원시 마산합포구' : '마산중부경찰서',
'창원시 마산회원구' : '마산동부경찰서',
'창원시 성산구' : '창원중부경찰서',
'창원시 의창구' : ['창원중부경찰서', '창원서부경찰서'],
'창원시 진해구' : '진해경찰서',
'창원시마산합포구' : '마산중부경찰서',
'창원시마산회원구' : '마산동부경찰서',
'창원시성산구' : '창원중부경찰서',
'창원시의창구' : ['창원중부경찰서', '창원서부경찰서'],
'창원시진해구' : '진해경찰서',
    
    #sejong
'세종시' : '세종경찰서',
'세종특별자치시' : '세종경찰서',
    
    #suwon
'수원시' : ['수원남부경찰서', '수원서부경찰서', '수원중부경찰서'],
'수원시 권선구' : '수원서부경찰서',
'수원시 영통구' : '수원남부경찰서',
'수원시 장안구' : '수원중부경찰서',
'수원시 팔달구' : '수원서부경찰서',
'수원시권선구' : '수원서부경찰서',
'수원시영통구' : '수원남부경찰서',
'수원시장안구' : '수원중부경찰서',
'수원시팔달구' : '수원서부경찰서',
'영통구' : '수원남부경찰서',
'장안구' : '수원중부경찰서',
'팔달구' : '수원서부경찰서',

    #jinju
'진주시' : '진주경찰서'
}