In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [121]:
accident = pd.read_csv('./11.5개시도_교통사고현황.csv')
accident.head()

       date    acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
0  2018년 1월  차대차 - 측면충돌      남     20대      남     50대    서울중부
1  2018년 1월  차대차 - 측면충돌      여     50대      남     70대    서울중부
2  2018년 1월  차대차 - 측면충돌      남     40대      남     50대    서울중부
3  2018년 1월    차대차 - 기타   기타불명     미분류      여     40대    서울중부
4  2018년 1월    차대차 - 기타      남     60대      남     50대    서울중부

In [3]:
pol = pd.read_csv('./12.경찰서별_지구대별 인원현황.csv')
pol.head()

  nat_pol_agency pol_office sec_center  num
0          서울경찰청    서울중부경찰서      을지지구대   42
1          서울경찰청    서울중부경찰서      광희지구대   47
2          서울경찰청    서울중부경찰서      약수지구대   42
3          서울경찰청    서울중부경찰서      신당파출소   26
4          서울경찰청    서울중부경찰서      장충파출소   26

In [4]:
yy = pd.read_csv('4.체감안전도_통계(2017~2019).csv')
yy.head()

,large_category,medium_category,tot_f_safety,dept_safety,crime_safety,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,2017 상반기(연령대),10대(만14세 이상),74.3,73.3,81.5,80.1,82.8,70.9,66.9,76.5
1,2017 상반기(연령대),20대,70.1,69.3,76.9,75.7,78.2,66.1,64.3,71.7
2,2017 상반기(연령대),30대,69.6,68.9,76.8,75.7,77.9,63.9,65.2,71.1
3,2017 상반기(연령대),40대,70.7,70.2,77.2,76.1,78.3,65.5,67.0,71.9
4,2017 상반기(연령대),50대,72.1,71.5,78.3,77.7,79.0,68.0,67.6,73.3

In [7]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140954 entries, 0 to 140953
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date      140954 non-null  object
 1   acc_case  140954 non-null  object
 2   ofn_sx    140954 non-null  object
 3   ofn_age   140954 non-null  object
 4   vic_sx    136527 non-null  object
 5   vic_age   140954 non-null  object
 6   jur_stn   140954 non-null  object
dtypes: object(7)
memory usage: 7.5+ MB

In [8]:
accident.describe()

             date     acc_case  ofn_sx ofn_age  vic_sx vic_age jur_stn
count      140954       140954  140954  140954  136527  140954  140954
unique         36           34       3      11       4      11      41
top     2019년 11월  차대차  - 측면충돌       남     50대       남     50대    서울송파
freq         4583        35023  111880   32946   99239   27849    8301

In [9]:
for i in accident.columns:
    print(accident[i].unique())

['2018년 1월' '2018년 2월' '2018년 3월' '2018년 4월' '2018년 5월' '2018년 6월'
 '2018년 7월' '2018년 8월' '2018년 9월' '2018년 10월' '2018년 11월' '2018년 12월'
 '2019년 1월' '2019년 2월' '2019년 3월' '2019년 4월' '2019년 5월' '2019년 6월'
 '2019년 7월' '2019년 8월' '2019년 9월' '2019년 10월' '2019년 11월' '2019년 12월'
 '2020년 1월' '2020년 2월' '2020년 3월' '2020년 4월' '2020년 5월' '2020년 6월'
 '2020년 7월' '2020년 8월' '2020년 9월' '2020년 10월' '2020년 11월' '2020년 12월']
['차대차 - 측면충돌' '차대차 - 기타' '차대차 - 추돌' '차대사람 - 횡단중' '차량단독 - 기타'
 '차대사람 - 길가장자리구역통행중' '차대사람 - 보도통행중' '차대사람 - 기타' '차대사람 - 차도통행중'
 '차량단독 - 공작물충돌' '차대차 - 정면충돌' '차대차 - 후진중충돌' '차량단독 - 전도전복 - 전도'
 '차량단독 - 주/정차차량 충돌' '차량단독 - 전도전복 - 전복' '차량단독 - 도로외이탈 - 추락'
 '차대사람  - 길가장자리구역통행중' '차대사람  - 횡단중' '차대차  - 추돌' '차대차  - 측면충돌' '차량단독  - 기타'
 '차량단독  - 전도전복 - 전도' '차대사람  - 차도통행중' '차대차  - 기타' '차대사람  - 기타'
 '차대사람  - 보도통행중' '차대차  - 후진중충돌' '차대차  - 정면충돌' '차량단독  - 공작물충돌'
 '차량단독  - 주/정차차량 충돌' '차량단독  - 전도전복 - 전복' '차량단독  - 도로외이탈 - 기타'
 '차량단독  - 도로외이탈 - 추락' '차량단독 - 도로외이탈 - 기타']
['남' '여' '기타불명']
['20대' '50대' '40대' '미분류' '60대' '30대' '70대' '10대' '80대' '10대 미만' '90대 이상']
['남' '여' nan '미분류' '기타불명']
['50대' '70대' '40대' '30대' '60대' '미분류' '20대' '80대' '10대' '90대 이상' '10대 미만']
['서울중부' '서울남대문' '서울종로' '서울혜화' '서울서대문' '서울서부' '서울용산' '서울성북' '서울강북' '서울동대문'
 '서울광진' '서울마포' '서울영등포' '서울금천' '서울성동' '서울동작' '서울중랑' '서울관악' '서울강남' '서울강서'
 '서울강동' '서울송파' '서울종암' '서울구로' '서울서초' '서울양천' '서울노원' '서울도봉' '서울은평' '서울방배'
 '서울수서' '세종' '수원남부' '수원서부' '수원중부' '진주' '마산동부' '마산중부' '창원서부' '창원중부' '진해경찰서']

In [ ]:
accident

In [17]:
accident.groupby(accident['acc_case']).count()

                     date  ofn_sx  ofn_age  vic_sx  vic_age  jur_stn
acc_case
차대사람  - 기타          10977   10977    10977   10977    10977    10977
차대사람  - 길가장자리구역통행중   1703    1703     1703    1703     1703     1703
차대사람  - 보도통행중        1718    1718     1718    1718     1718     1718
차대사람  - 차도통행중        2587    2587     2587    2587     2587     2587
차대사람  - 횡단중          9491    9491     9491    9491     9491     9491
차대사람 - 기타            2819    2819     2819    2819     2819     2819
차대사람 - 길가장자리구역통행중     330     330      330     330      330      330
차대사람 - 보도통행중          361     361      361     361      361      361
차대사람 - 차도통행중          952     952      952     952      952      952
차대사람 - 횡단중           2957    2957     2957    2957     2957     2957
차대차  - 기타           22571   22571    22571   22571    22571    22571
차대차  - 정면충돌          2717    2717     2717    2717     2717     2717
차대차  - 추돌           17423   17423    17423   17423    17423    17423
차대차  - 측면충돌         35023   35023    35023   35023    35023    35023
차대차  - 후진중충돌         1284    1284     1284    1284     1284     1284
차대차 - 기타             5993    5993     5993    5993     5993     5993
차대차 - 정면충돌            959     959      959     959      959      959
차대차 - 추돌             5242    5242     5242    5242     5242     5242
차대차 - 측면충돌          10857   10857    10857   10857    10857    10857
차대차 - 후진중충돌           412     412      412     412      412      412
차량단독  - 공작물충돌         694     694      694       0      694      694
차량단독  - 기타           2360    2360     2360       0     2360     2360
차량단독  - 도로외이탈 - 기타     10      10       10       0       10       10
차량단독  - 도로외이탈 - 추락     10      10       10       0       10       10
차량단독  - 전도전복 - 전도     306     306      306      94      306      306
차량단독  - 전도전복 - 전복      23      23       23      12       23       23
차량단독  - 주/정차차량 충돌       4       4        4       0        4        4
차량단독 - 공작물충돌          311     311      311       0      311      311
차량단독 - 기타             689     689      689       0      689      689
차량단독 - 도로외이탈 - 기타      10      10       10       0       10       10
차량단독 - 도로외이탈 - 추락      13      13       13       0       13       13
차량단독 - 전도전복 - 전도      126     126      126      39      126      126
차량단독 - 전도전복 - 전복       13      13       13       6       13       13
차량단독 - 주/정차차량 충돌        9       9        9       0        9        9

### 차사고 분류

In [21]:
# 차대사람 3만건
man_car = accident[accident['acc_case'].str.contains('차대사람')]
man_car

             date           acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
7        2018년 1월         차대사람 - 횡단중      여     40대      여     60대    서울중부
12       2018년 1월         차대사람 - 횡단중      남     30대      여     60대    서울중부
17       2018년 1월         차대사람 - 횡단중      남     40대      여     30대    서울중부
18       2018년 1월  차대사람 - 길가장자리구역통행중      남     50대      여     30대    서울중부
19       2018년 1월       차대사람 - 보도통행중      여     30대      남     60대    서울중부
...           ...                ...    ...     ...    ...     ...     ...
140948   2019년 3월       차대사람 - 차도통행중      여     40대      남  90대 이상    마산중부
140949   2019년 8월         차대사람 - 횡단중      남     40대      여  90대 이상    마산중부
140950  2020년 12월       차대사람 - 차도통행중      여     40대      여  90대 이상    창원중부
140951   2019년 4월         차대사람 - 횡단중      남     60대      남  90대 이상   진해경찰서
140952   2019년 5월       차대사람 - 차도통행중      남     20대      남  90대 이상   진해경찰서

[33895 rows x 7 columns]

In [24]:
#차대차 10만건
car_car = accident[accident['acc_case'].str.contains('차대차')]
car_car

             date     acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
0        2018년 1월   차대차 - 측면충돌      남     20대      남     50대    서울중부
1        2018년 1월   차대차 - 측면충돌      여     50대      남     70대    서울중부
2        2018년 1월   차대차 - 측면충돌      남     40대      남     50대    서울중부
3        2018년 1월     차대차 - 기타   기타불명     미분류      여     40대    서울중부
4        2018년 1월     차대차 - 기타      남     60대      남     50대    서울중부
...           ...          ...    ...     ...    ...     ...     ...
140920  2018년 11월    차대차  - 추돌      여     40대      남  90대 이상    서울도봉
140923   2018년 6월  차대차  - 측면충돌   기타불명     미분류      남  90대 이상    서울은평
140924   2018년 8월    차대차  - 추돌      남     60대      남  90대 이상    서울수서
140941  2018년 10월   차대차 - 측면충돌      남     60대      남  90대 이상      진주
140953   2020년 9월     차대차 - 기타      여     40대      남  90대 이상   진해경찰서

[102481 rows x 7 columns]

In [25]:
# 차량단독 4천건
car_only = accident[accident['acc_case'].str.contains('차량단독')]
car_only

             date          acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
11       2018년 1월         차량단독 - 기타      남     50대    NaN     미분류    서울중부
41       2018년 1월         차량단독 - 기타      남     50대    NaN     미분류    서울중부
83       2018년 2월      차량단독 - 공작물충돌      남     50대    NaN     미분류    서울중부
186      2018년 4월         차량단독 - 기타      남     60대    NaN     미분류    서울중부
226      2018년 5월         차량단독 - 기타      남     60대    NaN     미분류    서울중부
...           ...               ...    ...     ...    ...     ...     ...
140684  2020년 10월         차량단독 - 기타      남     50대    NaN     미분류   진해경찰서
140714  2020년 11월  차량단독 - 전도전복 - 전도      남     10대    NaN     미분류   진해경찰서
140748  2020년 11월      차량단독 - 공작물충돌      남     10대    NaN     미분류   진해경찰서
140755  2020년 11월         차량단독 - 기타      남     40대    NaN     미분류   진해경찰서
140800  2020년 12월      차량단독 - 공작물충돌      남     10대    NaN     미분류   진해경찰서

[4578 rows x 7 columns]

### 가해자 성별 분류

In [27]:
accident.groupby(accident['ofn_sx']).count()
#기타불명 3,226 건
#남 111,880 건
#여 25,848 건

          date  acc_case  ofn_age  vic_sx  vic_age  jur_stn
ofn_sx
기타불명      3226      3226     3226    3208     3226     3226
남       111880    111880   111880  107738   111880   111880
여        25848     25848    25848   25581    25848    25848

In [28]:
#여자
woman = accident[accident['ofn_sx'].str.contains('여')]
woman

             date      acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
1        2018년 1월    차대차 - 측면충돌      여     50대      남     70대    서울중부
7        2018년 1월    차대사람 - 횡단중      여     40대      여     60대    서울중부
19       2018년 1월  차대사람 - 보도통행중      여     30대      남     60대    서울중부
22       2018년 1월    차대차 - 측면충돌      여     40대      남     60대    서울중부
31       2018년 1월      차대차 - 추돌      여     50대      남     60대    서울중부
...           ...           ...    ...     ...    ...     ...     ...
140945  2019년 11월    차대사람 - 횡단중      여     50대      여  90대 이상      진주
140947   2019년 4월    차대사람 - 횡단중      여     40대      여  90대 이상    마산동부
140948   2019년 3월  차대사람 - 차도통행중      여     40대      남  90대 이상    마산중부
140950  2020년 12월  차대사람 - 차도통행중      여     40대      여  90대 이상    창원중부
140953   2020년 9월      차대차 - 기타      여     40대      남  90대 이상   진해경찰서

[25848 rows x 7 columns]

In [29]:
#남자
man = accident[accident['ofn_sx'].str.contains('남')]
man

             date      acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
0        2018년 1월    차대차 - 측면충돌      남     20대      남     50대    서울중부
2        2018년 1월    차대차 - 측면충돌      남     40대      남     50대    서울중부
4        2018년 1월      차대차 - 기타      남     60대      남     50대    서울중부
5        2018년 1월      차대차 - 추돌      남     30대      남     30대    서울중부
6        2018년 1월    차대차 - 측면충돌      남     50대      남     40대    서울중부
...           ...           ...    ...     ...    ...     ...     ...
140942  2018년 10월    차대사람 - 횡단중      남     40대      여  90대 이상      진주
140944  2019년 10월    차대사람 - 횡단중      남     30대      여  90대 이상      진주
140949   2019년 8월    차대사람 - 횡단중      남     40대      여  90대 이상    마산중부
140951   2019년 4월    차대사람 - 횡단중      남     60대      남  90대 이상   진해경찰서
140952   2019년 5월  차대사람 - 차도통행중      남     20대      남  90대 이상   진해경찰서

[111880 rows x 7 columns]

In [30]:
#기타
etc = accident[accident['ofn_sx'].str.contains('기타불명')]
etc

             date     acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
3        2018년 1월     차대차 - 기타   기타불명     미분류      여     40대    서울중부
8        2018년 1월     차대차 - 추돌   기타불명     미분류      남     40대    서울중부
20       2018년 1월    차대사람 - 기타   기타불명     미분류      여     60대    서울중부
34       2018년 1월     차대차 - 기타   기타불명     미분류      남     60대    서울중부
66       2018년 2월   차대사람 - 횡단중   기타불명     미분류      여     20대    서울중부
...           ...          ...    ...     ...    ...     ...     ...
140902   2019년 9월   차대사람  - 기타   기타불명     미분류      여  90대 이상    서울관악
140907  2019년 12월   차대사람  - 기타   기타불명     미분류      남  90대 이상    서울강동
140908  2018년 10월   차대사람  - 기타   기타불명     미분류      여  90대 이상    서울송파
140923   2018년 6월  차대차  - 측면충돌   기타불명     미분류      남  90대 이상    서울은평
140946   2019년 3월    차대사람 - 기타   기타불명     미분류      여  90대 이상    마산동부

[3226 rows x 7 columns]

### 가해자 연령별 분류

In [43]:
accident.groupby(accident['ofn_age']).count()[['date']]

          date
ofn_age
10대       3867
10대 미만       1
20대      17486
30대      22456
40대      24542
50대      32946
60대      26385
70대       8971
80대       1023
90대 이상      32
미분류       3245

In [44]:
age_10 = accident[accident['ofn_age'].str.contains('10')]
age_20 = accident[accident['ofn_age'].str.contains('20')]
age_30 = accident[accident['ofn_age'].str.contains('30')]
age_40 = accident[accident['ofn_age'].str.contains('40')]
age_50 = accident[accident['ofn_age'].str.contains('50')]
age_60 = accident[accident['ofn_age'].str.contains('60')]
age_70 = accident[accident['ofn_age'].str.contains('70')]
age_80 = accident[accident['ofn_age'].str.contains('80')]
age_90 = accident[accident['ofn_age'].str.contains('90')]
age_unknown = accident[accident['ofn_age'].str.contains('미분류')]

In [45]:
age_10

             date          acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
177      2018년 4월        차대차 - 측면충돌      남     10대      남     50대    서울중부
219      2018년 5월          차대차 - 추돌      남     10대      남     50대    서울중부
241      2018년 5월        차대차 - 측면충돌      남     10대      여     30대    서울중부
490     2018년 10월  차량단독 - 전도전복 - 전복      남     10대    미분류     미분류    서울중부
492     2018년 11월        차대차 - 측면충돌      남     10대      남     50대    서울중부
...           ...               ...    ...     ...    ...     ...     ...
140794  2020년 12월          차대차 - 기타      여     10대      여     40대   진해경찰서
140800  2020년 12월      차량단독 - 공작물충돌      남     10대    NaN     미분류   진해경찰서
140824  2020년 12월        차대차 - 정면충돌      남     10대      남     50대   진해경찰서
140868   2019년 5월        차대사람  - 기타      남     10대      남  90대 이상    서울성북
140885  2018년 10월        차대사람  - 기타      남     10대      여  90대 이상   서울영등포

[3868 rows x 7 columns]

### date 통일시키기

```
ym : 연도
acc_case : 사고 내용
ofn_sx : 가해자 성별
ofn_age : 가해자 나이
vic_sx : 피해자 성별
vic_age : 피해자 나이
jur_stn : 경찰서
- data 개수 14만개 정도
```

In [96]:
accident.head()

       date    acc_case ofn_sx ofn_age vic_sx vic_age jur_stn
0  2018년 1월  차대차 - 측면충돌      남     20대      남     50대    서울중부
1  2018년 1월  차대차 - 측면충돌      여     50대      남     70대    서울중부
2  2018년 1월  차대차 - 측면충돌      남     40대      남     50대    서울중부
3  2018년 1월    차대차 - 기타   기타불명     미분류      여     40대    서울중부
4  2018년 1월    차대차 - 기타      남     60대      남     50대    서울중부

In [122]:
accident['date'] = accident['date'].astype(str)
type(accident['date'])

pandas.core.series.Series

In [123]:
# year 뽑아내기
accident['year'] = accident['date'].apply(lambda x : str(x)[:4])
accident['year']

0         2018
1         2018
2         2018
3         2018
4         2018
          ...
140949    2019
140950    2020
140951    2019
140952    2019
140953    2020
Name: year, Length: 140954, dtype: object

In [124]:
accident['month'] = accident['date'].apply(lambda x : str(x)[6:])

In [125]:
# '월' 제거하기
accident['month'] = accident['month'].apply(lambda x : str(x)[:-1])

In [126]:
accident['half'] = accident['month'].apply(lambda x : '(상반기)' if int(x) <= 6 else '(하반기)')

In [127]:
# '2018(상반기)' 형식 만들기
accident['ym'] = accident['year'] + accident['half']
accident.head()

,date,acc_case,ofn_sx,ofn_age,vic_sx,vic_age,jur_stn,year,month,half,ym
0,2018년 1월,차대차 - 측면충돌,남,20대,남,50대,서울중부,2018,1,(상반기),2018(상반기)
1,2018년 1월,차대차 - 측면충돌,여,50대,남,70대,서울중부,2018,1,(상반기),2018(상반기)
2,2018년 1월,차대차 - 측면충돌,남,40대,남,50대,서울중부,2018,1,(상반기),2018(상반기)
3,2018년 1월,차대차 - 기타,기타불명,미분류,여,40대,서울중부,2018,1,(상반기),2018(상반기)
4,2018년 1월,차대차 - 기타,남,60대,남,50대,서울중부,2018,1,(상반기),2018(상반기)

In [21]:
# 필요없는 columns 삭제
accident.drop(['date'], axis = 1, inplace = True)
accident.head()

     acc_case ofn_sx ofn_age vic_sx vic_age jur_stn         ym
0  차대차 - 측면충돌      남     20대      남     50대    서울중부  2018(상반기)
1  차대차 - 측면충돌      여     50대      남     70대    서울중부  2018(상반기)
2  차대차 - 측면충돌      남     40대      남     50대    서울중부  2018(상반기)
3    차대차 - 기타   기타불명     미분류      여     40대    서울중부  2018(상반기)
4    차대차 - 기타      남     60대      남     50대    서울중부  2018(상반기)

### 경찰서 이름 통일시키기

In [128]:
accident['jur_stn'].unique()

array(['서울중부', '서울남대문', '서울종로', '서울혜화', '서울서대문', '서울서부', '서울용산', '서울성북',
       '서울강북', '서울동대문', '서울광진', '서울마포', '서울영등포', '서울금천', '서울성동', '서울동작',
       '서울중랑', '서울관악', '서울강남', '서울강서', '서울강동', '서울송파', '서울종암', '서울구로',
       '서울서초', '서울양천', '서울노원', '서울도봉', '서울은평', '서울방배', '서울수서', '세종',
       '수원남부', '수원서부', '수원중부', '진주', '마산동부', '마산중부', '창원서부', '창원중부',
       '진해경찰서'], dtype=object)

In [129]:
#진해경찰서를 진해로 바꾸고 한번에 뒤에 경찰서 붙이기
accident['jur_stn'].replace('진해경찰서','진해', inplace = True)

In [130]:
accident['jur_stn'][accident['jur_stn'].str.contains('경찰서')]

Series([], Name: jur_stn, dtype: object)

In [131]:
accident['jur_stn'] = accident['jur_stn'].apply(lambda x : (x + '경찰서'))
accident.head()

,date,acc_case,ofn_sx,ofn_age,vic_sx,vic_age,jur_stn,year,month,half,ym
0,2018년 1월,차대차 - 측면충돌,남,20대,남,50대,서울중부경찰서,2018,1,(상반기),2018(상반기)
1,2018년 1월,차대차 - 측면충돌,여,50대,남,70대,서울중부경찰서,2018,1,(상반기),2018(상반기)
2,2018년 1월,차대차 - 측면충돌,남,40대,남,50대,서울중부경찰서,2018,1,(상반기),2018(상반기)
3,2018년 1월,차대차 - 기타,기타불명,미분류,여,40대,서울중부경찰서,2018,1,(상반기),2018(상반기)
4,2018년 1월,차대차 - 기타,남,60대,남,50대,서울중부경찰서,2018,1,(상반기),2018(상반기)

In [132]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140954 entries, 0 to 140953
Data columns (total 11 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date      140954 non-null  object
 1   acc_case  140954 non-null  object
 2   ofn_sx    140954 non-null  object
 3   ofn_age   140954 non-null  object
 4   vic_sx    136527 non-null  object
 5   vic_age   140954 non-null  object
 6   jur_stn   140954 non-null  object
 7   year      140954 non-null  object
 8   month     140954 non-null  object
 9   half      140954 non-null  object
 10  ym        140954 non-null  object
dtypes: object(11)
memory usage: 11.8+ MB

### 피해자 성별 nan 값 처리하기

In [133]:
accident['vic_sx'].isnull().sum()

4427

In [134]:
accident['vic_sx'].unique()

array(['남', '여', nan, '미분류', '기타불명'], dtype=object)

In [135]:
accident['vic_sx'].value_counts()

남       99239
여       36854
기타불명      283
미분류       151
Name: vic_sx, dtype: int64

In [136]:
# 기타불명과 미분류 합쳐주기
accident['vic_sx'].replace('기타불명','미분류', inplace = True)
accident['vic_sx'].value_counts()

남      99239
여      36854
미분류      434
Name: vic_sx, dtype: int64

In [137]:
# na 값 미분류에 포함시키기
accident['vic_sx'].fillna('미분류', inplace = True)
accident['vic_sx']isnull().sum()

SyntaxError: invalid syntax (<ipython-input-137-bc1170cf349f>, line 3)

In [138]:
accident['vic_sx'].value_counts()

남      99239
여      36854
미분류      434
Name: vic_sx, dtype: int64

In [139]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140954 entries, 0 to 140953
Data columns (total 11 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date      140954 non-null  object
 1   acc_case  140954 non-null  object
 2   ofn_sx    140954 non-null  object
 3   ofn_age   140954 non-null  object
 4   vic_sx    136527 non-null  object
 5   vic_age   140954 non-null  object
 6   jur_stn   140954 non-null  object
 7   year      140954 non-null  object
 8   month     140954 non-null  object
 9   half      140954 non-null  object
 10  ym        140954 non-null  object
dtypes: object(11)
memory usage: 11.8+ MB

In [140]:
accident.head()

,date,acc_case,ofn_sx,ofn_age,vic_sx,vic_age,jur_stn,year,month,half,ym
0,2018년 1월,차대차 - 측면충돌,남,20대,남,50대,서울중부경찰서,2018,1,(상반기),2018(상반기)
1,2018년 1월,차대차 - 측면충돌,여,50대,남,70대,서울중부경찰서,2018,1,(상반기),2018(상반기)
2,2018년 1월,차대차 - 측면충돌,남,40대,남,50대,서울중부경찰서,2018,1,(상반기),2018(상반기)
3,2018년 1월,차대차 - 기타,기타불명,미분류,여,40대,서울중부경찰서,2018,1,(상반기),2018(상반기)
4,2018년 1월,차대차 - 기타,남,60대,남,50대,서울중부경찰서,2018,1,(상반기),2018(상반기)

In [141]:
# 10대 미만은 10대로 통일, 80대 이상 = 80대 + 90대
def set_agesex(data, col):
    
    for i in range(data.shape[0]):
        if data.loc[i,col] == '10대 미만':
            data.loc[i, col] = '10대'
            
    for i in range(data.shape[0]):
        if data.loc[i, col] == '90대 이상':
            data.loc[i,col] = '80대'
            
    for i in range(data.shape[0]):
        if data.loc[i, col] == '기타불명':
            data.loc[i,col] = '미분류'
            
    return(data)

In [214]:
accident = set_agesex(accident, 'ofn_age')

accident = set_agesex(accident, 'vic_age')
accident = set_agesex(accident, 'ofn_age')

accident = set_agesex(accident, 'vic_sx')

In [142]:
for i in accident.columns:
    print(accident[i].unique())

['2018년 1월' '2018년 2월' '2018년 3월' '2018년 4월' '2018년 5월' '2018년 6월'
 '2018년 7월' '2018년 8월' '2018년 9월' '2018년 10월' '2018년 11월' '2018년 12월'
 '2019년 1월' '2019년 2월' '2019년 3월' '2019년 4월' '2019년 5월' '2019년 6월'
 '2019년 7월' '2019년 8월' '2019년 9월' '2019년 10월' '2019년 11월' '2019년 12월'
 '2020년 1월' '2020년 2월' '2020년 3월' '2020년 4월' '2020년 5월' '2020년 6월'
 '2020년 7월' '2020년 8월' '2020년 9월' '2020년 10월' '2020년 11월' '2020년 12월']
['차대차 - 측면충돌' '차대차 - 기타' '차대차 - 추돌' '차대사람 - 횡단중' '차량단독 - 기타'
 '차대사람 - 길가장자리구역통행중' '차대사람 - 보도통행중' '차대사람 - 기타' '차대사람 - 차도통행중'
 '차량단독 - 공작물충돌' '차대차 - 정면충돌' '차대차 - 후진중충돌' '차량단독 - 전도전복 - 전도'
 '차량단독 - 주/정차차량 충돌' '차량단독 - 전도전복 - 전복' '차량단독 - 도로외이탈 - 추락'
 '차대사람  - 길가장자리구역통행중' '차대사람  - 횡단중' '차대차  - 추돌' '차대차  - 측면충돌' '차량단독  - 기타'
 '차량단독  - 전도전복 - 전도' '차대사람  - 차도통행중' '차대차  - 기타' '차대사람  - 기타'
 '차대사람  - 보도통행중' '차대차  - 후진중충돌' '차대차  - 정면충돌' '차량단독  - 공작물충돌'
 '차량단독  - 주/정차차량 충돌' '차량단독  - 전도전복 - 전복' '차량단독  - 도로외이탈 - 기타'
 '차량단독  - 도로외이탈 - 추락' '차량단독 - 도로외이탈 - 기타']
['남' '여' '기타불명']
['20대' '50대' '40대' '미분류' '60대' '30대' '70대' '10대' '80대' '10대 미만' '90대 이상']
['남' '여' nan '미분류']
['50대' '70대' '40대' '30대' '60대' '미분류' '20대' '80대' '10대' '90대 이상' '10대 미만']
['서울중부경찰서' '서울남대문경찰서' '서울종로경찰서' '서울혜화경찰서' '서울서대문경찰서' '서울서부경찰서' '서울용산경찰서'
 '서울성북경찰서' '서울강북경찰서' '서울동대문경찰서' '서울광진경찰서' '서울마포경찰서' '서울영등포경찰서' '서울금천경찰서'
 '서울성동경찰서' '서울동작경찰서' '서울중랑경찰서' '서울관악경찰서' '서울강남경찰서' '서울강서경찰서' '서울강동경찰서'
 '서울송파경찰서' '서울종암경찰서' '서울구로경찰서' '서울서초경찰서' '서울양천경찰서' '서울노원경찰서' '서울도봉경찰서'
 '서울은평경찰서' '서울방배경찰서' '서울수서경찰서' '세종경찰서' '수원남부경찰서' '수원서부경찰서' '수원중부경찰서'
 '진주경찰서' '마산동부경찰서' '마산중부경찰서' '창원서부경찰서' '창원중부경찰서' '진해경찰서']
['2018' '2019' '2020']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12']
['(상반기)' '(하반기)']
['2018(상반기)' '2018(하반기)' '2019(상반기)' '2019(하반기)' '2020(상반기)' '2020(하반기)']

### 경찰서별 연도별 acc_case count해서 컬럼으로 생성하기

In [161]:
#accident.drop(['date','month','half'],axis = 1, inplace = True)
accident.head()

     acc_case ofn_sx ofn_age vic_sx vic_age  jur_stn  year         ym
0  차대차 - 측면충돌      남     20대      남     50대  서울중부경찰서  2018  2018(상반기)
1  차대차 - 측면충돌      여     50대      남     70대  서울중부경찰서  2018  2018(상반기)
2  차대차 - 측면충돌      남     40대      남     50대  서울중부경찰서  2018  2018(상반기)
3    차대차 - 기타   기타불명     미분류      여     40대  서울중부경찰서  2018  2018(상반기)
4    차대차 - 기타      남     60대      남     50대  서울중부경찰서  2018  2018(상반기)

In [172]:
accident["acc_case"] = accident.acc_case.str.replace(" ","")

In [173]:
## 경찰서, date별 acc_case count하기
# ofn_sx를 수치형 카운트로 사용하기 위해 남겨둠
# reset_index 하면 index에 있던 것들이 컬럼으로 올라간다.
# reset_index(level = 0)은 0번째 idx를 컬럼으로 설정한다는 뜻
acs_18_1 = accident[accident.ym == '2018(상반기)'].groupby(['ym','jur_stn','acc_case']).count().drop(['year','ofn_age','vic_sx','vic_age'], axis = 1)
acs_18_1 = acs_18_1.reset_index(level = 0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_18_1 = acs_18_1.pivot(index = 'jur_stn', columns = 'acc_case', values = 'ofn_sx').fillna(0).reset_index(level = 0)
acs_18_1

acc_case,jur_stn,차대사람-기타,차대사람-길가장자리구역통행중,차대사람-보도통행중,차대사람-차도통행중,차대사람-횡단중,차대차-기타,차대차-정면충돌,차대차-추돌,차대차-측면충돌,차대차-후진중충돌,차량단독-공작물충돌,차량단독-기타,차량단독-도로외이탈-기타,차량단독-도로외이탈-추락,차량단독-전도전복-전도,차량단독-전도전복-전복,차량단독-주/정차차량충돌
0,마산동부경찰서,11.0,6.0,5.0,14.0,37.0,28.0,3.0,34.0,58.0,1.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0
1,마산중부경찰서,19.0,10.0,1.0,13.0,32.0,29.0,2.0,42.0,82.0,2.0,4.0,14.0,0.0,0.0,4.0,0.0,0.0
2,서울강남경찰서,95.0,32.0,9.0,19.0,47.0,287.0,16.0,236.0,221.0,7.0,5.0,10.0,0.0,0.0,1.0,0.0,0.0
3,서울강동경찰서,104.0,7.0,19.0,14.0,49.0,141.0,17.0,84.0,188.0,5.0,2.0,17.0,1.0,0.0,0.0,1.0,0.0
4,서울강북경찰서,71.0,13.0,11.0,34.0,71.0,96.0,25.0,80.0,194.0,8.0,4.0,14.0,0.0,0.0,2.0,0.0,0.0
5,서울강서경찰서,68.0,15.0,11.0,26.0,71.0,120.0,7.0,116.0,261.0,5.0,4.0,30.0,0.0,0.0,3.0,0.0,0.0
6,서울관악경찰서,63.0,13.0,13.0,21.0,55.0,93.0,8.0,102.0,203.0,6.0,3.0,14.0,0.0,0.0,0.0,1.0,0.0
7,서울광진경찰서,42.0,21.0,7.0,6.0,52.0,91.0,7.0,125.0,187.0,3.0,8.0,10.0,0.0,0.0,3.0,0.0,0.0
8,서울구로경찰서,49.0,14.0,12.0,18.0,90.0,143.0,22.0,155.0,183.0,7.0,8.0,23.0,0.0,0.0,3.0,0.0,0.0
9,서울금천경찰서,80.0,1.0,6.0,15.0,54.0,61.0,9.0,88.0,182.0,5.0,8.0,11.0,0.0,0.0,3.0,0.0,0.0
10,서울남대문경찰서,28.0,6.0,5.0,17.0,24.0,19.0,3.0,82.0,96.0,2.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0
11,서울노원경찰서,64.0,14.0,12.0,33.0,98.0,117.0,14.0,160.0,244.0,8.0,8.0,12.0,0.0,0.0,2.0,0.0,0.0
12,서울도봉경찰서,49.0,8.0,5.0,14.0,64.0,86.0,6.0,44.0,115.0,3.0,3.0,11.0,0.0,0.0,1.0,1.0,0.0
13,서울동대문경찰서,112.0,13.0,13.0,19.0,84.0,206.0,20.0,110.0,224.0,7.0,6.0,21.0,0.0,0.0,0.0,0.0,0.0
14,서울동작경찰서,71.0,20.0,9.0,28.0,87.0,60.0,12.0,122.0,225.0,5.0,4.0,14.0,0.0,0.0,5.0,0.0,0.0
15,서울마포경찰서,82.0,16.0,8.0,34.0,81.0,154.0,14.0,178.0,250.0,6.0,5.0,26.0,0.0,0.0,1.0,1.0,0.0
16,서울방배경찰서,13.0,5.0,9.0,6.0,39.0,27.0,1.0,58.0,108.0,2.0,4.0,7.0,0.0,0.0,0.0,0.0,0.0
17,서울서대문경찰서,38.0,8.0,7.0,22.0,70.0,23.0,16.0,89.0,178.0,4.0,7.0,17.0,0.0,0.0,1.0,0.0,0.0
18,서울서부경찰서,22.0,4.0,5.0,9.0,29.0,10.0,6.0,13.0,95.0,1.0,1.0,4.0,0.0,0.0,1.0,0.0,0.0
19,서울서초경찰서,82.0,15.0,12.0,25.0,51.0,156.0,26.0,193.0,317.0,10.0,5.0,9.0,1.0,1.0,1.0,1.0,0.0
20,서울성동경찰서,61.0,7.0,4.0,7.0,48.0,129.0,6.0,127.0,133.0,6.0,9.0,14.0,0.0,0.0,4.0,0.0,0.0
21,서울성북경찰서,29.0,6.0,5.0,11.0,68.0,42.0,14.0,77.0,171.0,1.0,2.0,7.0,0.0,0.0,4.0,0.0,0.0
22,서울송파경찰서,132.0,27.0,15.0,42.0,132.0,139.0,42.0,260.0,551.0,14.0,9.0,35.0,0.0,0.0,4.0,1.0,1.0
23,서울수서경찰서,84.0,25.0,10.0,2.0,65.0,253.0,11.0,151.0,131.0,0.0,5.0,12.0,1.0,0.0,0.0,0.0,0.0
24,서울양천경찰서,96.0,14.0,5.0,10.0,73.0,213.0,8.0,147.0,130.0,8.0,0.0,22.0,0.0,0.0,1.0,0.0,0.0
25,서울영등포경찰서,100.0,28.0,21.0,26.0,98.0,189.0,38.0,223.0,442.0,15.0,8.0,18.0,0.0,0.0,3.0,0.0,0.0
26,서울용산경찰서,50.0,9.0,5.0,14.0,68.0,101.0,17.0,148.0,225.0,3.0,12.0,16.0,0.0,0.0,1.0,1.0,0.0
27,서울은평경찰서,41.0,13.0,5.0,18.0,45.0,43.0,6.0,52.0,73.0,5.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0
28,서울종로경찰서,8.0,11.0,5.0,25.0,41.0,3.0,6.0,56.0,130.0,2.0,5.0,2.0,0.0,0.0,1.0,0.0,0.0
29,서울종암경찰서,18.0,2.0,3.0,13.0,40.0,27.0,4.0,53.0,124.0,2.0,3.0,15.0,0.0,0.0,0.0,0.0,0.0
30,서울중랑경찰서,82.0,12.0,12.0,16.0,101.0,170.0,13.0,134.0,197.0,9.0,3.0,15.0,0.0,0.0,6.0,1.0,0.0
31,서울중부경찰서,16.0,7.0,6.0,13.0,35.0,23.0,2.0,56.0,130.0,2.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0
32,서울혜화경찰서,30.0,9.0,4.0,17.0,19.0,18.0,2.0,50.0,109.0,4.0,1.0,9.0,0.0,0.0,6.0,0.0,0.0
33,세종경찰서,24.0,4.0,5.0,10.0,25.0,30.0,27.0,90.0,194.0,7.0,15.0,7.0,0.0,0.0,5.0,1.0,0.0
34,수원남부경찰서,81.0,11.0,5.0,29.0,86.0,165.0,11.0,176.0,311.0,13.0,3.0,17.0,0.0,0.0,1.0,0.0,0.0
35,수원서부경찰서,60.0,2.0,7.0,11.0,52.0,150.0,31.0,140.0,208.0,5.0,2.0,6.0,0.0,0.0,0.0,0.0,0.0
36,수원중부경찰서,122.0,10.0,4.0,8.0,88.0,293.0,25.0,166.0,152.0,8.0,4.0,30.0,0.0,0.0,1.0,1.0,0.0
37,진주경찰서,26.0,3.0,8.0,16.0,78.0,30.0,16.0,48.0,142.0,3.0,7.0,3.0,0.0,0.0,3.0,1.0,2.0
38,진해경찰서,10.0,2.0,4.0,13.0,18.0,15.0,4.0,43.0,118.0,2.0,5.0,3.0,0.0,1.0,1.0,0.0,0.0
39,창원서부경찰서,33.0,6.0,4.0,11.0,23.0,64.0,5.0,71.0,124.0,2.0,4.0,7.0,0.0,0.0,0.0,0.0,0.0
40,창원중부경찰서,14.0,5.0,7.0,21.0,47.0,15.0,10.0,64.0,145.0,4.0,2.0,2.0,0.0,0.0,2.0,0.0,0.0

In [157]:
acs_18.jur_stn.unique()

array(['마산동부경찰서', '마산중부경찰서', '서울강남경찰서', '서울강동경찰서', '서울강북경찰서', '서울강서경찰서',
       '서울관악경찰서', '서울광진경찰서', '서울구로경찰서', '서울금천경찰서', '서울남대문경찰서', '서울노원경찰서',
       '서울도봉경찰서', '서울동대문경찰서', '서울동작경찰서', '서울마포경찰서', '서울방배경찰서', '서울서대문경찰서',
       '서울서부경찰서', '서울서초경찰서', '서울성동경찰서', '서울성북경찰서', '서울송파경찰서', '서울수서경찰서',
       '서울양천경찰서', '서울영등포경찰서', '서울용산경찰서', '서울은평경찰서', '서울종로경찰서', '서울종암경찰서',
       '서울중랑경찰서', '서울중부경찰서', '서울혜화경찰서', '세종경찰서', '수원남부경찰서', '수원서부경찰서',
       '수원중부경찰서', '진주경찰서', '진해경찰서', '창원서부경찰서', '창원중부경찰서'], dtype=object)

In [174]:
acs_18_2 = accident[accident.ym == '2018(하반기)'].groupby(['ym','jur_stn','acc_case']).count().drop(['ofn_age','vic_sx','vic_age'], axis = 1)
acs_18_2 = acs_18_2.reset_index(level = 0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_18_2 = acs_18_2.pivot(index = 'jur_stn', columns = 'acc_case', values = 'ofn_sx').fillna(0).reset_index(level = 0)
acs_18_2

acc_case,jur_stn,차대사람-기타,차대사람-길가장자리구역통행중,차대사람-보도통행중,차대사람-차도통행중,차대사람-횡단중,차대차-기타,차대차-정면충돌,차대차-추돌,차대차-측면충돌,차대차-후진중충돌,차량단독-공작물충돌,차량단독-기타,차량단독-도로외이탈-기타,차량단독-도로외이탈-추락,차량단독-전도전복-전도,차량단독-전도전복-전복,차량단독-주/정차차량충돌
0,마산동부경찰서,10.0,3.0,6.0,13.0,31.0,12.0,10.0,28.0,64.0,2.0,4.0,2.0,0.0,0.0,1.0,0.0,0.0
1,마산중부경찰서,27.0,9.0,4.0,7.0,39.0,58.0,3.0,55.0,82.0,5.0,5.0,10.0,0.0,1.0,3.0,0.0,0.0
2,서울강남경찰서,80.0,32.0,13.0,21.0,56.0,307.0,20.0,198.0,281.0,11.0,7.0,11.0,0.0,0.0,1.0,0.0,0.0
3,서울강동경찰서,90.0,15.0,12.0,10.0,74.0,179.0,19.0,119.0,173.0,7.0,6.0,18.0,0.0,0.0,0.0,0.0,0.0
4,서울강북경찰서,88.0,12.0,8.0,18.0,72.0,115.0,25.0,74.0,163.0,7.0,2.0,18.0,0.0,0.0,3.0,0.0,0.0
5,서울강서경찰서,72.0,8.0,10.0,20.0,88.0,185.0,13.0,109.0,226.0,5.0,1.0,24.0,0.0,0.0,1.0,2.0,0.0
6,서울관악경찰서,59.0,14.0,16.0,24.0,52.0,83.0,16.0,106.0,200.0,6.0,5.0,16.0,0.0,0.0,1.0,0.0,0.0
7,서울광진경찰서,41.0,24.0,11.0,18.0,46.0,77.0,12.0,103.0,200.0,6.0,2.0,9.0,0.0,0.0,1.0,0.0,0.0
8,서울구로경찰서,71.0,10.0,11.0,26.0,78.0,185.0,20.0,122.0,241.0,10.0,8.0,23.0,0.0,0.0,2.0,0.0,0.0
9,서울금천경찰서,61.0,5.0,4.0,5.0,55.0,71.0,12.0,86.0,189.0,1.0,3.0,15.0,0.0,0.0,0.0,1.0,0.0
10,서울남대문경찰서,17.0,0.0,5.0,12.0,18.0,20.0,1.0,90.0,74.0,5.0,2.0,9.0,0.0,0.0,0.0,0.0,0.0
11,서울노원경찰서,45.0,4.0,16.0,20.0,74.0,138.0,24.0,142.0,273.0,16.0,5.0,21.0,0.0,0.0,0.0,0.0,0.0
12,서울도봉경찰서,52.0,6.0,4.0,10.0,71.0,98.0,10.0,43.0,98.0,1.0,1.0,20.0,0.0,0.0,1.0,0.0,0.0
13,서울동대문경찰서,140.0,10.0,5.0,25.0,70.0,213.0,16.0,124.0,224.0,7.0,5.0,21.0,0.0,0.0,2.0,0.0,0.0
14,서울동작경찰서,71.0,17.0,10.0,30.0,81.0,96.0,19.0,115.0,237.0,13.0,6.0,17.0,1.0,0.0,2.0,0.0,0.0
15,서울마포경찰서,93.0,5.0,12.0,16.0,58.0,186.0,15.0,178.0,259.0,8.0,6.0,10.0,0.0,0.0,2.0,1.0,0.0
16,서울방배경찰서,22.0,1.0,1.0,5.0,39.0,30.0,5.0,66.0,112.0,4.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0
17,서울서대문경찰서,56.0,7.0,10.0,24.0,76.0,57.0,17.0,73.0,173.0,4.0,5.0,16.0,0.0,0.0,2.0,0.0,0.0
18,서울서부경찰서,19.0,6.0,3.0,11.0,18.0,15.0,6.0,35.0,139.0,6.0,2.0,7.0,0.0,0.0,2.0,0.0,0.0
19,서울서초경찰서,97.0,5.0,18.0,25.0,53.0,165.0,34.0,196.0,332.0,8.0,3.0,9.0,0.0,0.0,0.0,0.0,0.0
20,서울성동경찰서,59.0,12.0,12.0,4.0,55.0,154.0,4.0,95.0,149.0,4.0,11.0,14.0,0.0,0.0,0.0,0.0,0.0
21,서울성북경찰서,35.0,2.0,6.0,11.0,68.0,49.0,12.0,54.0,127.0,5.0,5.0,9.0,0.0,0.0,1.0,0.0,0.0
22,서울송파경찰서,123.0,22.0,13.0,24.0,119.0,177.0,47.0,242.0,603.0,21.0,11.0,39.0,0.0,0.0,5.0,0.0,0.0
23,서울수서경찰서,73.0,24.0,11.0,10.0,52.0,293.0,7.0,155.0,95.0,6.0,1.0,16.0,0.0,0.0,1.0,0.0,0.0
24,서울양천경찰서,74.0,5.0,6.0,15.0,66.0,222.0,13.0,133.0,137.0,3.0,4.0,19.0,0.0,0.0,1.0,0.0,0.0
25,서울영등포경찰서,111.0,18.0,19.0,25.0,113.0,225.0,33.0,231.0,466.0,13.0,7.0,16.0,0.0,0.0,1.0,0.0,0.0
26,서울용산경찰서,71.0,3.0,3.0,12.0,58.0,137.0,6.0,179.0,175.0,3.0,4.0,12.0,0.0,0.0,0.0,0.0,0.0
27,서울은평경찰서,50.0,11.0,9.0,15.0,34.0,65.0,10.0,45.0,93.0,5.0,4.0,6.0,0.0,0.0,2.0,0.0,0.0
28,서울종로경찰서,14.0,9.0,12.0,24.0,39.0,12.0,7.0,51.0,119.0,5.0,1.0,5.0,0.0,0.0,1.0,0.0,0.0
29,서울종암경찰서,19.0,10.0,8.0,8.0,32.0,27.0,9.0,56.0,125.0,2.0,5.0,7.0,0.0,0.0,2.0,0.0,0.0
30,서울중랑경찰서,81.0,21.0,10.0,19.0,78.0,188.0,26.0,117.0,210.0,16.0,8.0,23.0,0.0,0.0,2.0,0.0,0.0
31,서울중부경찰서,12.0,10.0,9.0,14.0,38.0,14.0,10.0,45.0,105.0,4.0,3.0,6.0,0.0,0.0,3.0,1.0,1.0
32,서울혜화경찰서,19.0,6.0,7.0,8.0,26.0,26.0,8.0,48.0,90.0,5.0,1.0,6.0,0.0,0.0,3.0,0.0,0.0
33,세종경찰서,16.0,2.0,1.0,2.0,26.0,60.0,18.0,73.0,140.0,2.0,3.0,5.0,0.0,1.0,2.0,0.0,0.0
34,수원남부경찰서,79.0,12.0,7.0,18.0,82.0,158.0,18.0,141.0,356.0,13.0,4.0,20.0,0.0,0.0,0.0,0.0,0.0
35,수원서부경찰서,56.0,1.0,4.0,12.0,35.0,159.0,21.0,147.0,172.0,8.0,5.0,11.0,0.0,0.0,2.0,0.0,0.0
36,수원중부경찰서,136.0,4.0,6.0,14.0,75.0,272.0,23.0,134.0,184.0,8.0,5.0,18.0,0.0,0.0,2.0,1.0,0.0
37,진주경찰서,20.0,4.0,10.0,24.0,87.0,45.0,20.0,43.0,148.0,3.0,5.0,6.0,1.0,1.0,4.0,0.0,0.0
38,진해경찰서,17.0,2.0,2.0,18.0,31.0,32.0,6.0,51.0,125.0,2.0,4.0,3.0,0.0,0.0,2.0,1.0,1.0
39,창원서부경찰서,31.0,6.0,3.0,9.0,36.0,77.0,5.0,71.0,114.0,4.0,6.0,7.0,0.0,1.0,1.0,0.0,0.0
40,창원중부경찰서,13.0,6.0,3.0,20.0,53.0,36.0,17.0,54.0,141.0,3.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0

In [175]:
acs_19_1 = accident[accident.ym == '2019(상반기)'].groupby(['ym','jur_stn','acc_case']).count().drop(['ofn_age','vic_sx','vic_age'], axis = 1)
acs_19_1= acs_19_1.reset_index(level = 0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_19_1 = acs_19_1.pivot(index = 'jur_stn', columns = 'acc_case', values = 'ofn_sx').fillna(0).reset_index(level = 0)
acs_19_1

acs_19_2 = accident[accident.ym == '2019(하반기)'].groupby(['ym','jur_stn','acc_case']).count().drop(['ofn_age','vic_sx','vic_age'], axis = 1)
acs_19_2= acs_19_2.reset_index(level = 0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_19_2 = acs_19_2.pivot(index = 'jur_stn', columns = 'acc_case', values = 'ofn_sx').fillna(0).reset_index(level = 0)
acs_19_2

acc_case,jur_stn,차대사람-기타,차대사람-길가장자리구역통행중,차대사람-보도통행중,차대사람-차도통행중,차대사람-횡단중,차대차-기타,차대차-정면충돌,차대차-추돌,차대차-측면충돌,차대차-후진중충돌,차량단독-공작물충돌,차량단독-기타,차량단독-도로외이탈-기타,차량단독-도로외이탈-추락,차량단독-전도전복-전도,차량단독-전도전복-전복,차량단독-주/정차차량충돌
0,마산동부경찰서,18.0,6.0,2.0,23.0,35.0,34.0,9.0,36.0,69.0,3.0,2.0,5.0,1.0,0.0,0.0,0.0,0.0
1,마산중부경찰서,34.0,5.0,2.0,11.0,32.0,55.0,15.0,38.0,99.0,4.0,7.0,20.0,0.0,0.0,3.0,0.0,0.0
2,서울강남경찰서,134.0,28.0,21.0,10.0,52.0,359.0,24.0,147.0,381.0,16.0,7.0,13.0,0.0,0.0,1.0,0.0,0.0
3,서울강동경찰서,85.0,10.0,18.0,19.0,89.0,103.0,27.0,104.0,234.0,10.0,3.0,12.0,0.0,1.0,0.0,0.0,0.0
4,서울강북경찰서,92.0,16.0,6.0,14.0,70.0,92.0,17.0,95.0,222.0,9.0,3.0,22.0,0.0,0.0,1.0,0.0,0.0
5,서울강서경찰서,111.0,15.0,15.0,23.0,79.0,205.0,20.0,120.0,335.0,16.0,5.0,25.0,0.0,0.0,1.0,0.0,0.0
6,서울관악경찰서,70.0,9.0,11.0,20.0,63.0,155.0,18.0,90.0,225.0,13.0,1.0,25.0,0.0,0.0,2.0,0.0,0.0
7,서울광진경찰서,82.0,5.0,6.0,14.0,33.0,60.0,14.0,81.0,186.0,4.0,2.0,8.0,0.0,0.0,3.0,0.0,0.0
8,서울구로경찰서,82.0,10.0,11.0,13.0,85.0,208.0,14.0,108.0,203.0,7.0,1.0,18.0,0.0,0.0,1.0,1.0,0.0
9,서울금천경찰서,65.0,5.0,11.0,4.0,46.0,97.0,17.0,53.0,153.0,3.0,3.0,16.0,0.0,0.0,2.0,0.0,0.0
10,서울남대문경찰서,27.0,5.0,6.0,10.0,18.0,21.0,1.0,40.0,146.0,8.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0
11,서울노원경찰서,65.0,4.0,14.0,34.0,92.0,189.0,23.0,128.0,329.0,10.0,2.0,14.0,0.0,0.0,0.0,0.0,0.0
12,서울도봉경찰서,50.0,3.0,5.0,12.0,67.0,81.0,16.0,42.0,137.0,6.0,2.0,15.0,0.0,0.0,2.0,0.0,0.0
13,서울동대문경찰서,99.0,9.0,12.0,24.0,80.0,183.0,20.0,151.0,260.0,9.0,6.0,21.0,0.0,0.0,2.0,0.0,0.0
14,서울동작경찰서,67.0,12.0,13.0,32.0,70.0,91.0,11.0,132.0,254.0,15.0,4.0,22.0,0.0,0.0,0.0,0.0,0.0
15,서울마포경찰서,94.0,6.0,11.0,18.0,54.0,196.0,18.0,120.0,242.0,10.0,7.0,20.0,0.0,0.0,2.0,0.0,0.0
16,서울방배경찰서,22.0,6.0,3.0,3.0,29.0,21.0,4.0,55.0,138.0,2.0,5.0,6.0,0.0,0.0,0.0,0.0,0.0
17,서울서대문경찰서,70.0,7.0,11.0,23.0,72.0,90.0,13.0,82.0,194.0,6.0,7.0,19.0,0.0,0.0,2.0,0.0,0.0
18,서울서부경찰서,21.0,7.0,5.0,3.0,25.0,16.0,4.0,29.0,99.0,5.0,1.0,9.0,0.0,0.0,2.0,0.0,0.0
19,서울서초경찰서,101.0,4.0,17.0,18.0,49.0,282.0,38.0,160.0,277.0,18.0,10.0,9.0,0.0,2.0,4.0,1.0,0.0
20,서울성동경찰서,36.0,13.0,9.0,14.0,34.0,109.0,8.0,94.0,188.0,8.0,3.0,13.0,0.0,0.0,2.0,0.0,0.0
21,서울성북경찰서,40.0,3.0,6.0,9.0,61.0,36.0,6.0,66.0,168.0,2.0,1.0,11.0,0.0,0.0,3.0,0.0,0.0
22,서울송파경찰서,138.0,15.0,18.0,24.0,94.0,202.0,43.0,223.0,670.0,14.0,9.0,33.0,0.0,0.0,7.0,0.0,0.0
23,서울수서경찰서,92.0,22.0,16.0,12.0,60.0,344.0,16.0,123.0,133.0,1.0,2.0,17.0,0.0,0.0,0.0,0.0,0.0
24,서울양천경찰서,106.0,9.0,15.0,8.0,67.0,239.0,18.0,108.0,210.0,6.0,2.0,21.0,0.0,0.0,1.0,0.0,0.0
25,서울영등포경찰서,126.0,12.0,25.0,22.0,103.0,274.0,26.0,155.0,447.0,17.0,4.0,29.0,0.0,0.0,1.0,1.0,0.0
26,서울용산경찰서,56.0,22.0,6.0,7.0,37.0,126.0,11.0,107.0,189.0,7.0,6.0,11.0,0.0,0.0,1.0,0.0,0.0
27,서울은평경찰서,63.0,10.0,8.0,13.0,37.0,56.0,4.0,40.0,109.0,6.0,4.0,17.0,0.0,0.0,0.0,0.0,0.0
28,서울종로경찰서,32.0,2.0,4.0,25.0,30.0,10.0,5.0,45.0,154.0,4.0,6.0,8.0,0.0,1.0,2.0,0.0,0.0
29,서울종암경찰서,27.0,6.0,1.0,17.0,44.0,45.0,4.0,57.0,161.0,2.0,2.0,12.0,0.0,1.0,2.0,0.0,0.0
30,서울중랑경찰서,91.0,16.0,15.0,21.0,98.0,194.0,31.0,122.0,232.0,16.0,9.0,20.0,0.0,0.0,5.0,0.0,0.0
31,서울중부경찰서,32.0,4.0,4.0,9.0,40.0,54.0,9.0,32.0,124.0,7.0,2.0,6.0,0.0,0.0,1.0,0.0,1.0
32,서울혜화경찰서,35.0,5.0,5.0,6.0,22.0,27.0,7.0,42.0,107.0,3.0,3.0,4.0,0.0,0.0,2.0,0.0,0.0
33,세종경찰서,26.0,0.0,6.0,7.0,38.0,76.0,22.0,89.0,177.0,8.0,8.0,12.0,0.0,0.0,2.0,0.0,0.0
34,수원남부경찰서,83.0,8.0,10.0,34.0,73.0,199.0,11.0,139.0,392.0,18.0,1.0,18.0,0.0,0.0,4.0,0.0,0.0
35,수원서부경찰서,72.0,1.0,8.0,8.0,31.0,229.0,18.0,127.0,204.0,10.0,8.0,22.0,2.0,0.0,1.0,1.0,0.0
36,수원중부경찰서,113.0,7.0,3.0,10.0,66.0,278.0,9.0,138.0,170.0,16.0,4.0,20.0,0.0,0.0,2.0,0.0,0.0
37,진주경찰서,30.0,6.0,8.0,16.0,84.0,38.0,14.0,46.0,137.0,2.0,10.0,4.0,0.0,1.0,6.0,1.0,0.0
38,진해경찰서,33.0,3.0,4.0,17.0,32.0,76.0,26.0,64.0,165.0,1.0,7.0,10.0,1.0,0.0,2.0,0.0,0.0
39,창원서부경찰서,41.0,1.0,5.0,4.0,23.0,80.0,8.0,59.0,99.0,2.0,5.0,11.0,0.0,0.0,0.0,0.0,0.0
40,창원중부경찰서,28.0,2.0,6.0,26.0,43.0,23.0,4.0,49.0,144.0,6.0,1.0,1.0,0.0,0.0,3.0,0.0,1.0

In [176]:
acs_20_1 = accident[accident.ym == '2020(상반기)'].groupby(['ym','jur_stn','acc_case']).count().drop(['ofn_age','vic_sx','vic_age'], axis = 1)
acs_20_1 = acs_20_1.reset_index(level = 0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_20_1 = acs_20_1.pivot(index = 'jur_stn', columns = 'acc_case', values = 'ofn_sx').fillna(0).reset_index(level = 0)
acs_20_1

acs_20_2 = accident[accident.ym == '2020(하반기)'].groupby(['ym','jur_stn','acc_case']).count().drop(['ofn_age','vic_sx','vic_age'], axis = 1)
acs_20_2 = acs_20_2.reset_index(level = 0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_20_2 = acs_20_2.pivot(index = 'jur_stn', columns = 'acc_case', values = 'ofn_sx').fillna(0).reset_index(level = 0)
acs_20_2

acc_case,jur_stn,차대사람-기타,차대사람-길가장자리구역통행중,차대사람-보도통행중,차대사람-차도통행중,차대사람-횡단중,차대차-기타,차대차-정면충돌,차대차-추돌,차대차-측면충돌,차대차-후진중충돌,차량단독-공작물충돌,차량단독-기타,차량단독-도로외이탈-기타,차량단독-도로외이탈-추락,차량단독-전도전복-전도,차량단독-전도전복-전복,차량단독-주/정차차량충돌
0,마산동부경찰서,10.0,3.0,4.0,7.0,30.0,15.0,13.0,28.0,55.0,7.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0
1,마산중부경찰서,29.0,3.0,2.0,8.0,22.0,44.0,11.0,45.0,80.0,5.0,8.0,15.0,0.0,0.0,3.0,0.0,0.0
2,서울강남경찰서,123.0,26.0,21.0,12.0,28.0,401.0,25.0,188.0,256.0,18.0,4.0,14.0,0.0,0.0,4.0,0.0,0.0
3,서울강동경찰서,66.0,9.0,15.0,24.0,47.0,110.0,21.0,92.0,207.0,3.0,5.0,15.0,0.0,0.0,0.0,0.0,0.0
4,서울강북경찰서,79.0,4.0,5.0,12.0,34.0,187.0,13.0,53.0,118.0,9.0,0.0,22.0,0.0,0.0,1.0,0.0,0.0
5,서울강서경찰서,71.0,6.0,20.0,22.0,47.0,224.0,17.0,109.0,210.0,14.0,3.0,19.0,0.0,1.0,1.0,0.0,0.0
6,서울관악경찰서,76.0,14.0,15.0,23.0,57.0,217.0,19.0,124.0,211.0,20.0,3.0,11.0,0.0,1.0,3.0,0.0,0.0
7,서울광진경찰서,39.0,6.0,5.0,11.0,23.0,88.0,9.0,78.0,140.0,4.0,5.0,7.0,0.0,0.0,1.0,0.0,0.0
8,서울구로경찰서,53.0,9.0,20.0,23.0,43.0,140.0,23.0,93.0,207.0,8.0,4.0,19.0,0.0,0.0,6.0,0.0,0.0
9,서울금천경찰서,56.0,3.0,5.0,2.0,34.0,82.0,9.0,60.0,122.0,2.0,9.0,14.0,1.0,0.0,4.0,0.0,0.0
10,서울남대문경찰서,17.0,0.0,6.0,4.0,14.0,22.0,4.0,30.0,96.0,2.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0
11,서울노원경찰서,38.0,1.0,14.0,28.0,54.0,143.0,17.0,132.0,272.0,11.0,3.0,7.0,0.0,0.0,2.0,0.0,0.0
12,서울도봉경찰서,32.0,5.0,8.0,10.0,51.0,83.0,29.0,45.0,103.0,7.0,2.0,12.0,0.0,0.0,1.0,0.0,0.0
13,서울동대문경찰서,74.0,8.0,12.0,15.0,61.0,206.0,24.0,81.0,246.0,11.0,7.0,26.0,0.0,0.0,1.0,0.0,0.0
14,서울동작경찰서,77.0,7.0,11.0,8.0,40.0,109.0,17.0,94.0,233.0,7.0,2.0,19.0,0.0,0.0,3.0,0.0,0.0
15,서울마포경찰서,69.0,1.0,8.0,18.0,32.0,142.0,21.0,97.0,194.0,11.0,2.0,13.0,0.0,0.0,2.0,0.0,0.0
16,서울방배경찰서,21.0,2.0,8.0,6.0,12.0,28.0,2.0,53.0,141.0,9.0,1.0,6.0,0.0,0.0,2.0,0.0,0.0
17,서울서대문경찰서,45.0,3.0,6.0,13.0,37.0,88.0,10.0,50.0,186.0,8.0,2.0,18.0,0.0,0.0,2.0,0.0,0.0
18,서울서부경찰서,17.0,0.0,3.0,6.0,27.0,16.0,3.0,25.0,90.0,3.0,3.0,3.0,0.0,0.0,1.0,0.0,0.0
19,서울서초경찰서,61.0,5.0,14.0,16.0,34.0,293.0,28.0,144.0,219.0,16.0,1.0,12.0,0.0,1.0,2.0,0.0,1.0
20,서울성동경찰서,43.0,13.0,15.0,14.0,38.0,138.0,16.0,84.0,204.0,7.0,2.0,9.0,0.0,0.0,1.0,0.0,0.0
21,서울성북경찰서,34.0,0.0,4.0,11.0,33.0,43.0,9.0,44.0,98.0,5.0,3.0,4.0,0.0,0.0,3.0,0.0,0.0
22,서울송파경찰서,116.0,17.0,27.0,20.0,68.0,238.0,33.0,193.0,604.0,12.0,6.0,16.0,0.0,0.0,10.0,0.0,0.0
23,서울수서경찰서,63.0,19.0,19.0,7.0,44.0,295.0,11.0,177.0,163.0,2.0,2.0,8.0,0.0,0.0,3.0,0.0,0.0
24,서울양천경찰서,66.0,2.0,4.0,11.0,52.0,316.0,7.0,78.0,136.0,7.0,3.0,17.0,0.0,0.0,0.0,0.0,0.0
25,서울영등포경찰서,92.0,6.0,16.0,5.0,51.0,231.0,31.0,159.0,459.0,16.0,5.0,13.0,1.0,0.0,8.0,0.0,0.0
26,서울용산경찰서,34.0,2.0,7.0,4.0,22.0,153.0,10.0,59.0,91.0,6.0,3.0,8.0,1.0,0.0,1.0,0.0,0.0
27,서울은평경찰서,37.0,3.0,6.0,7.0,21.0,52.0,11.0,45.0,107.0,9.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0
28,서울종로경찰서,25.0,0.0,6.0,10.0,22.0,53.0,5.0,41.0,84.0,4.0,4.0,3.0,0.0,0.0,0.0,0.0,1.0
29,서울종암경찰서,27.0,8.0,7.0,9.0,33.0,36.0,7.0,49.0,141.0,6.0,0.0,8.0,0.0,0.0,2.0,0.0,0.0
30,서울중랑경찰서,81.0,19.0,7.0,8.0,55.0,224.0,21.0,75.0,195.0,7.0,6.0,12.0,0.0,0.0,8.0,1.0,0.0
31,서울중부경찰서,33.0,0.0,5.0,7.0,22.0,64.0,10.0,25.0,94.0,7.0,0.0,8.0,0.0,0.0,3.0,1.0,0.0
32,서울혜화경찰서,22.0,5.0,3.0,6.0,11.0,38.0,4.0,28.0,71.0,2.0,1.0,6.0,0.0,0.0,1.0,0.0,0.0
33,세종경찰서,27.0,1.0,4.0,10.0,22.0,71.0,31.0,75.0,169.0,3.0,6.0,10.0,0.0,0.0,2.0,0.0,0.0
34,수원남부경찰서,73.0,12.0,9.0,14.0,45.0,149.0,9.0,142.0,419.0,17.0,8.0,11.0,0.0,0.0,3.0,0.0,0.0
35,수원서부경찰서,54.0,0.0,7.0,8.0,19.0,177.0,13.0,110.0,167.0,10.0,4.0,13.0,0.0,0.0,2.0,0.0,0.0
36,수원중부경찰서,103.0,8.0,4.0,5.0,39.0,251.0,22.0,94.0,153.0,7.0,6.0,17.0,0.0,0.0,3.0,0.0,0.0
37,진주경찰서,23.0,2.0,6.0,7.0,77.0,43.0,6.0,47.0,102.0,1.0,7.0,3.0,1.0,0.0,2.0,0.0,0.0
38,진해경찰서,27.0,0.0,1.0,13.0,24.0,101.0,21.0,59.0,142.0,6.0,7.0,6.0,0.0,0.0,5.0,0.0,0.0
39,창원서부경찰서,37.0,2.0,0.0,2.0,26.0,42.0,16.0,61.0,111.0,6.0,1.0,6.0,0.0,0.0,1.0,0.0,0.0
40,창원중부경찰서,21.0,1.0,5.0,19.0,30.0,22.0,9.0,31.0,129.0,9.0,0.0,4.0,0.0,0.0,1.0,0.0,0.0

In [178]:
# date 변수 추가
def add_date(data, date):
    data['date'] = date
    return data

In [180]:
acs_18_1 = add_date(acs_18_1, '2018(상반기)')
acs_18_2 = add_date(acs_18_2, '2018(하반기)')
acs_19_1 = add_date(acs_19_1, '2019(상반기)')
acs_19_2 = add_date(acs_19_2, '2019(하반기)')
acs_20_1 = add_date(acs_20_1, '2020(상반기)')
acs_20_2 = add_date(acs_20_2, '2020(하반기)')

In [181]:
def sum_acc_case(data):
    data['차대사람'] = data[['차대사람-기타', '차대사람-길가장자리구역통행중','차대사람-보도통행중',
                        '차대사람-차도통행중','차대사람-횡단중']].sum(axis = 1)
    
    data['차대차'] = data[['차대차-기타','차대차-정면충돌','차대차-추돌','차대차-측면충돌', '차대차-후진중충돌']].sum(axis=1)
    
    data["차량단독"] =  data[['차량단독-공작물충돌', '차량단독-기타', '차량단독-도로외이탈-기타', '차량단독-도로외이탈-추락',
       '차량단독-전도전복-전도', '차량단독-전도전복-전복', '차량단독-주/정차차량충돌']].sum(axis=1)
    
    data = data[['jur_stn','date','차대사람','차대차','차량단독']]
    
    return data

In [182]:
acs_18_1 = sum_acc_case(acs_18_1)
acs_18_2 = sum_acc_case(acs_18_2)
acs_19_1 = sum_acc_case(acs_19_1)
acs_19_2 = sum_acc_case(acs_19_2)
acs_20_1 = sum_acc_case(acs_20_1)
acs_20_2 = sum_acc_case(acs_20_2)

In [187]:
acs_18_1.sort_values(by='차대사람', ascending= False)

acc_case   jur_stn       date   차대사람     차대차  차량단독
22         서울송파경찰서  2018(상반기)  348.0  1006.0  50.0
25        서울영등포경찰서  2018(상반기)  273.0   907.0  29.0
13        서울동대문경찰서  2018(상반기)  241.0   567.0  27.0
36         수원중부경찰서  2018(상반기)  232.0   644.0  36.0
30         서울중랑경찰서  2018(상반기)  223.0   523.0  25.0
11         서울노원경찰서  2018(상반기)  221.0   543.0  22.0
15         서울마포경찰서  2018(상반기)  221.0   602.0  33.0
14         서울동작경찰서  2018(상반기)  215.0   424.0  23.0
34         수원남부경찰서  2018(상반기)  212.0   676.0  21.0
2          서울강남경찰서  2018(상반기)  202.0   767.0  16.0
4          서울강북경찰서  2018(상반기)  200.0   403.0  20.0
24         서울양천경찰서  2018(상반기)  198.0   506.0  23.0
3          서울강동경찰서  2018(상반기)  193.0   435.0  21.0
5          서울강서경찰서  2018(상반기)  191.0   509.0  37.0
23         서울수서경찰서  2018(상반기)  186.0   546.0  18.0
19         서울서초경찰서  2018(상반기)  185.0   702.0  18.0
8          서울구로경찰서  2018(상반기)  183.0   510.0  34.0
6          서울관악경찰서  2018(상반기)  165.0   412.0  18.0
9          서울금천경찰서  2018(상반기)  156.0   345.0  22.0
26         서울용산경찰서  2018(상반기)  146.0   494.0  30.0
17        서울서대문경찰서  2018(상반기)  145.0   310.0  25.0
12         서울도봉경찰서  2018(상반기)  140.0   254.0  16.0
35         수원서부경찰서  2018(상반기)  132.0   534.0   8.0
37           진주경찰서  2018(상반기)  131.0   239.0  16.0
7          서울광진경찰서  2018(상반기)  128.0   413.0  21.0
20         서울성동경찰서  2018(상반기)  127.0   401.0  27.0
27         서울은평경찰서  2018(상반기)  122.0   179.0  17.0
21         서울성북경찰서  2018(상반기)  119.0   305.0  13.0
40         창원중부경찰서  2018(상반기)   94.0   238.0   6.0
28         서울종로경찰서  2018(상반기)   90.0   197.0   8.0
10        서울남대문경찰서  2018(상반기)   80.0   202.0   9.0
32         서울혜화경찰서  2018(상반기)   79.0   183.0  16.0
31         서울중부경찰서  2018(상반기)   77.0   213.0   7.0
39         창원서부경찰서  2018(상반기)   77.0   266.0  11.0
29         서울종암경찰서  2018(상반기)   76.0   210.0  18.0
1          마산중부경찰서  2018(상반기)   75.0   157.0  22.0
0          마산동부경찰서  2018(상반기)   73.0   124.0   6.0
16         서울방배경찰서  2018(상반기)   72.0   196.0  11.0
18         서울서부경찰서  2018(상반기)   69.0   125.0   6.0
33           세종경찰서  2018(상반기)   68.0   348.0  28.0
38           진해경찰서  2018(상반기)   47.0   182.0  10.0

In [191]:
# 경찰서별, 연도별 차대사람, 차대차, 차량단독 df 생성 완료
acs_final = pd.concat([acs_18_1,acs_18_2,acs_19_1,acs_19_2,acs_20_1,acs_20_2])
acs_final

acc_case  jur_stn       date   차대사람    차대차  차량단독
0         마산동부경찰서  2018(상반기)   73.0  124.0   6.0
1         마산중부경찰서  2018(상반기)   75.0  157.0  22.0
2         서울강남경찰서  2018(상반기)  202.0  767.0  16.0
3         서울강동경찰서  2018(상반기)  193.0  435.0  21.0
4         서울강북경찰서  2018(상반기)  200.0  403.0  20.0
..            ...        ...    ...    ...   ...
36        수원중부경찰서  2020(하반기)  159.0  527.0  26.0
37          진주경찰서  2020(하반기)  115.0  199.0  13.0
38          진해경찰서  2020(하반기)   65.0  329.0  18.0
39        창원서부경찰서  2020(하반기)   67.0  236.0   8.0
40        창원중부경찰서  2020(하반기)   76.0  200.0   5.0

[246 rows x 5 columns]

In [197]:
def csv_download_link(df, csv_file_name, delete_prompt=True):
    """Display a download link to load a data frame as csv from within a Jupyter notebook"""
    df.to_csv(csv_file_name, index=False)
    from IPython.display import FileLink
    display(FileLink(csv_file_name))
    if delete_prompt:
        a = input('Press enter to delete the file after you have downloaded it.')
        import os
        os.remove(csv_file_name)
        
csv_download_link(acs_final, 'car_acc_df.csv')

In [198]:
csv_download_link(acs_final, 'car_acc_df.csv')

/opt/app-root/src/car_acc_df.csv

Press enter to delete the file after you have downloaded it.

### 가해자 경찰서별 연도별 성별, 나이 묶기

In [202]:
accident.head()

   acc_case ofn_sx ofn_age vic_sx vic_age  jur_stn  year         ym
0  차대차-측면충돌      남     20대      남     50대  서울중부경찰서  2018  2018(상반기)
1  차대차-측면충돌      여     50대      남     70대  서울중부경찰서  2018  2018(상반기)
2  차대차-측면충돌      남     40대      남     50대  서울중부경찰서  2018  2018(상반기)
3    차대차-기타   기타불명     미분류      여     40대  서울중부경찰서  2018  2018(상반기)
4    차대차-기타      남     60대      남     50대  서울중부경찰서  2018  2018(상반기)

In [208]:
#가해자 성별
acs_ofnsex_181 = accident[accident.ym == '2018(상반기)'].groupby(['ym',"jur_stn","ofn_sx"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnsex_181 = acs_ofnsex_181.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnsex_181 = acs_ofnsex_181.pivot(index='jur_stn', columns='ofn_sx', values='ofn_age').fillna(0).reset_index(level=0)
acs_ofnsex_181.columns = ['jur_stn', '가해_성별_기타불명', '가해_남', '가해_여']
acs_ofnsex_181.head()

acs_ofnsex_182 = accident[accident.ym == '2018(하반기)'].groupby(['ym',"jur_stn","ofn_sx"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnsex_182 = acs_ofnsex_182.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnsex_182 = acs_ofnsex_182.pivot(index='jur_stn', columns='ofn_sx', values='ofn_age').fillna(0).reset_index(level=0)
acs_ofnsex_182.columns = ['jur_stn', '가해_성별_기타불명', '가해_남', '가해_여']
acs_ofnsex_182.head()

acs_ofnsex_191 = accident[accident.ym == '2019(상반기)'].groupby(['ym',"jur_stn","ofn_sx"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnsex_191 = acs_ofnsex_191.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnsex_191 = acs_ofnsex_191.pivot(index='jur_stn', columns='ofn_sx', values='ofn_age').fillna(0).reset_index(level=0)
acs_ofnsex_191.columns = ['jur_stn', '가해_성별_기타불명', '가해_남', '가해_여']
acs_ofnsex_191.head()

acs_ofnsex_192 = accident[accident.ym == '2019(하반기)'].groupby(['ym',"jur_stn","ofn_sx"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnsex_192 = acs_ofnsex_192.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnsex_192 = acs_ofnsex_192.pivot(index='jur_stn', columns='ofn_sx', values='ofn_age').fillna(0).reset_index(level=0)
acs_ofnsex_192.columns = ['jur_stn', '가해_성별_기타불명', '가해_남', '가해_여']
acs_ofnsex_192.head()

acs_ofnsex_201 = accident[accident.ym == '2020(상반기)'].groupby(['ym',"jur_stn","ofn_sx"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnsex_201 = acs_ofnsex_201.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnsex_201 = acs_ofnsex_201.pivot(index='jur_stn', columns='ofn_sx', values='ofn_age').fillna(0).reset_index(level=0)
acs_ofnsex_201.columns = ['jur_stn', '가해_성별_기타불명', '가해_남', '가해_여']
acs_ofnsex_201.head()

acs_ofnsex_202 = accident[accident.ym == '2020(하반기)'].groupby(['ym',"jur_stn","ofn_sx"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnsex_202 = acs_ofnsex_202.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnsex_202 = acs_ofnsex_202.pivot(index='jur_stn', columns='ofn_sx', values='ofn_age').fillna(0).reset_index(level=0)
acs_ofnsex_202.columns = ['jur_stn', '가해_성별_기타불명', '가해_남', '가해_여']
acs_ofnsex_202.head()

   jur_stn  가해_성별_기타불명   가해_남   가해_여
0  마산동부경찰서         0.0  134.0   42.0
1  마산중부경찰서         1.0  207.0   67.0
2  서울강남경찰서        30.0  864.0  226.0
3  서울강동경찰서        17.0  488.0  109.0
4  서울강북경찰서         6.0  448.0   83.0

In [219]:
# 가해자 나이
acs_ofnage_181 = accident[accident.ym == '2018(상반기)'].groupby(['ym',"jur_stn","ofn_age"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnage_181 = acs_ofnage_181.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnage_181 = acs_ofnage_181.pivot(index='jur_stn', columns='ofn_age', values='ofn_sx').fillna(0).reset_index(level=0)
acs_ofnage_181.columns =['jur_stn', '가해_10대이하', '가해_20대', '가해_30대', 
                             '가해_40대', '가해_50대', '가해_60대', '가해_70대', 
                             '가해_80대이상','가해_미분류']

acs_ofnage_182 = accident[accident.ym == '2018(하반기)'].groupby(['ym',"jur_stn","ofn_age"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnage_182 = acs_ofnage_182.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnage_182 = acs_ofnage_182.pivot(index='jur_stn', columns='ofn_age', values='ofn_sx').fillna(0).reset_index(level=0)
acs_ofnage_182.columns =['jur_stn', '가해_10대이하', '가해_20대', '가해_30대', 
                             '가해_40대', '가해_50대', '가해_60대', '가해_70대', 
                             '가해_80대이상','가해_미분류']

acs_ofnage_191 = accident[accident.ym == '2019(상반기)'].groupby(['ym',"jur_stn","ofn_age"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnage_191 = acs_ofnage_191.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnage_191 = acs_ofnage_191.pivot(index='jur_stn', columns='ofn_age', values='ofn_sx').fillna(0).reset_index(level=0)
acs_ofnage_191.columns =['jur_stn', '가해_10대이하', '가해_20대', '가해_30대', 
                             '가해_40대', '가해_50대', '가해_60대', '가해_70대', 
                             '가해_80대이상','가해_미분류']

acs_ofnage_192 = accident[accident.ym == '2019(하반기)'].groupby(['ym',"jur_stn","ofn_age"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnage_192 = acs_ofnage_192.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnage_192 = acs_ofnage_192.pivot(index='jur_stn', columns='ofn_age', values='ofn_sx').fillna(0).reset_index(level=0)
acs_ofnage_192.columns =['jur_stn', '가해_10대이하', '가해_20대', '가해_30대', 
                             '가해_40대', '가해_50대', '가해_60대', '가해_70대', 
                             '가해_80대이상','가해_미분류']

acs_ofnage_201 = accident[accident.ym == '2020(상반기)'].groupby(['ym',"jur_stn","ofn_age"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnage_201 = acs_ofnage_201.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnage_201 = acs_ofnage_201.pivot(index='jur_stn', columns='ofn_age', values='ofn_sx').fillna(0).reset_index(level=0)
acs_ofnage_201.columns =['jur_stn', '가해_10대이하', '가해_20대', '가해_30대', 
                             '가해_40대', '가해_50대', '가해_60대', '가해_70대', 
                             '가해_80대이상','가해_미분류']

acs_ofnage_202 = accident[accident.ym == '2020(하반기)'].groupby(['ym',"jur_stn","ofn_age"]).count().drop(["acc_case","vic_sx","vic_age"],axis=1)
acs_ofnage_202 = acs_ofnage_202.reset_index(level=0).drop(["ym"],axis=1).reset_index(level=1).reset_index(level=0)
acs_ofnage_202 = acs_ofnage_202.pivot(index='jur_stn', columns='ofn_age', values='ofn_sx').fillna(0).reset_index(level=0)
acs_ofnage_202.columns =['jur_stn', '가해_10대이하', '가해_20대', '가해_30대', 
                             '가해_40대', '가해_50대', '가해_60대', '가해_70대', 
                             '가해_80대이상','가해_미분류']
acs_ofnage_202.head()

,jur_stn,가해_10대이하,가해_20대,가해_30대,가해_40대,가해_50대,가해_60대,가해_70대,가해_80대이상,가해_미분류
0,마산동부경찰서,2.0,15.0,19.0,32.0,58.0,38.0,11.0,1.0,0.0
1,마산중부경찰서,2.0,31.0,24.0,52.0,71.0,61.0,26.0,7.0,1.0
2,서울강남경찰서,18.0,155.0,238.0,223.0,192.0,189.0,66.0,7.0,32.0
3,서울강동경찰서,29.0,62.0,91.0,96.0,153.0,119.0,41.0,6.0,17.0
4,서울강북경찰서,24.0,75.0,75.0,91.0,115.0,102.0,47.0,2.0,6.0

In [220]:
acs_ofnsex_181 = add_date(acs_ofnsex_181,'2018(상반기)')
acs_ofnsex_182 = add_date(acs_ofnsex_182,'2018(하반기)')
acs_ofnage_181 = add_date(acs_ofnsex_181,'2018(상반기)')
acs_ofnage_182 = add_date(acs_ofnsex_182,'2018(하반기)')

acs_ofnsex_191 = add_date(acs_ofnsex_191,'2019(상반기)')
acs_ofnsex_192 = add_date(acs_ofnsex_192,'2019(하반기)')
acs_ofnage_191 = add_date(acs_ofnsex_191,'2019(상반기)')
acs_ofnage_192 = add_date(acs_ofnsex_192,'2019(하반기)')

acs_ofnsex_201 = add_date(acs_ofnsex_201,'2020(상반기)')
acs_ofnsex_202 = add_date(acs_ofnsex_202,'2020(하반기)')
acs_ofnage_201 = add_date(acs_ofnsex_201,'2020(상반기)')
acs_ofnage_202 = add_date(acs_ofnsex_202,'2020(하반기)')

In [221]:
acs_ofnage_final = pd.concat([acs_ofnage_181,acs_ofnage_182,acs_ofnage_191,acs_ofnage_192,acs_ofnage_201,acs_ofnage_202])
acs_ofnsex_final = pd.concat([acs_ofnsex_181,acs_ofnsex_182,acs_ofnsex_191,acs_ofnsex_192,acs_ofnsex_201,acs_ofnsex_202])

In [223]:
# 가해자 나이
acs_ofnage_final

    jur_stn  가해_성별_기타불명   가해_남   가해_여       date
0   마산동부경찰서         3.0  157.0   43.0  2018(상반기)
1   마산중부경찰서         0.0  195.0   59.0  2018(상반기)
2   서울강남경찰서        19.0  804.0  162.0  2018(상반기)
3   서울강동경찰서        15.0  513.0  121.0  2018(상반기)
4   서울강북경찰서        19.0  514.0   90.0  2018(상반기)
..      ...         ...    ...    ...        ...
36  수원중부경찰서         4.0  550.0  158.0  2020(하반기)
37    진주경찰서         6.0  235.0   86.0  2020(하반기)
38    진해경찰서         3.0  295.0  114.0  2020(하반기)
39  창원서부경찰서         4.0  236.0   71.0  2020(하반기)
40  창원중부경찰서         1.0  204.0   76.0  2020(하반기)

[246 rows x 5 columns]

In [224]:
# 가해자 성별
acs_ofnsex_final

    jur_stn  가해_성별_기타불명   가해_남   가해_여       date
0   마산동부경찰서         3.0  157.0   43.0  2018(상반기)
1   마산중부경찰서         0.0  195.0   59.0  2018(상반기)
2   서울강남경찰서        19.0  804.0  162.0  2018(상반기)
3   서울강동경찰서        15.0  513.0  121.0  2018(상반기)
4   서울강북경찰서        19.0  514.0   90.0  2018(상반기)
..      ...         ...    ...    ...        ...
36  수원중부경찰서         4.0  550.0  158.0  2020(하반기)
37    진주경찰서         6.0  235.0   86.0  2020(하반기)
38    진해경찰서         3.0  295.0  114.0  2020(하반기)
39  창원서부경찰서         4.0  236.0   71.0  2020(하반기)
40  창원중부경찰서         1.0  204.0   76.0  2020(하반기)

[246 rows x 5 columns]

### 피해자 경찰서별 연도별 성별, 나이 묶기

In [225]:
accident.head()

   acc_case ofn_sx ofn_age vic_sx vic_age  jur_stn  year         ym
0  차대차-측면충돌      남     20대      남     50대  서울중부경찰서  2018  2018(상반기)
1  차대차-측면충돌      여     50대      남     70대  서울중부경찰서  2018  2018(상반기)
2  차대차-측면충돌      남     40대      남     50대  서울중부경찰서  2018  2018(상반기)
3    차대차-기타   기타불명     미분류      여     40대  서울중부경찰서  2018  2018(상반기)
4    차대차-기타      남     60대      남     50대  서울중부경찰서  2018  2018(상반기)

In [240]:
acs_vicsex_181 = accident[accident.ym == '2018(상반기)'].groupby(['ym','jur_stn','vic_sx']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicsex_181 = acs_vicsex_181.reset_index(level=0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicsex_181 = acs_vicsex_181.pivot(index = 'jur_stn', columns = 'vic_sx', values = 'vic_age').fillna(0).reset_index(level= 0)
acs_vicsex_181.columns = ['jur_stn','피해_남','피해_미분류','피해_여']

acs_vicsex_182 = accident[accident.ym == '2018(하반기)'].groupby(['ym','jur_stn','vic_sx']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicsex_182 = acs_vicsex_182.reset_index(level=0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicsex_182 = acs_vicsex_182.pivot(index = 'jur_stn', columns = 'vic_sx', values = 'vic_age').fillna(0).reset_index(level= 0)
acs_vicsex_182.columns = ['jur_stn','피해_남','피해_미분류','피해_여']

acs_vicsex_191 = accident[accident.ym == '2019(상반기)'].groupby(['ym','jur_stn','vic_sx']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicsex_191 = acs_vicsex_191.reset_index(level=0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicsex_191 = acs_vicsex_191.pivot(index = 'jur_stn', columns = 'vic_sx', values = 'vic_age').fillna(0).reset_index(level= 0)
acs_vicsex_191.columns = ['jur_stn','피해_남','피해_미분류','피해_여']

acs_vicsex_192 = accident[accident.ym == '2019(하반기)'].groupby(['ym','jur_stn','vic_sx']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicsex_192 = acs_vicsex_192.reset_index(level=0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicsex_192 = acs_vicsex_192.pivot(index = 'jur_stn', columns = 'vic_sx', values = 'vic_age').fillna(0).reset_index(level= 0)
acs_vicsex_192.columns = ['jur_stn','피해_남','피해_미분류','피해_여']

acs_vicsex_201 = accident[accident.ym == '2020(상반기)'].groupby(['ym','jur_stn','vic_sx']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicsex_201 = acs_vicsex_201.reset_index(level=0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicsex_201 = acs_vicsex_201.pivot(index = 'jur_stn', columns = 'vic_sx', values = 'vic_age').fillna(0).reset_index(level= 0)
acs_vicsex_201.columns = ['jur_stn','피해_남','피해_미분류','피해_여']

acs_vicsex_202 = accident[accident.ym == '2020(하반기)'].groupby(['ym','jur_stn','vic_sx']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicsex_202 = acs_vicsex_202.reset_index(level=0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicsex_202 = acs_vicsex_202.pivot(index = 'jur_stn', columns = 'vic_sx', values = 'vic_age').fillna(0).reset_index(level= 0)
acs_vicsex_202.columns = ['jur_stn','피해_남','피해_미분류','피해_여']
acs_vicsex_202.head()

   jur_stn   피해_남  피해_미분류   피해_여
0  마산동부경찰서  103.0     0.0   69.0
1  마산중부경찰서  190.0     1.0   58.0
2  서울강남경찰서  823.0     2.0  273.0
3  서울강동경찰서  429.0     1.0  164.0
4  서울강북경찰서  388.0     0.0  126.0

In [241]:
acs_vicsex_181 = add_date(acs_vicsex_181, '2018(상반기)')
acs_vicsex_182 = add_date(acs_vicsex_182, '2018(하반기)')
acs_vicsex_191 = add_date(acs_vicsex_191, '2019(상반기)')
acs_vicsex_192 = add_date(acs_vicsex_192, '2019(하반기)')
acs_vicsex_201 = add_date(acs_vicsex_201, '2020(상반기)')
acs_vicsex_202 = add_date(acs_vicsex_202, '2020(하반기)')

In [245]:
acs_vicsex_final = pd.concat([acs_vicsex_181, acs_vicsex_182,acs_vicsex_191,acs_vicsex_192,acs_vicsex_201,acs_vicsex_202])
acs_vicsex_final

    jur_stn   피해_남  피해_미분류   피해_여       date
0   마산동부경찰서  128.0     1.0   68.0  2018(상반기)
1   마산중부경찰서  154.0     4.0   78.0  2018(상반기)
2   서울강남경찰서  747.0     2.0  221.0  2018(상반기)
3   서울강동경찰서  433.0     4.0  192.0  2018(상반기)
4   서울강북경찰서  447.0     2.0  156.0  2018(상반기)
..      ...    ...     ...    ...        ...
36  수원중부경찰서  487.0     1.0  198.0  2020(하반기)
37    진주경찰서  182.0     0.0  132.0  2020(하반기)
38    진해경찰서  258.0     0.0  136.0  2020(하반기)
39  창원서부경찰서  217.0     0.0   86.0  2020(하반기)
40  창원중부경찰서  190.0     0.0   86.0  2020(하반기)

[246 rows x 5 columns]

#### 피해자 나이

In [246]:
accident.head()

   acc_case ofn_sx ofn_age vic_sx vic_age  jur_stn  year         ym
0  차대차-측면충돌      남     20대      남     50대  서울중부경찰서  2018  2018(상반기)
1  차대차-측면충돌      여     50대      남     70대  서울중부경찰서  2018  2018(상반기)
2  차대차-측면충돌      남     40대      남     50대  서울중부경찰서  2018  2018(상반기)
3    차대차-기타   기타불명     미분류      여     40대  서울중부경찰서  2018  2018(상반기)
4    차대차-기타      남     60대      남     50대  서울중부경찰서  2018  2018(상반기)

In [ ]:
acs_vicsex_181 = accident[accident.ym == '2018(상반기)'].groupby(['ym','jur_stn','vic_sx']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicsex_181 = acs_vicsex_181.reset_index(level=0).drop(['ym'], axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicsex_181 = acs_vicsex_181.pivot(index = 'jur_stn', columns = 'vic_sx', values = 'vic_age').fillna(0).reset_index(level= 0)
acs_vicsex_181.columns = ['jur_stn','피해_남','피해_미분류','피해_여']

In [254]:
acs_vicage_181 = accident[accident.ym == '2018(상반기)'].groupby(['ym','jur_stn','vic_age']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicage_181 = acs_vicage_181.reset_index(level = 0).drop(['ym'],axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicage_181 = acs_vicage_181.pivot(index = 'jur_stn', columns = 'vic_age', values = 'vic_sx').fillna(0).reset_index()
acs_vicage_181.columns = ['jur_stn','피해_10대이하','피해_20대','피해_30대','피해_40대','피해_50대','피해_60대','피해_70대','피해_80대이상','피해_미분류']

acs_vicage_182 = accident[accident.ym == '2018(하반기)'].groupby(['ym','jur_stn','vic_age']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicage_182 = acs_vicage_182.reset_index(level = 0).drop(['ym'],axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicage_182 = acs_vicage_182.pivot(index = 'jur_stn', columns = 'vic_age', values = 'vic_sx').fillna(0).reset_index()
acs_vicage_182.columns = ['jur_stn','피해_10대이하','피해_20대','피해_30대','피해_40대','피해_50대','피해_60대','피해_70대','피해_80대이상','피해_미분류']

acs_vicage_191 = accident[accident.ym == '2019(상반기)'].groupby(['ym','jur_stn','vic_age']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicage_191 = acs_vicage_191.reset_index(level = 0).drop(['ym'],axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicage_191 = acs_vicage_191.pivot(index = 'jur_stn', columns = 'vic_age', values = 'vic_sx').fillna(0).reset_index()
acs_vicage_191.columns = ['jur_stn','피해_10대이하','피해_20대','피해_30대','피해_40대','피해_50대','피해_60대','피해_70대','피해_80대이상','피해_미분류']

acs_vicage_192 = accident[accident.ym == '2019(하반기)'].groupby(['ym','jur_stn','vic_age']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicage_192 = acs_vicage_192.reset_index(level = 0).drop(['ym'],axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicage_192 = acs_vicage_192.pivot(index = 'jur_stn', columns = 'vic_age', values = 'vic_sx').fillna(0).reset_index()
acs_vicage_192.columns = ['jur_stn','피해_10대이하','피해_20대','피해_30대','피해_40대','피해_50대','피해_60대','피해_70대','피해_80대이상','피해_미분류']

acs_vicage_201 = accident[accident.ym == '2020(상반기)'].groupby(['ym','jur_stn','vic_age']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicage_201 = acs_vicage_201.reset_index(level = 0).drop(['ym'],axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicage_201 = acs_vicage_201.pivot(index = 'jur_stn', columns = 'vic_age', values = 'vic_sx').fillna(0).reset_index()
acs_vicage_201.columns = ['jur_stn','피해_10대이하','피해_20대','피해_30대','피해_40대','피해_50대','피해_60대','피해_70대','피해_80대이상','피해_미분류']

acs_vicage_202 = accident[accident.ym == '2020(하반기)'].groupby(['ym','jur_stn','vic_age']).count().drop(['acc_case','ofn_sx','ofn_age','year'],axis = 1)
acs_vicage_202 = acs_vicage_202.reset_index(level = 0).drop(['ym'],axis = 1).reset_index(level = 1).reset_index(level = 0)
acs_vicage_202 = acs_vicage_202.pivot(index = 'jur_stn', columns = 'vic_age', values = 'vic_sx').fillna(0).reset_index()
acs_vicage_202.columns = ['jur_stn','피해_10대이하','피해_20대','피해_30대','피해_40대','피해_50대','피해_60대','피해_70대','피해_80대이상','피해_미분류']
acs_vicage_202.head()

,jur_stn,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류
0,마산동부경찰서,7.0,18.0,30.0,31.0,39.0,27.0,18.0,2.0,0.0
1,마산중부경찰서,9.0,34.0,34.0,42.0,52.0,52.0,17.0,8.0,1.0
2,서울강남경찰서,13.0,249.0,277.0,221.0,169.0,136.0,28.0,3.0,2.0
3,서울강동경찰서,30.0,84.0,105.0,98.0,123.0,102.0,37.0,14.0,1.0
4,서울강북경찰서,24.0,86.0,91.0,81.0,114.0,84.0,26.0,8.0,0.0

In [256]:
acs_vicage_181 = add_date(acs_vicage_181, '2018(상반기)')
acs_vicage_182 = add_date(acs_vicage_182, '2018(하반기)')
acs_vicage_191 = add_date(acs_vicage_191, '2019(상반기)')
acs_vicage_192 = add_date(acs_vicage_192, '2019(하반기)')
acs_vicage_201 = add_date(acs_vicage_201, '2020(상반기)')
acs_vicage_202 = add_date(acs_vicage_202, '2020(하반기)')

In [257]:
acs_vicage_final = pd.concat([acs_vicage_181,acs_vicage_182,acs_vicage_191,acs_vicage_192,acs_vicage_201,acs_vicage_202])
acs_vicage_final

,jur_stn,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,date
0,마산동부경찰서,7.0,24.0,33.0,35.0,40.0,40.0,11.0,6.0,1.0,2018(상반기)
1,마산중부경찰서,7.0,18.0,35.0,47.0,48.0,44.0,25.0,8.0,4.0,2018(상반기)
2,서울강남경찰서,10.0,147.0,248.0,187.0,201.0,137.0,36.0,2.0,2.0,2018(상반기)
3,서울강동경찰서,27.0,83.0,100.0,108.0,138.0,112.0,41.0,16.0,4.0,2018(상반기)
4,서울강북경찰서,30.0,67.0,92.0,107.0,132.0,120.0,41.0,14.0,2.0,2018(상반기)
...,...,...,...,...,...,...,...,...,...,...,...
36,수원중부경찰서,26.0,94.0,123.0,127.0,151.0,100.0,47.0,17.0,1.0,2020(하반기)
37,진주경찰서,25.0,37.0,41.0,39.0,69.0,60.0,33.0,10.0,0.0,2020(하반기)
38,진해경찰서,17.0,41.0,75.0,95.0,82.0,58.0,20.0,6.0,0.0,2020(하반기)
39,창원서부경찰서,7.0,30.0,61.0,62.0,67.0,49.0,16.0,11.0,0.0,2020(하반기)
40,창원중부경찰서,9.0,56.0,56.0,46.0,64.0,31.0,12.0,2.0,0.0,2020(하반기)

In [259]:
acs_car_final = acs_final

In [260]:
csv_download_link(acs_car_final, 'car_acc_df.csv')
acs_car_final

acc_case  jur_stn       date   차대사람    차대차  차량단독
0         마산동부경찰서  2018(상반기)   73.0  124.0   6.0
1         마산중부경찰서  2018(상반기)   75.0  157.0  22.0
2         서울강남경찰서  2018(상반기)  202.0  767.0  16.0
3         서울강동경찰서  2018(상반기)  193.0  435.0  21.0
4         서울강북경찰서  2018(상반기)  200.0  403.0  20.0
..            ...        ...    ...    ...   ...
36        수원중부경찰서  2020(하반기)  159.0  527.0  26.0
37          진주경찰서  2020(하반기)  115.0  199.0  13.0
38          진해경찰서  2020(하반기)   65.0  329.0  18.0
39        창원서부경찰서  2020(하반기)   67.0  236.0   8.0
40        창원중부경찰서  2020(하반기)   76.0  200.0   5.0

[246 rows x 5 columns]

In [267]:
acs_ofnage_final
csv_download_link(acs_ofnage_final, '교통사고_가해자나이.csv')

/opt/app-root/src/교통사고_가해자나이.csv

Press enter to delete the file after you have downloaded it.

In [266]:
acs_ofnsex_final
csv_download_link(acs_ofnsex_final, '교통사고_가해자성별.csv')

/opt/app-root/src/교통사고_가해자성별.csv

Press enter to delete the file after you have downloaded it.

In [268]:
acs_vicage_final
csv_download_link(acs_vicage_final, '교통사고_피해자나이.csv')

/opt/app-root/src/교통사고_피해자나이.csv

Press enter to delete the file after you have downloaded it.

In [269]:
acs_vicsex_final
csv_download_link(acs_vicsex_final, '교통사고_피해자성별.csv')

/opt/app-root/src/교통사고_피해자성별.csv

Press enter to delete the file after you have downloaded it.

In [2]:
import pandas as pd
import os

In [3]:
os.getcwd()

'C:\\Users\\SAMSUNG\\Desktop\\SSAC\\머신러닝\\메인프로젝트'

In [5]:
df = pd.read_csv('./교통사고csv/11번.교통사고_total.csv')
df.head()

,Unnamed: 0,jur_stn,date,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
0,0,마산동부경찰서,2018(상반기),73.0,124.0,6.0,3.0,157.0,43.0,7.0,24.0,33.0,35.0,40.0,40.0,11.0,6.0,1.0,128.0,68.0
1,1,마산중부경찰서,2018(상반기),75.0,157.0,22.0,0.0,195.0,59.0,7.0,18.0,35.0,47.0,48.0,44.0,25.0,8.0,4.0,154.0,78.0
2,2,서울강남경찰서,2018(상반기),202.0,767.0,16.0,19.0,804.0,162.0,10.0,147.0,248.0,187.0,201.0,137.0,36.0,2.0,2.0,747.0,221.0
3,3,서울강동경찰서,2018(상반기),193.0,435.0,21.0,15.0,513.0,121.0,27.0,83.0,100.0,108.0,138.0,112.0,41.0,16.0,4.0,433.0,192.0
4,4,서울강북경찰서,2018(상반기),200.0,403.0,20.0,19.0,514.0,90.0,30.0,67.0,92.0,107.0,132.0,120.0,41.0,14.0,2.0,447.0,156.0

In [8]:
#df.drop(['Unnamed: 0'], axis = 1, inplace = True)
df.head()

,jur_stn,date,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
0,마산동부경찰서,2018(상반기),73.0,124.0,6.0,3.0,157.0,43.0,7.0,24.0,33.0,35.0,40.0,40.0,11.0,6.0,1.0,128.0,68.0
1,마산중부경찰서,2018(상반기),75.0,157.0,22.0,0.0,195.0,59.0,7.0,18.0,35.0,47.0,48.0,44.0,25.0,8.0,4.0,154.0,78.0
2,서울강남경찰서,2018(상반기),202.0,767.0,16.0,19.0,804.0,162.0,10.0,147.0,248.0,187.0,201.0,137.0,36.0,2.0,2.0,747.0,221.0
3,서울강동경찰서,2018(상반기),193.0,435.0,21.0,15.0,513.0,121.0,27.0,83.0,100.0,108.0,138.0,112.0,41.0,16.0,4.0,433.0,192.0
4,서울강북경찰서,2018(상반기),200.0,403.0,20.0,19.0,514.0,90.0,30.0,67.0,92.0,107.0,132.0,120.0,41.0,14.0,2.0,447.0,156.0

In [10]:
df.rename(columns = {'date' : 'year'}, inplace = True)
df.columns

Index(['jur_stn', 'year', '차대사람', '차대차', '차량단독', '가해_성별_기타불명', '가해_남', '가해_여',
       '피해_10대이하', '피해_20대', '피해_30대', '피해_40대', '피해_50대', '피해_60대', '피해_70대',
       '피해_80대이상', '피해_미분류', '피해_남', '피해_여'],
      dtype='object')

In [12]:
df.to_csv('./교통사고csv/11번.교통사고_전처리(수정).csv', index = False)

### 교통사고 17년도 NA값 처리하기

In [15]:
os.getcwd()

'C:\\Users\\SAMSUNG\\Desktop\\SSAC\\머신러닝\\메인프로젝트'

In [2]:
base_df = pd.read_csv('./base_df.csv')
base_df.head()

    jur_stn      year
0   서울중부경찰서  2016(이전)
1   서울종로경찰서  2016(이전)
2  서울남대문경찰서  2016(이전)
3  서울서대문경찰서  2016(이전)
4   서울혜화경찰서  2016(이전)

In [3]:
base_df = base_df[base_df['year'] != '2016(이전)']
base_df.year.unique()

array(['2017(상반기)', '2017(하반기)', '2018(상반기)', '2018(하반기)', '2019(상반기)',
       '2019(하반기)', '2020(상반기)', '2020(하반기)'], dtype=object)

In [86]:
df = pd.read_csv('./교통사고csv/11번.교통사고_전처리_total.csv')
df.head()

,jur_stn,year,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
0,마산동부경찰서,2018(상반기),73.0,124.0,6.0,3.0,157.0,43.0,7.0,24.0,33.0,35.0,40.0,40.0,11.0,6.0,1.0,128.0,68.0
1,마산중부경찰서,2018(상반기),75.0,157.0,22.0,0.0,195.0,59.0,7.0,18.0,35.0,47.0,48.0,44.0,25.0,8.0,4.0,154.0,78.0
2,서울강남경찰서,2018(상반기),202.0,767.0,16.0,19.0,804.0,162.0,10.0,147.0,248.0,187.0,201.0,137.0,36.0,2.0,2.0,747.0,221.0
3,서울강동경찰서,2018(상반기),193.0,435.0,21.0,15.0,513.0,121.0,27.0,83.0,100.0,108.0,138.0,112.0,41.0,16.0,4.0,433.0,192.0
4,서울강북경찰서,2018(상반기),200.0,403.0,20.0,19.0,514.0,90.0,30.0,67.0,92.0,107.0,132.0,120.0,41.0,14.0,2.0,447.0,156.0

In [87]:
df.year.unique()

array(['2018(상반기)', '2018(하반기)', '2019(상반기)', '2019(하반기)', '2020(상반기)',
       '2020(하반기)'], dtype=object)

In [88]:
df.describe()

,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
count,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.00000,235.000000,235.000000
mean,135.604255,412.787234,18.506383,12.957447,449.042553,104.897872,19.382979,83.289362,106.927660,103.042553,111.944681,81.404255,31.740426,9.519149,1.73617,398.808511,148.442553
std,62.035976,222.910520,8.843545,9.524950,223.157715,58.740977,12.013086,48.933337,64.429839,55.888609,54.960992,41.360444,14.866236,5.028408,1.86699,207.990861,72.651962
min,41.000000,116.000000,3.000000,0.000000,134.000000,18.000000,0.000000,15.000000,12.000000,23.000000,28.000000,25.000000,3.000000,0.000000,0.00000,103.000000,35.000000
25%,80.000000,219.500000,12.000000,6.000000,251.500000,60.000000,9.000000,42.500000,55.500000,58.500000,65.500000,48.000000,21.000000,6.000000,0.00000,217.500000,90.000000
50%,131.000000,373.000000,18.000000,10.000000,428.000000,90.000000,17.000000,81.000000,94.000000,93.000000,102.000000,75.000000,30.000000,9.000000,1.00000,371.000000,135.000000
75%,185.500000,543.500000,24.000000,19.000000,596.000000,134.000000,26.500000,109.500000,134.500000,130.500000,150.500000,108.000000,40.000000,12.500000,3.00000,524.500000,197.500000
max,348.000000,1152.000000,55.000000,45.000000,1127.000000,345.000000,60.000000,249.000000,332.000000,270.000000,294.000000,220.000000,86.000000,23.000000,10.00000,1042.000000,397.000000

In [89]:
df_merge = pd.merge(base_df, df, how = 'left', on = ('jur_stn','year')) 
df = df_merge.copy()
df

,jur_stn,year,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
0,서울중부경찰서,2017(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,서울종로경찰서,2017(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,서울남대문경찰서,2017(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울서대문경찰서,2017(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울혜화경찰서,2017(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,창원서부경찰서,2020(하반기),67.0,236.0,8.0,4.0,236.0,71.0,7.0,30.0,61.0,62.0,67.0,49.0,16.0,11.0,0.0,217.0,86.0
324,마산중부경찰서,2020(하반기),64.0,185.0,26.0,1.0,207.0,67.0,9.0,34.0,34.0,42.0,52.0,52.0,17.0,8.0,1.0,190.0,58.0
325,마산동부경찰서,2020(하반기),54.0,118.0,4.0,0.0,134.0,42.0,7.0,18.0,30.0,31.0,39.0,27.0,18.0,2.0,0.0,103.0,69.0
326,진주경찰서,2020(하반기),115.0,199.0,13.0,6.0,235.0,86.0,25.0,37.0,41.0,39.0,69.0,60.0,33.0,10.0,0.0,182.0,132.0
327,진해경찰서,2020(하반기),65.0,329.0,18.0,3.0,295.0,114.0,17.0,41.0,75.0,95.0,82.0,58.0,20.0,6.0,0.0,258.0,136.0

In [90]:
pol_list = df['jur_stn'].unique()
len(pol_list)

41

In [91]:
# 상/하반기 구분
year_list = df['year'].unique()
year_list_up = year_list[::2]
year_list_down = year_list[1::2]

In [92]:
year_list

array(['2017(상반기)', '2017(하반기)', '2018(상반기)', '2018(하반기)', '2019(상반기)',
       '2019(하반기)', '2020(상반기)', '2020(하반기)'], dtype=object)

In [93]:
year_list_up

array(['2017(상반기)', '2018(상반기)', '2019(상반기)', '2020(상반기)'], dtype=object)

In [94]:
year_list_down

array(['2017(하반기)', '2018(하반기)', '2019(하반기)', '2020(하반기)'], dtype=object)

In [95]:
# 상반기
for name in range(len(pol_list)):
    temp = pd.DataFrame()
    for i in range(len(year_list_up)):
        temp = pd.concat([temp, df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list_up[i])]])
    df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list[0])] = temp.fillna(round(temp.mean()))[:1]
    
# 하반기
for name in range(len(pol_list)):
    temp = pd.DataFrame()
    for i in range(len(year_list_down)):
        temp = pd.concat([temp, df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list_down[i])]])
    df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list[1])] = temp.fillna(round(temp.mean()))[:1]

In [14]:
a = 2.2341
round(a)

2

In [96]:
df

,jur_stn,year,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
0,서울중부경찰서,2017(상반기),74.0,190.0,6.0,8.0,220.0,42.0,8.0,34.0,54.0,38.0,58.0,46.0,20.0,5.0,0.0,198.0,65.0
1,서울종로경찰서,2017(상반기),72.0,174.0,9.0,5.0,211.0,39.0,3.0,32.0,53.0,47.0,55.0,35.0,16.0,6.0,1.0,178.0,67.0
2,서울남대문경찰서,2017(상반기),63.0,182.0,10.0,5.0,213.0,37.0,3.0,27.0,49.0,48.0,55.0,45.0,13.0,3.0,1.0,192.0,52.0
3,서울서대문경찰서,2017(상반기),127.0,329.0,20.0,9.0,390.0,78.0,17.0,76.0,73.0,83.0,95.0,73.0,28.0,10.0,1.0,339.0,116.0
4,서울혜화경찰서,2017(상반기),68.0,180.0,11.0,9.0,216.0,33.0,3.0,35.0,45.0,39.0,56.0,43.0,21.0,5.0,3.0,190.0,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,창원서부경찰서,2020(하반기),67.0,236.0,8.0,4.0,236.0,71.0,7.0,30.0,61.0,62.0,67.0,49.0,16.0,11.0,0.0,217.0,86.0
324,마산중부경찰서,2020(하반기),64.0,185.0,26.0,1.0,207.0,67.0,9.0,34.0,34.0,42.0,52.0,52.0,17.0,8.0,1.0,190.0,58.0
325,마산동부경찰서,2020(하반기),54.0,118.0,4.0,0.0,134.0,42.0,7.0,18.0,30.0,31.0,39.0,27.0,18.0,2.0,0.0,103.0,69.0
326,진주경찰서,2020(하반기),115.0,199.0,13.0,6.0,235.0,86.0,25.0,37.0,41.0,39.0,69.0,60.0,33.0,10.0,0.0,182.0,132.0
327,진해경찰서,2020(하반기),65.0,329.0,18.0,3.0,295.0,114.0,17.0,41.0,75.0,95.0,82.0,58.0,20.0,6.0,0.0,258.0,136.0

#### 결측치가 18-19년도 사이에 11개 존재

In [24]:
df[df.year == '2018(상반기)']
# 서울중부, 동대문, 중랑, 관악이 NA 18년도 상반기
# 동대문, 관악 2018 하반기
# 양천,관악,영등포 19년도 상반기
# 성동, 관악 19 하반기

,jur_stn,year,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
82,서울중부경찰서,2018(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,서울종로경찰서,2018(상반기),90.0,197.0,8.0,5.0,252.0,38.0,4.0,32.0,62.0,60.0,62.0,44.0,17.0,4.0,3.0,204.0,81.0
84,서울남대문경찰서,2018(상반기),80.0,202.0,9.0,5.0,246.0,40.0,3.0,24.0,67.0,53.0,57.0,56.0,16.0,5.0,1.0,220.0,61.0
85,서울서대문경찰서,2018(상반기),145.0,310.0,25.0,5.0,402.0,73.0,17.0,78.0,64.0,82.0,102.0,69.0,29.0,11.0,4.0,333.0,119.0
86,서울혜화경찰서,2018(상반기),79.0,183.0,16.0,9.0,237.0,32.0,4.0,27.0,50.0,44.0,61.0,44.0,23.0,7.0,8.0,202.0,58.0
87,서울용산경찰서,2018(상반기),146.0,494.0,30.0,26.0,563.0,81.0,14.0,100.0,145.0,127.0,137.0,75.0,35.0,7.0,2.0,477.0,163.0
88,서울성북경찰서,2018(상반기),119.0,305.0,13.0,8.0,356.0,73.0,16.0,59.0,76.0,82.0,89.0,69.0,26.0,7.0,4.0,302.0,122.0
89,서울동대문경찰서,2018(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,서울마포경찰서,2018(상반기),221.0,602.0,33.0,23.0,726.0,107.0,35.0,164.0,162.0,144.0,155.0,121.0,36.0,5.0,3.0,602.0,220.0
91,서울영등포경찰서,2018(상반기),273.0,907.0,29.0,45.0,986.0,178.0,26.0,165.0,204.0,262.0,260.0,181.0,60.0,16.0,9.0,888.0,286.0
92,서울성동경찰서,2018(상반기),127.0,401.0,27.0,20.0,487.0,48.0,25.0,86.0,91.0,103.0,106.0,75.0,33.0,8.0,5.0,410.0,117.0
93,서울동작경찰서,2018(상반기),215.0,424.0,23.0,10.0,528.0,124.0,22.0,106.0,112.0,118.0,134.0,93.0,35.0,19.0,5.0,460.0,179.0
94,서울광진경찰서,2018(상반기),128.0,413.0,21.0,19.0,471.0,72.0,24.0,87.0,94.0,96.0,121.0,84.0,28.0,4.0,6.0,415.0,123.0
95,서울서부경찰서,2018(상반기),69.0,125.0,6.0,7.0,167.0,26.0,10.0,15.0,38.0,35.0,42.0,26.0,19.0,9.0,1.0,129.0,65.0
96,서울강북경찰서,2018(상반기),200.0,403.0,20.0,19.0,514.0,90.0,30.0,67.0,92.0,107.0,132.0,120.0,41.0,14.0,2.0,447.0,156.0
97,서울금천경찰서,2018(상반기),156.0,345.0,22.0,8.0,437.0,78.0,23.0,81.0,97.0,82.0,105.0,75.0,26.0,11.0,4.0,379.0,121.0
98,서울중랑경찰서,2018(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,서울강남경찰서,2018(상반기),202.0,767.0,16.0,19.0,804.0,162.0,10.0,147.0,248.0,187.0,201.0,137.0,36.0,2.0,2.0,747.0,221.0
100,서울관악경찰서,2018(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,서울강서경찰서,2018(상반기),191.0,509.0,37.0,14.0,618.0,105.0,22.0,98.0,137.0,135.0,153.0,106.0,35.0,12.0,5.0,498.0,200.0
102,서울강동경찰서,2018(상반기),193.0,435.0,21.0,15.0,513.0,121.0,27.0,83.0,100.0,108.0,138.0,112.0,41.0,16.0,4.0,433.0,192.0
103,서울종암경찰서,2018(상반기),76.0,210.0,18.0,6.0,266.0,32.0,7.0,42.0,48.0,51.0,62.0,44.0,24.0,7.0,1.0,216.0,69.0
104,서울구로경찰서,2018(상반기),183.0,510.0,34.0,11.0,618.0,98.0,30.0,88.0,134.0,116.0,141.0,121.0,44.0,18.0,4.0,527.0,165.0
105,서울서초경찰서,2018(상반기),185.0,702.0,18.0,25.0,696.0,184.0,17.0,116.0,219.0,195.0,180.0,115.0,41.0,2.0,4.0,627.0,258.0
106,서울양천경찰서,2018(상반기),198.0,506.0,23.0,25.0,578.0,124.0,33.0,82.0,101.0,124.0,177.0,133.0,41.0,11.0,3.0,480.0,222.0
107,서울송파경찰서,2018(상반기),348.0,1006.0,50.0,40.0,1119.0,245.0,46.0,176.0,299.0,270.0,276.0,191.0,76.0,15.0,10.0,974.0,375.0
108,서울노원경찰서,2018(상반기),221.0,543.0,22.0,16.0,603.0,167.0,32.0,90.0,117.0,148.0,170.0,131.0,58.0,16.0,4.0,533.0,229.0
109,서울방배경찰서,2018(상반기),72.0,196.0,11.0,7.0,220.0,52.0,8.0,37.0,54.0,54.0,56.0,36.0,19.0,4.0,0.0,203.0,65.0
110,서울은평경찰서,2018(상반기),122.0,179.0,17.0,24.0,251.0,43.0,18.0,39.0,39.0,47.0,75.0,47.0,24.0,11.0,1.0,205.0,95.0
111,서울도봉경찰서,2018(상반기),140.0,254.0,16.0,8.0,329.0,73.0,24.0,43.0,51.0,63.0,99.0,74.0,31.0,9.0,2.0,275.0,119.0
112,서울수서경찰서,2018(상반기),186.0,546.0,18.0,20.0,561.0,169.0,21.0,99.0,166.0,137.0,152.0,114.0,32.0,10.0,1.0,518.0,213.0
113,수원중부경찰서,2018(상반기),232.0,644.0,36.0,17.0,681.0,214.0,37.0,108.0,150.0,197.0,205.0,113.0,46.0,19.0,3.0,591.0,284.0
114,수원남부경찰서,2018(상반기),212.0,676.0,21.0,33.0,679.0,197.0,39.0,167.0,187.0,203.0,164.0,88.0,27.0,12.0,2.0,656.0,231.0
115,수원서부경찰서,2018(상반기),132.0,534.0,8.0,12.0,499.0,163.0,45.0,93.0,140.0,120.0,150.0,79.0,29.0,10.0,0.0,500.0,166.0
116,세종경찰서,2018(상반기),68.0,348.0,28.0,5.0,328.0,111.0,18.0,55.0,93.0,91.0,81.0,43.0,24.0,11.0,6.0,275.0,141.0
117,창원중부경찰서,2018(상반기),94.0,238.0,6.0,4.0,264.0,70.0,15.0,56.0,53.0,72.0,77.0,43.0,15.0,1.0,2.0,218.0,114.0
118,창원서부경찰서,2018(상반기),77.0,266.0,11.0,7.0,264.0,83.0,8.0,44.0,51.0,67.0,91.0,47.0,23.0,7.0,5.0,233.0,105.0
119,마산중부경찰서,2018(상반기),75.0,157.0,22.0,0.0,195.0,59.0,7.0,18.0,35.0,47.0,48.0,44.0,25.0,8.0,4.0,154.0,78.0
120,마산동부경찰서,2018(상반기),73.0,124.0,6.0,3.0,157.0,43.0,7.0,24.0,33.0,35.0,40.0,40.0,11.0,6.0,1.0,128.0,68.0
121,진주경찰서,2018(상반기),131.0,239.0,16.0,2.0,294.0,90.0,17.0,39.0,55.0,65.0,85.0,53.0,38.0,18.0,4.0,248.0,122.0
122,진해경찰서,2018(상반기),47.0,182.0,10.0,3.0,175.0,61.0,9.0,26.0,42.0,54.0,45.0,36.0,12.0,5.0,1.0,170.0,59.0

In [96]:
os.getcwd()

'C:\\Users\\SAMSUNG\\Desktop\\SSAC\\머신러닝\\메인프로젝트'

In [98]:
df.to_csv('./교통사고csv/11번.교통사고_total.csv', index = False)

In [97]:
df.isnull().sum()

jur_stn        0
year           0
차대사람          11
차대차           11
차량단독          11
가해_성별_기타불명    11
가해_남          11
가해_여          11
피해_10대이하      11
피해_20대        11
피해_30대        11
피해_40대        11
피해_50대        11
피해_60대        11
피해_70대        11
피해_80대이상      11
피해_미분류        11
피해_남          11
피해_여          11
dtype: int64

## 남은 결측치 처리

###### 결측치가 2018에 존재하는 듯

#### 해당 연도의 경찰서별로 뽑기

```
# 서울중부, 동대문, 중랑, 관악이 NA 18년도 상반기
# 동대문, 관악 2018 하반기
# 양천,관악,영등포 19년도 상반기
# 성동, 관악 19 하반기
```

In [128]:
temp=pd.DataFrame()
for i in range(len(year_list_down)):
    temp = pd.concat([temp, df[(df['jur_stn'] == '서울관악경찰서') & (df['year'] == year_list_down[i])]])
temp

,jur_stn,year,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
59,서울관악경찰서,2017(하반기),185.0,591.0,18.0,4.0,656.0,134.0,22.0,156.0,150.0,119.0,141.0,129.0,50.0,8.0,1.0,611.0,164.0
141,서울관악경찰서,2018(하반기),185.0,591.0,18.0,4.0,656.0,134.0,22.0,156.0,150.0,119.0,141.0,129.0,50.0,8.0,1.0,611.0,164.0
223,서울관악경찰서,2019(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,서울관악경찰서,2020(하반기),185.0,591.0,18.0,4.0,656.0,134.0,22.0,156.0,150.0,119.0,141.0,129.0,50.0,8.0,1.0,611.0,164.0

In [132]:
# NA값을 해당 경찰서별 상/하반기 평균값으로 넣어주기
df[(df['jur_stn'] == '서울관악경찰서') & (df['year'] == year_list[5])] = temp.fillna(round(temp.mean()))[2:3]

In [100]:
year_list

array(['2017(상반기)', '2017(하반기)', '2018(상반기)', '2018(하반기)', '2019(상반기)',
       '2019(하반기)', '2020(상반기)', '2020(하반기)'], dtype=object)

In [130]:
df[df.jur_stn == '서울관악경찰서']

,jur_stn,year,차대사람,차대차,차량단독,가해_성별_기타불명,가해_남,가해_여,피해_10대이하,피해_20대,피해_30대,피해_40대,피해_50대,피해_60대,피해_70대,피해_80대이상,피해_미분류,피해_남,피해_여
18,서울관악경찰서,2017(상반기),150.0,503.0,12.0,4.0,567.0,94.0,16.0,126.0,154.0,101.0,125.0,91.0,31.0,9.0,0.0,483.0,170.0
59,서울관악경찰서,2017(하반기),185.0,591.0,18.0,4.0,656.0,134.0,22.0,156.0,150.0,119.0,141.0,129.0,50.0,8.0,1.0,611.0,164.0
100,서울관악경찰서,2018(상반기),150.0,503.0,12.0,4.0,567.0,94.0,16.0,126.0,154.0,101.0,125.0,91.0,31.0,9.0,0.0,483.0,170.0
141,서울관악경찰서,2018(하반기),185.0,591.0,18.0,4.0,656.0,134.0,22.0,156.0,150.0,119.0,141.0,129.0,50.0,8.0,1.0,611.0,164.0
182,서울관악경찰서,2019(상반기),150.0,503.0,12.0,4.0,567.0,94.0,16.0,126.0,154.0,101.0,125.0,91.0,31.0,9.0,0.0,483.0,170.0
223,서울관악경찰서,2019(하반기),185.0,591.0,18.0,4.0,656.0,134.0,22.0,156.0,150.0,119.0,141.0,129.0,50.0,8.0,1.0,611.0,164.0
264,서울관악경찰서,2020(상반기),150.0,503.0,12.0,4.0,567.0,94.0,16.0,126.0,154.0,101.0,125.0,91.0,31.0,9.0,0.0,483.0,170.0
305,서울관악경찰서,2020(하반기),185.0,591.0,18.0,4.0,656.0,134.0,22.0,156.0,150.0,119.0,141.0,129.0,50.0,8.0,1.0,611.0,164.0

In [128]:
# 상반기
for name in range(len(pol_list)):
    temp = pd.DataFrame()
    for i in range(len(year_list_up)):
        temp = pd.concat([temp, df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list_up[i])]])
    df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list[2])] = temp.fillna(round(temp.mean()))[1:2]
    
# 하반기
for name in range(len(pol_list)):
    temp = pd.DataFrame()
    for i in range(len(year_list_down)):
        temp = pd.concat([temp, df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list_down[i])]])
    df[(df['jur_stn'] == pol_list[name]) & (df['year'] == year_list[3])] = temp.fillna(round(temp.mean()))[1:2]

In [133]:
# NA 값 처리
df.isnull().sum()

jur_stn       0
year          0
차대사람          0
차대차           0
차량단독          0
가해_성별_기타불명    0
가해_남          0
가해_여          0
피해_10대이하      0
피해_20대        0
피해_30대        0
피해_40대        0
피해_50대        0
피해_60대        0
피해_70대        0
피해_80대이상      0
피해_미분류        0
피해_남          0
피해_여          0
dtype: int64

In [134]:
os.getcwd()

'C:\\Users\\SAMSUNG\\Desktop\\SSAC\\머신러닝\\메인프로젝트'

In [135]:
df.to_csv('./교통사고csv/11번.교통사고_total.csv', index = False)