In [175]:
# 경찰서별 담당 행정구역
sgg_nm_transfer = {
    '마산동부경찰서' : '창원시마산회원구'  ,
    '마산중부경찰서' : '창원시마산합포구'  ,
    '서울강남경찰서' : '강남구'  , 
    '서울강동경찰서' : '강동구' , 
    '서울강북경찰서' :'강북구'  , 
    '서울강서경찰서' :  '강서구',
    '서울관악경찰서' : '관악구' ,
      '서울광진경찰서' : '광진구', 
     '서울구로경찰서' : '구로구' , 
     '서울금천경찰서' : '금천구' , 
    '서울남대문경찰서' : '중구' , 
    '서울노원경찰서' : '노원구' ,
    '서울도봉경찰서' : '도봉구'  , 
    '서울동대문경찰서' : '동대문구'  , 
    '서울동작경찰서' : '동작구'  , 
    '서울마포경찰서' : '마포구' , 
    '서울방배경찰서' : '서초구', 
    '서울서대문경찰서' : '서대문구' ,
    '서울서부경찰서' : '은평구' , 
    '서울서초경찰서' : '서초구' , 
    '서울성동경찰서' : '성동구' , 
    '서울성북경찰서' :'성북구' , 
    '서울송파경찰서' :'송파구' , 
    '서울수서경찰서' : '강남구' ,
     '서울양천경찰서': '양천구'  , 
    '서울영등포경찰서' : '영등포구' , 
    '서울용산경찰서': '용산구'  , 
    '서울은평경찰서' : '은평구' , 
    '서울종로경찰서': '종로구', 
    '서울종암경찰서' : '성북구'  ,
     '서울중랑경찰서' : '중랑구'   , 
    '서울중부경찰서' : '중구'  , 
    '서울혜화경찰서': '종로구'  , 
    '세종경찰서' : '세종시'  , 
    '수원남부경찰서': '수원시영통구'  ,
   '수원서부경찰서' : '수원시팔달구'  ,  
    '수원중부경찰서' :'수원시장안구'   , 
    '진주경찰서' : '진주시'  ,
    '진해경찰서' : '창원시진해구'  , 
    '창원서부경찰서' : '창원시의창구' , 
    '창원중부경찰서': '창원시성산구'
    
}

### 성비

In [176]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [177]:
df_b = pd.read_csv('base_df.csv')

In [178]:
df = pd.read_csv('14.5개시도_성연령별_총인구분포.csv')

In [179]:
df_b['sgg_nm'] = df_b['jur_stn'].apply(lambda x : sgg_nm_transfer[x])
df_b

      jur_stn       year    sgg_nm
0     서울중부경찰서   2016(이전)        중구
1     서울종로경찰서   2016(이전)       종로구
2    서울남대문경찰서   2016(이전)        중구
3    서울서대문경찰서   2016(이전)      서대문구
4     서울혜화경찰서   2016(이전)       종로구
..        ...        ...       ...
364   창원서부경찰서  2020(하반기)    창원시의창구
365   마산중부경찰서  2020(하반기)  창원시마산합포구
366   마산동부경찰서  2020(하반기)  창원시마산회원구
367     진주경찰서  2020(하반기)       진주시
368     진해경찰서  2020(하반기)    창원시진해구

[369 rows x 3 columns]

In [180]:
df_b['date'] = df_b['year'].apply(lambda x : int(x[:4]))
df_b

      jur_stn       year    sgg_nm  date
0     서울중부경찰서   2016(이전)        중구  2016
1     서울종로경찰서   2016(이전)       종로구  2016
2    서울남대문경찰서   2016(이전)        중구  2016
3    서울서대문경찰서   2016(이전)      서대문구  2016
4     서울혜화경찰서   2016(이전)       종로구  2016
..        ...        ...       ...   ...
364   창원서부경찰서  2020(하반기)    창원시의창구  2020
365   마산중부경찰서  2020(하반기)  창원시마산합포구  2020
366   마산동부경찰서  2020(하반기)  창원시마산회원구  2020
367     진주경찰서  2020(하반기)       진주시  2020
368     진해경찰서  2020(하반기)    창원시진해구  2020

[369 rows x 4 columns]

In [181]:
df.drop(columns = ['sido'], inplace = True)

In [182]:
df

,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate
0,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3
1,종로구,0~4세,2017,4137,2099,2038,103.0,4011,2039,1972,103.4
2,종로구,0세,2017,694,336,358,93.9,675,327,348,94.0
3,종로구,1세,2017,836,429,407,105.4,805,412,393,104.8
4,종로구,2세,2017,878,459,419,109.5,850,447,403,110.9
...,...,...,...,...,...,...,...,...,...,...,...
13819,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0
13820,중구,15~64세,2017,97649,48332,49317,98.0,88374,44025,44349,99.3
13821,중구,65세이상,2017,19212,8259,10953,75.4,18692,8032,10660,75.3
13822,중구,평균연령,2017,42.8,42.1,43.5,NaN,43.2,42.4,43.9,NaN
13823,중구,중위연령,2017,42.6,41.9,43.3,NaN,43.2,42.4,43.9,NaN

In [183]:
df_n = df[df['age'].isin(['합계', '15세미만','15~19세', '20~24세', '25~29세', '30~34세','35~39세', '40~44세', '45~49세'
                             , '50~54세', '55~59세', '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85세이상'])]
df_n

,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate
0,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3
19,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8
25,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8
31,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2
37,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1
...,...,...,...,...,...,...,...,...,...,...,...
13781,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3
13787,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0
13793,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0
13799,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7
13819,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0

In [184]:
df_n = df_n.astype({'popu_num' : 'int'})
df_n = df_n.astype({'local_num' : 'int'})
df_n = df_n.astype({'popu_male_num' : 'int'})
df_n = df_n.astype({'popu_female_num' : 'int'})
df_n = df_n.astype({'local_male_num' : 'int'})
df_n = df_n.astype({'local_female_num' : 'int'})

In [185]:
df_n['for'] = df_n['popu_num'] - df_n['local_num']
df_n['for_male_num'] = df_n['popu_male_num'] - df_n['local_male_num']
df_n['for_female_num'] = df_n['popu_female_num'] - df_n['local_female_num']

In [186]:
df_n['for_sx_rate'] = round(df_n['for_male_num'] / df_n['for_female_num'] * 100, 1)

In [187]:
df_n

,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,for,for_male_num,for_female_num,for_sx_rate
0,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3,10979,4913,6066,81.0
19,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8,840,307,533,57.6
25,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8,2757,940,1817,51.7
31,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2,1404,637,767,83.1
37,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1,1096,561,535,104.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13781,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3,98,50,48,104.2
13787,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0,61,25,36,69.4
13793,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0,33,9,24,37.5
13799,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7,20,5,15,33.3
13819,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0,470,270,200,135.0

In [188]:
df_nn = pd.merge(df_b, df_n, on = ['sgg_nm', 'date'])
df_nn

,jur_stn,year,sgg_nm,date,age,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,for,for_male_num,for_female_num,for_sx_rate
0,서울중부경찰서,2017(상반기),중구,2017,합계,127896,62195,65701,94.7,117631,57391,60240,95.3,10265,4804,5461,88.0
1,서울중부경찰서,2017(상반기),중구,2017,15~19세,5739,2574,3165,81.3,5316,2415,2901,83.2,423,159,264,60.2
2,서울중부경찰서,2017(상반기),중구,2017,20~24세,10343,4813,5530,87.0,8861,4269,4592,93.0,1482,544,938,58.0
3,서울중부경찰서,2017(상반기),중구,2017,25~29세,11113,5609,5504,101.9,9743,4956,4787,103.5,1370,653,717,91.1
4,서울중부경찰서,2017(상반기),중구,2017,30~34세,10666,5373,5293,101.5,9548,4779,4769,100.2,1118,594,524,113.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,70~74세,6314,2970,3344,88.8,6287,2958,3329,88.9,27,12,15,80.0
4178,진해경찰서,2019(하반기),창원시진해구,2019,75~79세,4943,2071,2872,72.1,4927,2066,2861,72.2,16,5,11,45.5
4179,진해경찰서,2019(하반기),창원시진해구,2019,80~84세,3297,1205,2092,57.6,3288,1201,2087,57.5,9,4,5,80.0
4180,진해경찰서,2019(하반기),창원시진해구,2019,85세이상,2146,538,1608,33.5,2139,537,1602,33.5,7,1,6,16.7
4181,진해경찰서,2019(하반기),창원시진해구,2019,15세미만,31522,16267,15255,106.6,31357,16185,15172,106.7,165,82,83,98.8

In [189]:
df_bb = df_nn[['jur_stn', 'year', 'sgg_nm', 'date']]
df_bb

      jur_stn       year  sgg_nm  date
0     서울중부경찰서  2017(상반기)      중구  2017
1     서울중부경찰서  2017(상반기)      중구  2017
2     서울중부경찰서  2017(상반기)      중구  2017
3     서울중부경찰서  2017(상반기)      중구  2017
4     서울중부경찰서  2017(상반기)      중구  2017
...       ...        ...     ...   ...
4177    진해경찰서  2019(하반기)  창원시진해구  2019
4178    진해경찰서  2019(하반기)  창원시진해구  2019
4179    진해경찰서  2019(하반기)  창원시진해구  2019
4180    진해경찰서  2019(하반기)  창원시진해구  2019
4181    진해경찰서  2019(하반기)  창원시진해구  2019

[4182 rows x 4 columns]

In [190]:
for i in df_nn['age'].unique() :
    df_bb['popu_'+i] = 0

<ipython-input-190-6905af3922f4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bb['popu_'+i] = 0

In [191]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4178,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4179,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4180,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4181,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [192]:
for i in range(len(df_nn)) :
    bb_nm = df_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df_nn['jur_stn'].iloc[i])&(df_bb['date']==df_nn['date'].iloc[i])]
    bb[bb_nm] = df_nn['popu_num'].iloc[i]
    df_bb['popu_' + bb_nm].iloc[bb.index] = df_nn['popu_num'].iloc[i]
df_nnn = df_bb
df_nnn

<ipython-input-192-37003f0f8ee8>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df_nn['popu_num'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522

In [193]:
df_nnn

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522

In [194]:
for i in df_nn['age'].unique() :
    df_bb['for_'+i] = 0

In [195]:
for i in range(len(df_nn)) :
    bb_nm = df_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df_nn['jur_stn'].iloc[i])&(df_bb['date']==df_nn['date'].iloc[i])]
    bb[bb_nm] = df_nn['for'].iloc[i]
    df_bb['for_' + bb_nm].iloc[bb.index] = df_nn['for'].iloc[i]
df_nnn = df_bb
df_nnn

<ipython-input-195-c6f6053e539d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df_nn['for'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [196]:
df_nnn

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [197]:
for i in df_nn['age'].unique() :
    df_bb['popu_female_'+i] = 0

In [198]:
for i in range(len(df_nn)) :
    bb_nm = df_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df_nn['jur_stn'].iloc[i])&(df_bb['date']==df_nn['date'].iloc[i])]
    bb[bb_nm] = df_nn['popu_female_num'].iloc[i]
    df_bb['popu_female_' + bb_nm].iloc[bb.index] = df_nn['popu_female_num'].iloc[i]
df_nnn = df_bb
df_nnn

<ipython-input-198-664c353e8947>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df_nn['popu_female_num'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_female_45~49세,popu_female_50~54세,popu_female_55~59세,popu_female_60~64세,popu_female_65~69세,popu_female_70~74세,popu_female_75~79세,popu_female_80~84세,popu_female_85세이상,popu_female_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,5121,5063,5546,4590,3287,2696,2407,1492,1071,5431
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,5121,5063,5546,4590,3287,2696,2407,1492,1071,5431
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,5121,5063,5546,4590,3287,2696,2407,1492,1071,5431
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,5121,5063,5546,4590,3287,2696,2407,1492,1071,5431
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,5121,5063,5546,4590,3287,2696,2407,1492,1071,5431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7987,6745,7138,6613,4444,3344,2872,2092,1608,15255
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7987,6745,7138,6613,4444,3344,2872,2092,1608,15255
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7987,6745,7138,6613,4444,3344,2872,2092,1608,15255
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7987,6745,7138,6613,4444,3344,2872,2092,1608,15255
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7987,6745,7138,6613,4444,3344,2872,2092,1608,15255

In [199]:
for i in df_nn['age'].unique() :
    df_bb['for_female_'+i] = 0

In [200]:
for i in range(len(df_nn)) :
    bb_nm = df_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df_nn['jur_stn'].iloc[i])&(df_bb['date']==df_nn['date'].iloc[i])]
    bb[bb_nm] = df_nn['for_female_num'].iloc[i]
    df_bb['for_female_' + bb_nm].iloc[bb.index] = df_nn['for_female_num'].iloc[i]
df_nnn = df_bb
df_nnn

<ipython-input-200-4351322ea37e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df_nn['for_female_num'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_female_45~49세,for_female_50~54세,for_female_55~59세,for_female_60~64세,for_female_65~69세,for_female_70~74세,for_female_75~79세,for_female_80~84세,for_female_85세이상,for_female_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,190,155,120,80,37,15,11,5,6,83
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,190,155,120,80,37,15,11,5,6,83
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,190,155,120,80,37,15,11,5,6,83
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,190,155,120,80,37,15,11,5,6,83
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,190,155,120,80,37,15,11,5,6,83

In [201]:
df_nnn.drop_duplicates(inplace=True)
df_nnn

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_female_45~49세,for_female_50~54세,for_female_55~59세,for_female_60~64세,for_female_65~69세,for_female_70~74세,for_female_75~79세,for_female_80~84세,for_female_85세이상,for_female_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,440,505,462,386,170,48,36,24,15,200
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,378,402,349,287,123,51,34,15,10,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,98,95,83,48,31,11,7,6,1,23
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,182,163,126,70,40,7,5,4,3,58
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,182,163,126,70,40,7,5,4,3,58
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,190,155,120,80,37,15,11,5,6,83
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,190,155,120,80,37,15,11,5,6,83

In [202]:
df_nnn['year'].value_counts()

2017(상반기)    41
2017(하반기)    41
2018(상반기)    41
2018(하반기)    41
2019(상반기)    41
2019(하반기)    41
Name: year, dtype: int64

In [203]:
df_nnn['popu_u20'] = df_nnn['popu_15세미만'] + df_nnn['popu_15~19세']
df_nnn['popu_2030'] = df_nnn['popu_20~24세'] + df_nnn['popu_25~29세'] + df_nnn['popu_30~34세'] + df_nnn['popu_35~39세']
df_nnn['popu_4050'] = df_nnn['popu_40~44세'] + df_nnn['popu_45~49세'] + df_nnn['popu_50~54세'] + df_nnn['popu_55~59세']

In [204]:
df_nnn['popu_o60'] = df_nnn['popu_합계'] - df_nnn['popu_u20'] - df_nnn['popu_2030'] - df_nnn['popu_4050']

In [205]:
df_nnn['popu_female_u20'] = df_nnn['popu_female_15세미만'] + df_nnn['popu_female_15~19세']
df_nnn['popu_female_2030'] = df_nnn['popu_female_20~24세'] + df_nnn['popu_female_25~29세'] + df_nnn['popu_female_30~34세'] + df_nnn['popu_female_35~39세']
df_nnn['popu_female_4050'] = df_nnn['popu_female_40~44세'] + df_nnn['popu_female_45~49세'] + df_nnn['popu_female_50~54세'] + df_nnn['popu_female_55~59세']

In [206]:
df_nnn['popu_female_o60'] = df_nnn['popu_female_합계'] - df_nnn['popu_female_u20'] - df_nnn['popu_female_2030'] - df_nnn['popu_female_4050']

In [207]:
df_nnn['for_u20'] = df_nnn['for_15세미만'] + df_nnn['for_15~19세']
df_nnn['for_2030'] = df_nnn['for_20~24세'] + df_nnn['for_25~29세'] + df_nnn['for_30~34세'] + df_nnn['for_35~39세']
df_nnn['for_4050'] = df_nnn['for_40~44세'] + df_nnn['for_45~49세'] + df_nnn['for_50~54세'] + df_nnn['for_55~59세']

In [208]:
df_nnn['for_o60'] = df_nnn['for_합계'] - df_nnn['for_u20'] - df_nnn['for_2030'] - df_nnn['for_4050']

In [209]:
df_nnn['for_female_u20'] = df_nnn['for_female_15세미만'] + df_nnn['for_female_15~19세']
df_nnn['for_female_2030'] = df_nnn['for_female_20~24세'] + df_nnn['for_female_25~29세'] + df_nnn['for_female_30~34세'] + df_nnn['for_female_35~39세']
df_nnn['for_female_4050'] = df_nnn['for_female_40~44세'] + df_nnn['for_female_45~49세'] + df_nnn['for_female_50~54세'] + df_nnn['for_female_55~59세']

In [210]:
df_nnn['for_female_o60'] = df_nnn['for_female_합계'] - df_nnn['for_female_u20'] - df_nnn['for_female_2030'] - df_nnn['for_female_4050']

In [211]:
df_nnn.columns

Index(['jur_stn', 'year', 'sgg_nm', 'date', 'popu_합계', 'popu_15~19세',
       'popu_20~24세', 'popu_25~29세', 'popu_30~34세', 'popu_35~39세',
       'popu_40~44세', 'popu_45~49세', 'popu_50~54세', 'popu_55~59세',
       'popu_60~64세', 'popu_65~69세', 'popu_70~74세', 'popu_75~79세',
       'popu_80~84세', 'popu_85세이상', 'popu_15세미만', 'for_합계', 'for_15~19세',
       'for_20~24세', 'for_25~29세', 'for_30~34세', 'for_35~39세', 'for_40~44세',
       'for_45~49세', 'for_50~54세', 'for_55~59세', 'for_60~64세', 'for_65~69세',
       'for_70~74세', 'for_75~79세', 'for_80~84세', 'for_85세이상', 'for_15세미만',
       'popu_female_합계', 'popu_female_15~19세', 'popu_female_20~24세',
       'popu_female_25~29세', 'popu_female_30~34세', 'popu_female_35~39세',
       'popu_female_40~44세', 'popu_female_45~49세', 'popu_female_50~54세',
       'popu_female_55~59세', 'popu_female_60~64세', 'popu_female_65~69세',
       'popu_female_70~74세', 'popu_female_75~79세', 'popu_female_80~84세',
       'popu_female_85세이상', 'popu_female_15세미만', 'for_female_합계',
       'for_female_15~19세', 'for_female_20~24세', 'for_female_25~29세',
       'for_female_30~34세', 'for_female_35~39세', 'for_female_40~44세',
       'for_female_45~49세', 'for_female_50~54세', 'for_female_55~59세',
       'for_female_60~64세', 'for_female_65~69세', 'for_female_70~74세',
       'for_female_75~79세', 'for_female_80~84세', 'for_female_85세이상',
       'for_female_15세미만', 'popu_u20', 'popu_2030', 'popu_4050', 'popu_o60',
       'popu_female_u20', 'popu_female_2030', 'popu_female_4050',
       'popu_female_o60', 'for_u20', 'for_2030', 'for_4050', 'for_o60',
       'for_female_u20', 'for_female_2030', 'for_female_4050',
       'for_female_o60'],
      dtype='object')

In [212]:
df_nnn.drop(columns = ['sgg_nm', 'date', 'popu_15~19세',
       'popu_20~24세', 'popu_25~29세', 'popu_30~34세', 'popu_35~39세',
       'popu_40~44세', 'popu_45~49세', 'popu_50~54세', 'popu_55~59세',
       'popu_60~64세', 'popu_65~69세', 'popu_70~74세', 'popu_75~79세',
       'popu_80~84세', 'popu_85세이상', 'popu_15세미만', 'for_15~19세',
       'for_20~24세', 'for_25~29세', 'for_30~34세', 'for_35~39세', 'for_40~44세',
       'for_45~49세', 'for_50~54세', 'for_55~59세', 'for_60~64세', 'for_65~69세',
       'for_70~74세', 'for_75~79세', 'for_80~84세', 'for_85세이상', 'for_15세미만',
       'popu_female_15~19세', 'popu_female_20~24세',
       'popu_female_25~29세', 'popu_female_30~34세', 'popu_female_35~39세',
       'popu_female_40~44세', 'popu_female_45~49세', 'popu_female_50~54세',
       'popu_female_55~59세', 'popu_female_60~64세', 'popu_female_65~69세',
       'popu_female_70~74세', 'popu_female_75~79세', 'popu_female_80~84세',
       'popu_female_85세이상', 'popu_female_15세미만',
       'for_female_15~19세', 'for_female_20~24세', 'for_female_25~29세',
       'for_female_30~34세', 'for_female_35~39세', 'for_female_40~44세',
       'for_female_45~49세', 'for_female_50~54세', 'for_female_55~59세',
       'for_female_60~64세', 'for_female_65~69세', 'for_female_70~74세',
       'for_female_75~79세', 'for_female_80~84세', 'for_female_85세이상',
       'for_female_15세미만'], inplace = True)

In [213]:
df_nnn

,jur_stn,year,popu_합계,for_합계,popu_female_합계,for_female_합계,popu_u20,popu_2030,popu_4050,popu_o60,...,popu_female_4050,popu_female_o60,for_u20,for_2030,for_4050,for_o60,for_female_u20,for_female_2030,for_female_4050,for_female_o60
0,서울중부경찰서,2017(상반기),127896,10265,65701,5461,16774,42620,40286,28216,...,20161,15543,893,4872,3302,1198,464,2568,1750,679
17,서울남대문경찰서,2017(상반기),127896,10265,65701,5461,16774,42620,40286,28216,...,20161,15543,893,4872,3302,1198,464,2568,1750,679
34,서울중부경찰서,2017(하반기),127896,10265,65701,5461,16774,42620,40286,28216,...,20161,15543,893,4872,3302,1198,464,2568,1750,679
51,서울남대문경찰서,2017(하반기),127896,10265,65701,5461,16774,42620,40286,28216,...,20161,15543,893,4872,3302,1198,464,2568,1750,679
68,서울종로경찰서,2017(상반기),157277,10979,80607,6066,23931,50443,49187,33716,...,24967,18530,1116,6063,2878,922,668,3462,1416,520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),192446,2871,96095,1260,32856,46112,65987,47491,...,32887,25995,124,1718,840,189,65,709,382,104
4114,진주경찰서,2019(상반기),354166,7152,177306,2868,66710,94780,112947,79729,...,56673,45031,424,4908,1563,257,198,1875,666,129
4131,진주경찰서,2019(하반기),354166,7152,177306,2868,66710,94780,112947,79729,...,56673,45031,424,4908,1563,257,198,1875,666,129
4148,진해경찰서,2019(상반기),190885,4917,92798,1768,40507,49459,62622,38297,...,29965,20973,212,2834,1570,301,98,902,614,154
4165,진해경찰서,2019(하반기),190885,4917,92798,1768,40507,49459,62622,38297,...,29965,20973,212,2834,1570,301,98,902,614,154

In [214]:
df_nnn.iloc[0, 2:] = df_nnn.iloc[0, 2:] / 2
df_nnn.iloc[1, 2:] = df_nnn.iloc[1, 2:] / 2
df_nnn.iloc[2, 2:] = df_nnn.iloc[2, 2:] / 2
df_nnn.iloc[3, 2:] = df_nnn.iloc[3, 2:] / 2 # 중구

df_nnn.iloc[4, 2:] = df_nnn.iloc[4, 2:] / 2
df_nnn.iloc[5, 2:] = df_nnn.iloc[5, 2:] / 2
df_nnn.iloc[6, 2:] = df_nnn.iloc[6, 2:] / 2
df_nnn.iloc[7, 2:] = df_nnn.iloc[7, 2:] / 2 # 종로구

df_nnn.iloc[12, 2:] = df_nnn.iloc[12, 2:] / 2
df_nnn.iloc[13, 2:] = df_nnn.iloc[13, 2:] / 2
df_nnn.iloc[14, 2:] = df_nnn.iloc[14, 2:] / 2
df_nnn.iloc[15, 2:] = df_nnn.iloc[15, 2:] / 2 # 성북구

df_nnn.iloc[28, 2:] = df_nnn.iloc[28, 2:] / 2
df_nnn.iloc[29, 2:] = df_nnn.iloc[29, 2:] / 2
df_nnn.iloc[30, 2:] = df_nnn.iloc[30, 2:] / 2
df_nnn.iloc[31, 2:] = df_nnn.iloc[31, 2:] / 2 # 은평구

df_nnn.iloc[50, 2:] = df_nnn.iloc[50, 2:] / 2
df_nnn.iloc[51, 2:] = df_nnn.iloc[51, 2:] / 2
df_nnn.iloc[52, 2:] = df_nnn.iloc[52, 2:] / 2
df_nnn.iloc[53, 2:] = df_nnn.iloc[53, 2:] / 2 # 서초구

df_nnn.iloc[38, 2:] = df_nnn.iloc[38, 2:] / 2
df_nnn.iloc[39, 2:] = df_nnn.iloc[39, 2:] / 2
df_nnn.iloc[40, 2:] = df_nnn.iloc[40, 2:] / 2
df_nnn.iloc[41, 2:] = df_nnn.iloc[41, 2:] / 2 # 강남구

In [215]:
for i in range(1, 3):
    df_nnn.iloc[0 + 82 * i, 2:] = df_nnn.iloc[0 + 82 * i, 2:] / 2
    df_nnn.iloc[1 + 82 * i, 2:] = df_nnn.iloc[1 + 82 * i, 2:] / 2
    df_nnn.iloc[2 + 82 * i, 2:] = df_nnn.iloc[2 + 82 * i, 2:] / 2
    df_nnn.iloc[3 + 82 * i, 2:] = df_nnn.iloc[3 + 82 * i, 2:] / 2 # 중구

    df_nnn.iloc[4 + 82 * i, 2:] = df_nnn.iloc[4 + 82 * i, 2:] / 2
    df_nnn.iloc[5 + 82 * i, 2:] = df_nnn.iloc[5 + 82 * i, 2:] / 2
    df_nnn.iloc[6 + 82 * i, 2:] = df_nnn.iloc[6 + 82 * i, 2:] / 2
    df_nnn.iloc[7 + 82 * i, 2:] = df_nnn.iloc[7 + 82 * i, 2:] / 2 # 종로구

    df_nnn.iloc[12 + 82 * i, 2:] = df_nnn.iloc[12 + 82 * i, 2:] / 2
    df_nnn.iloc[13 + 82 * i, 2:] = df_nnn.iloc[13 + 82 * i, 2:] / 2
    df_nnn.iloc[14 + 82 * i, 2:] = df_nnn.iloc[14 + 82 * i, 2:] / 2
    df_nnn.iloc[15 + 82 * i, 2:] = df_nnn.iloc[15 + 82 * i, 2:] / 2 # 성북구

    df_nnn.iloc[28 + 82 * i, 2:] = df_nnn.iloc[28 + 82 * i, 2:] / 2
    df_nnn.iloc[29 + 82 * i, 2:] = df_nnn.iloc[29 + 82 * i, 2:] / 2
    df_nnn.iloc[30 + 82 * i, 2:] = df_nnn.iloc[30 + 82 * i, 2:] / 2
    df_nnn.iloc[31 + 82 * i, 2:] = df_nnn.iloc[31 + 82 * i, 2:] / 2 # 은평구

    df_nnn.iloc[50 + 82 * i, 2:] = df_nnn.iloc[50 + 82 * i, 2:] / 2
    df_nnn.iloc[51 + 82 * i, 2:] = df_nnn.iloc[51 + 82 * i, 2:] / 2
    df_nnn.iloc[52 + 82 * i, 2:] = df_nnn.iloc[52 + 82 * i, 2:] / 2
    df_nnn.iloc[53 + 82 * i, 2:] = df_nnn.iloc[53 + 82 * i, 2:] / 2 # 서초구

    df_nnn.iloc[38 + 82 * i, 2:] = df_nnn.iloc[38 + 82 * i, 2:] / 2
    df_nnn.iloc[39 + 82 * i, 2:] = df_nnn.iloc[39 + 82 * i, 2:] / 2
    df_nnn.iloc[40 + 82 * i, 2:] = df_nnn.iloc[40 + 82 * i, 2:] / 2
    df_nnn.iloc[41 + 82 * i, 2:] = df_nnn.iloc[41 + 82 * i, 2:] / 2 # 강남구

In [217]:
df_nnn['sx_rate_합계'] = round(((df_nnn['popu_합계'] - df_nnn['popu_female_합계']) / df_nnn['popu_female_합계']) * 100, 1)
df_nnn['sx_rate_u20'] = round(((df_nnn['popu_u20'] - df_nnn['popu_female_u20']) / df_nnn['popu_female_u20']) * 100, 1)
df_nnn['sx_rate_2030'] = round(((df_nnn['popu_2030'] - df_nnn['popu_female_2030']) / df_nnn['popu_female_2030']) * 100, 1)
df_nnn['sx_rate_4050'] = round(((df_nnn['popu_4050'] - df_nnn['popu_female_4050']) / df_nnn['popu_female_4050']) * 100, 1)
df_nnn['sx_rate_o60'] = round(((df_nnn['popu_o60'] - df_nnn['popu_female_o60']) / df_nnn['popu_female_o60']) * 100, 1)
df_nnn['for_sx_rate_합계'] = round(((df_nnn['for_합계'] - df_nnn['for_female_합계']) / df_nnn['for_female_합계']) * 100, 1)
df_nnn['for_sx_rate_u20'] = round(((df_nnn['for_u20'] - df_nnn['for_female_u20']) / df_nnn['for_female_u20']) * 100, 1)
df_nnn['for_sx_rate_2030'] = round(((df_nnn['for_2030'] - df_nnn['for_female_2030']) / df_nnn['for_female_2030']) * 100, 1)
df_nnn['for_sx_rate_4050'] = round(((df_nnn['for_4050'] - df_nnn['for_female_4050']) / df_nnn['for_female_4050']) * 100, 1)
df_nnn['for_sx_rate_o60'] = round(((df_nnn['for_o60'] - df_nnn['for_female_o60']) / df_nnn['for_female_o60']) * 100, 1)

In [218]:
df_nnn

,jur_stn,year,popu_합계,for_합계,popu_female_합계,for_female_합계,popu_u20,popu_2030,popu_4050,popu_o60,...,sx_rate_합계,sx_rate_u20,sx_rate_2030,sx_rate_4050,sx_rate_o60,for_sx_rate_합계,for_sx_rate_u20,for_sx_rate_2030,for_sx_rate_4050,for_sx_rate_o60
0,서울중부경찰서,2017(상반기),63948.0,5132.5,32850.5,2730.5,8387.0,21310.0,20143.0,14108.0,...,94.7,95.1,99.1,99.8,81.5,88.0,92.5,89.7,88.7,76.4
17,서울남대문경찰서,2017(상반기),63948.0,5132.5,32850.5,2730.5,8387.0,21310.0,20143.0,14108.0,...,94.7,95.1,99.1,99.8,81.5,88.0,92.5,89.7,88.7,76.4
34,서울중부경찰서,2017(하반기),63948.0,5132.5,32850.5,2730.5,8387.0,21310.0,20143.0,14108.0,...,94.7,95.1,99.1,99.8,81.5,88.0,92.5,89.7,88.7,76.4
51,서울남대문경찰서,2017(하반기),63948.0,5132.5,32850.5,2730.5,8387.0,21310.0,20143.0,14108.0,...,94.7,95.1,99.1,99.8,81.5,88.0,92.5,89.7,88.7,76.4
68,서울종로경찰서,2017(상반기),78638.5,5489.5,40303.5,3033.0,11965.5,25221.5,24593.5,16858.0,...,95.1,105.7,98.0,97.0,82.0,81.0,67.1,75.1,103.2,77.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),192446.0,2871.0,96095.0,1260.0,32856.0,46112.0,65987.0,47491.0,...,100.3,109.2,114.4,100.6,82.7,127.9,90.8,142.3,119.9,81.7
4114,진주경찰서,2019(상반기),354166.0,7152.0,177306.0,2868.0,66710.0,94780.0,112947.0,79729.0,...,99.7,110.8,115.7,99.3,77.1,149.4,114.1,161.8,134.7,99.2
4131,진주경찰서,2019(하반기),354166.0,7152.0,177306.0,2868.0,66710.0,94780.0,112947.0,79729.0,...,99.7,110.8,115.7,99.3,77.1,149.4,114.1,161.8,134.7,99.2
4148,진해경찰서,2019(상반기),190885.0,4917.0,92798.0,1768.0,40507.0,49459.0,62622.0,38297.0,...,105.7,109.1,120.0,109.0,82.6,178.1,116.3,214.2,155.7,95.5
4165,진해경찰서,2019(하반기),190885.0,4917.0,92798.0,1768.0,40507.0,49459.0,62622.0,38297.0,...,105.7,109.1,120.0,109.0,82.6,178.1,116.3,214.2,155.7,95.5

In [221]:
df_nnn.to_csv('new_인구데이터.csv', index = False)

In [225]:
df_nnn.columns

Index(['jur_stn', 'year', 'popu_합계', 'for_합계', 'popu_female_합계',
       'for_female_합계', 'popu_u20', 'popu_2030', 'popu_4050', 'popu_o60',
       'popu_female_u20', 'popu_female_2030', 'popu_female_4050',
       'popu_female_o60', 'for_u20', 'for_2030', 'for_4050', 'for_o60',
       'for_female_u20', 'for_female_2030', 'for_female_4050',
       'for_female_o60', 'sx_rate_합계', 'sx_rate_u20', 'sx_rate_2030',
       'sx_rate_4050', 'sx_rate_o60', 'for_sx_rate_합계', 'for_sx_rate_u20',
       'for_sx_rate_2030', 'for_sx_rate_4050', 'for_sx_rate_o60'],
      dtype='object')

In [227]:
df_nnn.drop(columns = ['popu_o60', 'for_u20', 'for_2030', 'popu_합계', 'for_합계', 'popu_u20', 'popu_o60'], inplace = True)

In [226]:
df_bb.columns

Index(['jur_stn', 'year', 'child', 'house', 'report_sx_total', 'vio_cnt',
       'mur_rob_cnt', 'car_cnt', 'popu_합계', 'for_합계', 'popu_u20', 'popu_o60',
       'for_u20', 'for_2030', 'single_합계', 'single_u20', 'single_2030',
       'single_4050', 'single_o60', 'single_f_합계', 'single_f_u20',
       'single_f_2030', 'single_f_4050', 'single_f_o60', 'popu_2050',
       'for_o40', '총범죄발생대비검거수', '절도폭력범죄발생대비검거수', '강도살인범죄발생대비검거수',
       '교통사고범죄발생대비검거수', '기초질서범죄발생대비검거수', '인구수대비검거수', '외국인인구수대비검거수', '인구수대비경찰수',
       'before_q1', 'before_q2', 'before_q3', 'before_q4', 'before_q5',
       'light_r', 'cctv_r', 'adult_r', 'bell_r', 'light_cnt', 'cctv', 'adult',
       'bell', 'ofn_10', 'ofn_20', 'ofn_340', 'ofn_5670', 'ofn_80ov', 'ofn_m',
       'ofn_w', 'ofn_unknown', 'vic_10', 'vic_20', 'vic_340', 'vic_5670',
       'vic_80ov', 'vic_m', 'vic_w', 'vic_unknown', 'case_car_man',
       'case_car_car', 'case_car_only', 'q1', 'q2', 'q3', 'q4', 'q5'],
      dtype='object')

In [228]:
df_bb = pd.read_csv('total_data(교통,인구,집값,어린이,누적합포함).csv')

In [229]:
ndf = pd.merge(left = df_bb, right = df_nnn, how = 'left', on = ['jur_stn', 'year'])

In [230]:
ndf

,jur_stn,year,child,house,report_sx_total,vio_cnt,mur_rob_cnt,car_cnt,popu_합계,for_합계,...,sx_rate_합계,sx_rate_u20,sx_rate_2030,sx_rate_4050,sx_rate_o60,for_sx_rate_합계,for_sx_rate_u20,for_sx_rate_2030,for_sx_rate_4050,for_sx_rate_o60
0,서울중부경찰서,2017(상반기),39.0,97.0,22574.0,1324.0,0.0,1412.0,63948.0,5132.500000,...,94.7,95.1,99.1,99.8,81.5,88.0,92.5,89.7,88.7,76.4
1,서울종로경찰서,2017(상반기),46.0,98.0,19674.0,1102.0,0.0,867.0,78638.5,5489.500000,...,95.1,105.7,98.0,97.0,82.0,81.0,67.1,75.1,103.2,77.3
2,서울남대문경찰서,2017(상반기),39.0,97.0,14499.0,949.0,0.0,736.0,63948.0,5132.500000,...,94.7,95.1,99.1,99.8,81.5,88.0,92.5,89.7,88.7,76.4
3,서울서대문경찰서,2017(상반기),39.0,98.0,38769.0,1924.0,0.0,1788.0,321345.0,13152.000000,...,88.8,96.6,86.4,95.6,78.0,57.7,60.2,45.7,98.8,82.2
4,서울혜화경찰서,2017(상반기),46.0,98.0,18857.0,1127.0,0.0,899.0,78638.5,5489.500000,...,95.1,105.7,98.0,97.0,82.0,81.0,67.1,75.1,103.2,77.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,창원서부경찰서,2020(하반기),44.0,95.0,21563.0,1282.0,1.0,1984.0,262241.0,3605.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,마산중부경찰서,2020(하반기),37.0,88.0,17412.0,1107.0,1.0,1301.0,175504.0,2158.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,마산동부경찰서,2020(하반기),44.0,86.0,24025.0,1430.0,4.0,1919.0,193101.0,2000.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,진주경찰서,2020(하반기),64.0,92.0,34627.0,2347.0,2.0,3169.0,353236.0,6427.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327,진해경찰서,2020(하반기),37.0,90.0,16772.0,1116.0,1.0,1537.0,192759.0,3363.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [231]:
ndf.columns

Index(['jur_stn', 'year', 'child', 'house', 'report_sx_total', 'vio_cnt',
       'mur_rob_cnt', 'car_cnt', 'popu_합계', 'for_합계', 'popu_u20', 'popu_o60',
       'for_u20', 'for_2030', 'single_합계', 'single_u20', 'single_2030',
       'single_4050', 'single_o60', 'single_f_합계', 'single_f_u20',
       'single_f_2030', 'single_f_4050', 'single_f_o60', 'popu_2050',
       'for_o40', '총범죄발생대비검거수', '절도폭력범죄발생대비검거수', '강도살인범죄발생대비검거수',
       '교통사고범죄발생대비검거수', '기초질서범죄발생대비검거수', '인구수대비검거수', '외국인인구수대비검거수', '인구수대비경찰수',
       'before_q1', 'before_q2', 'before_q3', 'before_q4', 'before_q5',
       'light_r', 'cctv_r', 'adult_r', 'bell_r', 'light_cnt', 'cctv', 'adult',
       'bell', 'ofn_10', 'ofn_20', 'ofn_340', 'ofn_5670', 'ofn_80ov', 'ofn_m',
       'ofn_w', 'ofn_unknown', 'vic_10', 'vic_20', 'vic_340', 'vic_5670',
       'vic_80ov', 'vic_m', 'vic_w', 'vic_unknown', 'case_car_man',
       'case_car_car', 'case_car_only', 'q1', 'q2', 'q3', 'q4', 'q5',
       'popu_female_합계', 'for_female_합계', 'popu_2030', 'popu_4050',
       'popu_female_u20', 'popu_female_2030', 'popu_female_4050',
       'popu_female_o60', 'for_4050', 'for_o60', 'for_female_u20',
       'for_female_2030', 'for_female_4050', 'for_female_o60', 'sx_rate_합계',
       'sx_rate_u20', 'sx_rate_2030', 'sx_rate_4050', 'sx_rate_o60',
       'for_sx_rate_합계', 'for_sx_rate_u20', 'for_sx_rate_2030',
       'for_sx_rate_4050', 'for_sx_rate_o60'],
      dtype='object')

In [232]:
ndf.to_csv('total_data(성비더함).csv', index = False)