- popu_합계: 전체 인구
- for_합계: 외국인 인구
- popu_u20: 20세 미만 인구
- popu_2030: 2030대 인구
- popu_4050: 4050대 인구
- popu_o60: 60세 이상 인구
- for_u20: 20세 미만 외국인 인구
- for_2030: 2030대 외국인 ㅇ
- for_4050	
- for_o60

In [112]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [113]:
df1 = gpd.read_file('./data/1.5개시도_경찰서_관할경계.geojson')
df3 = pd.read_csv('./data/14.5개시도_성연령별_총인구분포.csv')
df_b = pd.read_csv('base_df.csv')

C:\Anaconda3\lib\site-packages\geopandas\array.py:85: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  aout[:] = out

In [114]:
df3['age'].unique()

array(['합계', '0~4세', '0세', '1세', '2세', '3세', '4세', '5~9세', '5세', '6세',
       '7세', '8세', '9세', '10~14세', '10세', '11세', '12세', '13세', '14세',
       '15~19세', '15세', '16세', '17세', '18세', '19세', '20~24세', '20세',
       '21세', '22세', '23세', '24세', '25~29세', '25세', '26세', '27세', '28세',
       '29세', '30~34세', '30세', '31세', '32세', '33세', '34세', '35~39세',
       '35세', '36세', '37세', '38세', '39세', '40~44세', '40세', '41세', '42세',
       '43세', '44세', '45~49세', '45세', '46세', '47세', '48세', '49세',
       '50~54세', '50세', '51세', '52세', '53세', '54세', '55~59세', '55세',
       '56세', '57세', '58세', '59세', '60~64세', '60세', '61세', '62세', '63세',
       '64세', '65~69세', '65세', '66세', '67세', '68세', '69세', '70~74세',
       '70세', '71세', '72세', '73세', '74세', '75~79세', '75세', '76세', '77세',
       '78세', '79세', '80~84세', '80세', '81세', '82세', '83세', '84세', '85세이상',
       '85~89세', '85세', '86세', '87세', '88세', '89세', '90~94세', '90세',
       '91세', '92세', '93세', '94세', '95~99세', '95세', '96세', '97세', '98세',
       '99세', '100세이상', '15세미만', '15~64세', '65세이상', '평균연령', '중위연령'],
      dtype=object)

In [115]:
# 중복되지 않는 연령 구간별 합계 가져오기
df3_n = df3[df3['age'].isin(['합계', '15세미만','15~19세', '20~24세', '25~29세', '30~34세','35~39세', '40~44세', '45~49세'
                             , '50~54세', '55~59세', '60~64세', '65~69세', '70~74세', '75~79세', '80~84세', '85세이상'])]
df3_n

,sido,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate
0,서울특별시,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3
19,서울특별시,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8
25,서울특별시,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8
31,서울특별시,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2
37,서울특별시,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1
...,...,...,...,...,...,...,...,...,...,...,...,...
13781,서울특별시,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3
13787,서울특별시,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0
13793,서울특별시,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0
13799,서울특별시,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7
13819,서울특별시,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0

In [116]:
# 데이터 타입 변경
df3_n = df3_n.astype({'popu_num' : 'int'})
df3_n = df3_n.astype({'local_num' : 'int'})
df3_n = df3_n.astype({'popu_male_num' : 'int'})
df3_n = df3_n.astype({'popu_female_num' : 'int'})
df3_n = df3_n.astype({'local_male_num' : 'int'})
df3_n = df3_n.astype({'local_female_num' : 'int'})

In [117]:
# 내국인 인구로 외국인 인구 구하기
df3_n['foreigner'] = df3_n['popu_num'] - df3_n['local_num']
df3_n['for_male_num'] = df3_n['popu_male_num'] - df3_n['local_male_num']
df3_n['for_female_num'] = df3_n['popu_female_num'] - df3_n['local_female_num']

In [118]:
# 외국인 성비
df3_n['for_sx_rate'] = round(df3_n['for_male_num'] / df3_n['for_female_num'] * 100, 1)

In [119]:
#불필요한 컬럼 제거
df3_n.drop(columns = ['sido'], inplace = True)

In [120]:
df3_n

,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,foreigner,for_male_num,for_female_num,for_sx_rate
0,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3,10979,4913,6066,81.0
19,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8,840,307,533,57.6
25,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8,2757,940,1817,51.7
31,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2,1404,637,767,83.1
37,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1,1096,561,535,104.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13781,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3,98,50,48,104.2
13787,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0,61,25,36,69.4
13793,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0,33,9,24,37.5
13799,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7,20,5,15,33.3
13819,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0,470,270,200,135.0

In [121]:
# 경찰서별 담당 행정구역
sgg_nm_transfer = {
    '마산동부경찰서' : '창원시마산회원구'  ,
    '마산중부경찰서' : '창원시마산합포구'  ,
    '서울강남경찰서' : '강남구'  , 
    '서울강동경찰서' : '강동구' , 
    '서울강북경찰서' :'강북구'  , 
    '서울강서경찰서' :  '강서구',
    '서울관악경찰서' : '관악구' ,
      '서울광진경찰서' : '광진구', 
     '서울구로경찰서' : '구로구' , 
     '서울금천경찰서' : '금천구' , 
    '서울남대문경찰서' : '중구' , 
    '서울노원경찰서' : '노원구' ,
    '서울도봉경찰서' : '도봉구'  , 
    '서울동대문경찰서' : '동대문구'  , 
    '서울동작경찰서' : '동작구'  , 
    '서울마포경찰서' : '마포구' , 
    '서울방배경찰서' : '서초구', 
    '서울서대문경찰서' : '서대문구' ,
    '서울서부경찰서' : '은평구' , 
    '서울서초경찰서' : '서초구' , 
    '서울성동경찰서' : '성동구' , 
    '서울성북경찰서' :'성북구' , 
    '서울송파경찰서' :'송파구' , 
    '서울수서경찰서' : '강남구' ,
     '서울양천경찰서': '양천구'  , 
    '서울영등포경찰서' : '영등포구' , 
    '서울용산경찰서': '용산구'  , 
    '서울은평경찰서' : '은평구' , 
    '서울종로경찰서': '종로구', 
    '서울종암경찰서' : '성북구'  ,
     '서울중랑경찰서' : '중랑구'   , 
    '서울중부경찰서' : '중구'  , 
    '서울혜화경찰서': '종로구'  , 
    '세종경찰서' : '세종시'  , 
    '수원남부경찰서': '수원시영통구'  ,
   '수원서부경찰서' : '수원시팔달구'  ,  
    '수원중부경찰서' :'수원시장안구'   , 
    '진주경찰서' : '진주시'  ,
    '진해경찰서' : '창원시진해구'  , 
    '창원서부경찰서' : '창원시의창구' , 
    '창원중부경찰서': '창원시성산구'
    
}

In [122]:
# 기본 데이터프레임에 담당 행정구역 추가
df_b['sgg_nm'] = df_b['jur_stn'].apply(lambda x : sgg_nm_transfer[x])
df_b

      jur_stn       year    sgg_nm
0     서울중부경찰서   2016(이전)        중구
1     서울종로경찰서   2016(이전)       종로구
2    서울남대문경찰서   2016(이전)        중구
3    서울서대문경찰서   2016(이전)      서대문구
4     서울혜화경찰서   2016(이전)       종로구
..        ...        ...       ...
364   창원서부경찰서  2020(하반기)    창원시의창구
365   마산중부경찰서  2020(하반기)  창원시마산합포구
366   마산동부경찰서  2020(하반기)  창원시마산회원구
367     진주경찰서  2020(하반기)       진주시
368     진해경찰서  2020(하반기)    창원시진해구

[369 rows x 3 columns]

In [123]:
# 연도 추가
df_b['date'] = df_b['year'].apply(lambda x : int(x[:4]))
df_b

      jur_stn       year    sgg_nm  date
0     서울중부경찰서   2016(이전)        중구  2016
1     서울종로경찰서   2016(이전)       종로구  2016
2    서울남대문경찰서   2016(이전)        중구  2016
3    서울서대문경찰서   2016(이전)      서대문구  2016
4     서울혜화경찰서   2016(이전)       종로구  2016
..        ...        ...       ...   ...
364   창원서부경찰서  2020(하반기)    창원시의창구  2020
365   마산중부경찰서  2020(하반기)  창원시마산합포구  2020
366   마산동부경찰서  2020(하반기)  창원시마산회원구  2020
367     진주경찰서  2020(하반기)       진주시  2020
368     진해경찰서  2020(하반기)    창원시진해구  2020

[369 rows x 4 columns]

In [124]:
df3_n

,sgg_nm,age,date,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,foreigner,for_male_num,for_female_num,for_sx_rate
0,종로구,합계,2017,157277,76670,80607,95.1,146298,71757,74541,96.3,10979,4913,6066,81.0
19,종로구,15~19세,2017,10198,5267,4931,106.8,9358,4960,4398,112.8,840,307,533,57.6
25,종로구,20~24세,2017,15098,6848,8250,83.0,12341,5908,6433,91.8,2757,940,1817,51.7
31,종로구,25~29세,2017,13584,7156,6428,111.3,12180,6519,5661,115.2,1404,637,767,83.1
37,종로구,30~34세,2017,11100,5615,5485,102.4,10004,5054,4950,102.1,1096,561,535,104.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13781,중구,70~74세,2017,4900,2204,2696,81.8,4802,2154,2648,81.3,98,50,48,104.2
13787,중구,75~79세,2017,4139,1732,2407,72.0,4078,1707,2371,72.0,61,25,36,69.4
13793,중구,80~84세,2017,2338,846,1492,56.7,2305,837,1468,57.0,33,9,24,37.5
13799,중구,85세이상,2017,1548,477,1071,44.5,1528,472,1056,44.7,20,5,15,33.3
13819,중구,15세미만,2017,11035,5604,5431,103.2,10565,5334,5231,102.0,470,270,200,135.0

In [125]:
df3_nn

,jur_stn,year,sgg_nm,date,age,popu_num,popu_male_num,popu_female_num,popu_sx_rate,local_num,local_male_num,local_female_num,local_sx_rate,foreigner,for_male_num,for_female_num,for_sx_rate
0,서울중부경찰서,2017(상반기),중구,2017,합계,127896,62195,65701,94.7,117631,57391,60240,95.3,10265,4804,5461,88.0
1,서울중부경찰서,2017(상반기),중구,2017,15세미만,11035,5604,5431,103.2,10565,5334,5231,102.0,470,270,200,135.0
2,서울중부경찰서,2017(상반기),중구,2017,15~64세,97649,48332,49317,98.0,88374,44025,44349,99.3,9275,4307,4968,86.7
3,서울중부경찰서,2017(상반기),중구,2017,65세이상,19212,8259,10953,75.4,18692,8032,10660,75.3,520,227,293,77.5
4,서울남대문경찰서,2017(상반기),중구,2017,합계,127896,62195,65701,94.7,117631,57391,60240,95.3,10265,4804,5461,88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,진해경찰서,2019(상반기),창원시진해구,2019,65세이상,25405,11045,14360,76.9,25268,10982,14286,76.9,137,63,74,85.1
980,진해경찰서,2019(하반기),창원시진해구,2019,합계,190885,98087,92798,105.7,185968,94938,91030,104.3,4917,3149,1768,178.1
981,진해경찰서,2019(하반기),창원시진해구,2019,15세미만,31522,16267,15255,106.6,31357,16185,15172,106.7,165,82,83,98.8
982,진해경찰서,2019(하반기),창원시진해구,2019,15~64세,133958,70775,63183,112.0,129343,67771,61572,110.1,4615,3004,1611,186.5
983,진해경찰서,2019(하반기),창원시진해구,2019,65세이상,25405,11045,14360,76.9,25268,10982,14286,76.9,137,63,74,85.1

In [126]:
df3_nn = pd.merge(df_b, df3_n, on =['sgg_nm', 'date'])

In [127]:
df_bb = df3_nn[['jur_stn', 'year', 'sgg_nm', 'date']]
df_bb

      jur_stn       year  sgg_nm  date
0     서울중부경찰서  2017(상반기)      중구  2017
1     서울중부경찰서  2017(상반기)      중구  2017
2     서울중부경찰서  2017(상반기)      중구  2017
3     서울중부경찰서  2017(상반기)      중구  2017
4     서울중부경찰서  2017(상반기)      중구  2017
...       ...        ...     ...   ...
4177    진해경찰서  2019(하반기)  창원시진해구  2019
4178    진해경찰서  2019(하반기)  창원시진해구  2019
4179    진해경찰서  2019(하반기)  창원시진해구  2019
4180    진해경찰서  2019(하반기)  창원시진해구  2019
4181    진해경찰서  2019(하반기)  창원시진해구  2019

[4182 rows x 4 columns]

In [128]:
for i in df3_nn['age'].unique() :
    df_bb['popu_'+i] = 0

<ipython-input-128-7c141b5acd54>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bb['popu_'+i] = 0

In [129]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,서울중부경찰서,2017(상반기),중구,2017,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4178,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4179,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4180,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4181,진해경찰서,2019(하반기),창원시진해구,2019,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [130]:
for i in range(len(df3_nn)) :
    bb_nm = df3_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df3_nn['jur_stn'].iloc[i])&(df_bb['date']==df3_nn['date'].iloc[i])]
    bb[bb_nm] = df3_nn['popu_num'].iloc[i]
    df_bb['popu_' + bb_nm].iloc[bb.index] = df3_nn['popu_num'].iloc[i]
df4 = df_bb
df4

<ipython-input-130-8440aac26757>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df3_nn['popu_num'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,popu_45~49세,popu_50~54세,popu_55~59세,popu_60~64세,popu_65~69세,popu_70~74세,popu_75~79세,popu_80~84세,popu_85세이상,popu_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,10406,9926,10810,9004,6287,4900,4139,2338,1548,11035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,17213,14121,14130,12892,8705,6314,4943,3297,2146,31522

In [131]:
for i in df3_nn['age'].unique() :
    df_bb['for_'+i] = 0

In [132]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0,0,0

In [133]:
for i in range(len(df3_nn)) :
    bb_nm = df3_nn['age'].iloc[i]
    bb = df_bb[(df_bb['jur_stn']==df3_nn['jur_stn'].iloc[i])&(df_bb['date']==df3_nn['date'].iloc[i])]
    bb[bb_nm] = df3_nn['foreigner'].iloc[i]
    df_bb['for_' + bb_nm].iloc[bb.index] = df3_nn['foreigner'].iloc[i]
df4 = df_bb
df4

<ipython-input-133-066708432911>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[bb_nm] = df3_nn['foreigner'].iloc[i]
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [134]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
1,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
2,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
3,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
4,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4177,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4178,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4179,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4180,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4181,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [135]:
df4.drop_duplicates(inplace=True)
df4

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_45~49세,for_50~54세,for_55~59세,for_60~64세,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,875,900,781,678,308,98,61,33,20,470
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,800,768,638,512,226,81,54,27,22,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,233,213,168,103,51,15,11,7,2,54
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,412,362,260,140,71,22,13,7,4,135
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,412,362,260,140,71,22,13,7,4,135
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,481,370,259,164,78,27,16,9,7,165

In [136]:
df4['year'].value_counts()

2017(상반기)    41
2017(하반기)    41
2018(상반기)    41
2018(하반기)    41
2019(상반기)    41
2019(하반기)    41
Name: year, dtype: int64

In [137]:
df4.columns

Index(['jur_stn', 'year', 'sgg_nm', 'date', 'popu_합계', 'popu_15~19세',
       'popu_20~24세', 'popu_25~29세', 'popu_30~34세', 'popu_35~39세',
       'popu_40~44세', 'popu_45~49세', 'popu_50~54세', 'popu_55~59세',
       'popu_60~64세', 'popu_65~69세', 'popu_70~74세', 'popu_75~79세',
       'popu_80~84세', 'popu_85세이상', 'popu_15세미만', 'for_합계', 'for_15~19세',
       'for_20~24세', 'for_25~29세', 'for_30~34세', 'for_35~39세', 'for_40~44세',
       'for_45~49세', 'for_50~54세', 'for_55~59세', 'for_60~64세', 'for_65~69세',
       'for_70~74세', 'for_75~79세', 'for_80~84세', 'for_85세이상', 'for_15세미만'],
      dtype='object')

In [85]:
df4['jur_stn'].unique()

array(['서울중부경찰서', '서울남대문경찰서', '서울종로경찰서', '서울혜화경찰서', '서울서대문경찰서', '서울용산경찰서',
       '서울성북경찰서', '서울종암경찰서', '서울동대문경찰서', '서울마포경찰서', '서울영등포경찰서', '서울성동경찰서',
       '서울동작경찰서', '서울광진경찰서', '서울서부경찰서', '서울은평경찰서', '서울강북경찰서', '서울금천경찰서',
       '서울중랑경찰서', '서울강남경찰서', '서울수서경찰서', '서울관악경찰서', '서울강서경찰서', '서울강동경찰서',
       '서울구로경찰서', '서울서초경찰서', '서울방배경찰서', '서울양천경찰서', '서울송파경찰서', '서울노원경찰서',
       '서울도봉경찰서', '수원중부경찰서', '수원남부경찰서', '수원서부경찰서', '세종경찰서', '창원중부경찰서',
       '창원서부경찰서', '마산중부경찰서', '마산동부경찰서', '진주경찰서', '진해경찰서'], dtype=object)

In [86]:
len(df4['jur_stn'].unique())

41

In [87]:
df4.to_csv('alskd.csv')

In [139]:
df4['popu_u20'] = df4['popu_15세미만'] + df4['popu_15~19세']
df4['popu_2030'] = df4['popu_20~24세'] + df4['popu_25~29세'] + df4['popu_30~34세'] + df4['popu_35~39세']
df4['popu_4050'] = df4['popu_40~44세'] + df4['popu_45~49세'] + df4['popu_50~54세'] + df4['popu_55~59세']

In [140]:
df4['popu_o60'] = df4['popu_합계'] - df4['popu_u20'] - df4['popu_2030'] - df4['popu_4050']

In [141]:
df4

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_65~69세,for_70~74세,for_75~79세,for_80~84세,for_85세이상,for_15세미만,popu_u20,popu_2030,popu_4050,popu_o60
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,308,98,61,33,20,470,16774,42620,40286,28216
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,226,81,54,27,22,276,23931,50443,49187,33716
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,51,15,11,7,2,54,32856,46112,65987,47491
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,71,22,13,7,4,135,66710,94780,112947,79729
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,71,22,13,7,4,135,66710,94780,112947,79729
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,78,27,16,9,7,165,40507,49459,62622,38297
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,78,27,16,9,7,165,40507,49459,62622,38297

In [142]:
df4['for_u20'] = df4['for_15세미만'] + df4['for_15~19세']
df4['for_2030'] = df4['for_20~24세'] + df4['for_25~29세'] + df4['for_30~34세'] + df4['for_35~39세']
df4['for_4050'] = df4['for_40~44세'] + df4['for_45~49세'] + df4['for_50~54세'] + df4['for_55~59세']

In [143]:
df4['for_o60'] = df4['for_합계'] - df4['for_u20'] - df4['for_2030'] - df4['for_4050']

In [144]:
df4

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,for_85세이상,for_15세미만,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,20,470,16774,42620,40286,28216,893,4872,3302,1198
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,22,276,23931,50443,49187,33716,1116,6063,2878,922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,2,54,32856,46112,65987,47491,124,1718,840,189
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,4,135,66710,94780,112947,79729,424,4908,1563,257
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,4,135,66710,94780,112947,79729,424,4908,1563,257
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7,165,40507,49459,62622,38297,212,2834,1570,301
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,7,165,40507,49459,62622,38297,212,2834,1570,301

In [146]:
# 필요없는 컬럼 제거
df4_n = df4.drop(['popu_15~19세',
       'popu_20~24세', 'popu_25~29세', 'popu_30~34세', 'popu_35~39세',
       'popu_40~44세', 'popu_45~49세', 'popu_50~54세', 'popu_55~59세',
       'popu_60~64세', 'popu_65~69세', 'popu_70~74세', 'popu_75~79세',
       'popu_80~84세', 'popu_85세이상', 'popu_15세미만','for_15~19세',
       'for_20~24세', 'for_25~29세', 'for_30~34세', 'for_35~39세', 'for_40~44세',
       'for_45~49세', 'for_50~54세', 'for_55~59세', 'for_60~64세', 'for_65~69세',
       'for_70~74세', 'for_75~79세', 'for_80~84세', 'for_85세이상', 'for_15세미만'], axis = 1)

In [147]:
df4_n

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2017(상반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
17,서울남대문경찰서,2017(상반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
34,서울중부경찰서,2017(하반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
51,서울남대문경찰서,2017(하반기),중구,2017,127896,10265,16774,42620,40286,28216,893,4872,3302,1198
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10979,23931,50443,49187,33716,1116,6063,2878,922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,2871,32856,46112,65987,47491,124,1718,840,189
4114,진주경찰서,2019(상반기),진주시,2019,354166,7152,66710,94780,112947,79729,424,4908,1563,257
4131,진주경찰서,2019(하반기),진주시,2019,354166,7152,66710,94780,112947,79729,424,4908,1563,257
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,4917,40507,49459,62622,38297,212,2834,1570,301
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,4917,40507,49459,62622,38297,212,2834,1570,301

In [148]:
df4_n.to_csv('중간저장.csv')

In [149]:
# 행정구역을 여러 경찰서가 담당하는 경우 그 수만큼 인구를 나눠줌
'''
df4_n.iloc[0, 4:] = df4_n.iloc[0, 4:] / 2
df4_n.iloc[1, 4:] = df4_n.iloc[1, 4:] / 2
df4_n.iloc[2, 4:] = df4_n.iloc[2, 4:] / 2
df4_n.iloc[3, 4:] = df4_n.iloc[3, 4:] / 2 # 중구

df4_n.iloc[4, 4:] = df4_n.iloc[4, 4:] / 2
df4_n.iloc[5, 4:] = df4_n.iloc[5, 4:] / 2
df4_n.iloc[6, 4:] = df4_n.iloc[6, 4:] / 2
df4_n.iloc[7, 4:] = df4_n.iloc[7, 4:] / 2 # 종로구

df4_n.iloc[12, 4:] = df4_n.iloc[12, 4:] / 2
df4_n.iloc[13, 4:] = df4_n.iloc[13, 4:] / 2
df4_n.iloc[14, 4:] = df4_n.iloc[14, 4:] / 2
df4_n.iloc[15, 4:] = df4_n.iloc[15, 4:] / 2 # 성북구

df4_n.iloc[28, 4:] = df4_n.iloc[28, 4:] / 2
df4_n.iloc[29, 4:] = df4_n.iloc[29, 4:] / 2
df4_n.iloc[30, 4:] = df4_n.iloc[30, 4:] / 2
df4_n.iloc[31, 4:] = df4_n.iloc[31, 4:] / 2 # 은평구

df4_n.iloc[50, 4:] = df4_n.iloc[50, 4:] / 2
df4_n.iloc[51, 4:] = df4_n.iloc[51, 4:] / 2
df4_n.iloc[52, 4:] = df4_n.iloc[52, 4:] / 2
df4_n.iloc[53, 4:] = df4_n.iloc[53, 4:] / 2 # 서초구

df4_n.iloc[38, 4:] = df4_n.iloc[38, 4:] / 2
df4_n.iloc[39, 4:] = df4_n.iloc[39, 4:] / 2
df4_n.iloc[40, 4:] = df4_n.iloc[40, 4:] / 2
df4_n.iloc[41, 4:] = df4_n.iloc[41, 4:] / 2 # 강남구
'''

In [153]:
# 행정구역을 여러 경찰서가 담당하는 경우 그 수만큼 인구를 나눠줌
'''
for i in range(1, 3):
    df4_n.iloc[0 + 82 * i, 4:] = df4_n.iloc[0 + 82 * i, 4:] / 2
    df4_n.iloc[1 + 82 * i, 4:] = df4_n.iloc[1 + 82 * i, 4:] / 2
    df4_n.iloc[2 + 82 * i, 4:] = df4_n.iloc[2 + 82 * i, 4:] / 2
    df4_n.iloc[3 + 82 * i, 4:] = df4_n.iloc[3 + 82 * i, 4:] / 2 # 중구

    df4_n.iloc[4 + 82 * i, 4:] = df4_n.iloc[4 + 82 * i, 4:] / 2
    df4_n.iloc[5 + 82 * i, 4:] = df4_n.iloc[5 + 82 * i, 4:] / 2
    df4_n.iloc[6 + 82 * i, 4:] = df4_n.iloc[6 + 82 * i, 4:] / 2
    df4_n.iloc[7 + 82 * i, 4:] = df4_n.iloc[7 + 82 * i, 4:] / 2 # 종로구

    df4_n.iloc[12 + 82 * i, 4:] = df4_n.iloc[12 + 82 * i, 4:] / 2
    df4_n.iloc[13 + 82 * i, 4:] = df4_n.iloc[13 + 82 * i, 4:] / 2
    df4_n.iloc[14 + 82 * i, 4:] = df4_n.iloc[14 + 82 * i, 4:] / 2
    df4_n.iloc[15 + 82 * i, 4:] = df4_n.iloc[15 + 82 * i, 4:] / 2 # 성북구

    df4_n.iloc[28 + 82 * i, 4:] = df4_n.iloc[28 + 82 * i, 4:] / 2
    df4_n.iloc[29 + 82 * i, 4:] = df4_n.iloc[29 + 82 * i, 4:] / 2
    df4_n.iloc[30 + 82 * i, 4:] = df4_n.iloc[30 + 82 * i, 4:] / 2
    df4_n.iloc[31 + 82 * i, 4:] = df4_n.iloc[31 + 82 * i, 4:] / 2 # 은평구

    df4_n.iloc[50 + 82 * i, 4:] = df4_n.iloc[50 + 82 * i, 4:] / 2
    df4_n.iloc[51 + 82 * i, 4:] = df4_n.iloc[51 + 82 * i, 4:] / 2
    df4_n.iloc[52 + 82 * i, 4:] = df4_n.iloc[52 + 82 * i, 4:] / 2
    df4_n.iloc[53 + 82 * i, 4:] = df4_n.iloc[53 + 82 * i, 4:] / 2 # 서초구

    df4_n.iloc[38 + 82 * i, 4:] = df4_n.iloc[38 + 82 * i, 4:] / 2
    df4_n.iloc[39 + 82 * i, 4:] = df4_n.iloc[39 + 82 * i, 4:] / 2
    df4_n.iloc[40 + 82 * i, 4:] = df4_n.iloc[40 + 82 * i, 4:] / 2
    df4_n.iloc[41 + 82 * i, 4:] = df4_n.iloc[41 + 82 * i, 4:] / 2 # 강남구
'''

In [154]:
df4_n

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2017(상반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
17,서울남대문경찰서,2017(상반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
34,서울중부경찰서,2017(하반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
51,서울남대문경찰서,2017(하반기),중구,2017,63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
68,서울종로경찰서,2017(상반기),종로구,2017,78638.5,5489.5,11965.5,25221.5,24593.5,16858.0,558.0,3031.5,1439.0,461.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446.0,2871.0,32856.0,46112.0,65987.0,47491.0,124.0,1718.0,840.0,189.0
4114,진주경찰서,2019(상반기),진주시,2019,354166.0,7152.0,66710.0,94780.0,112947.0,79729.0,424.0,4908.0,1563.0,257.0
4131,진주경찰서,2019(하반기),진주시,2019,354166.0,7152.0,66710.0,94780.0,112947.0,79729.0,424.0,4908.0,1563.0,257.0
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885.0,4917.0,40507.0,49459.0,62622.0,38297.0,212.0,2834.0,1570.0,301.0
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885.0,4917.0,40507.0,49459.0,62622.0,38297.0,212.0,2834.0,1570.0,301.0

In [157]:
df4_n.to_csv('중간저장3.csv', index = False)

In [159]:
df4_n.sort_values(by = ['jur_stn', 'year'], axis = 0)

,jur_stn,year,sgg_nm,date,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
1292,마산동부경찰서,2017(상반기),창원시마산회원구,2017,202864.0,2770.0,37306.0,51907.0,69877.0,43774.0,79.0,1650.0,865.0,176.0
1309,마산동부경찰서,2017(하반기),창원시마산회원구,2017,202864.0,2770.0,37306.0,51907.0,69877.0,43774.0,79.0,1650.0,865.0,176.0
2686,마산동부경찰서,2018(상반기),창원시마산회원구,2018,197683.0,2770.0,35319.0,49122.0,67932.0,45310.0,82.0,1699.0,815.0,174.0
2703,마산동부경찰서,2018(하반기),창원시마산회원구,2018,197683.0,2770.0,35319.0,49122.0,67932.0,45310.0,82.0,1699.0,815.0,174.0
4080,마산동부경찰서,2019(상반기),창원시마산회원구,2019,192446.0,2871.0,32856.0,46112.0,65987.0,47491.0,124.0,1718.0,840.0,189.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,창원중부경찰서,2017(하반기),창원시성산구,2017,226726.0,4937.0,46726.0,68373.0,86416.0,25211.0,111.0,3420.0,1231.0,175.0
2584,창원중부경찰서,2018(상반기),창원시성산구,2018,225894.0,5101.0,44290.0,68541.0,85492.0,27571.0,141.0,3515.0,1267.0,178.0
2601,창원중부경찰서,2018(하반기),창원시성산구,2018,225894.0,5101.0,44290.0,68541.0,85492.0,27571.0,141.0,3515.0,1267.0,178.0
3978,창원중부경찰서,2019(상반기),창원시성산구,2019,219951.0,5191.0,41200.0,65279.0,83360.0,30112.0,184.0,3394.0,1409.0,204.0
3995,창원중부경찰서,2019(하반기),창원시성산구,2019,219951.0,5191.0,41200.0,65279.0,83360.0,30112.0,184.0,3394.0,1409.0,204.0

In [162]:
df4_n.drop(columns = ['sgg_nm', 'date'], inplace = True)

In [163]:
df4_n.to_csv('14번.연령별인구_전처리')

,jur_stn,year,popu_합계,for_합계,popu_u20,popu_2030,popu_4050,popu_o60,for_u20,for_2030,for_4050,for_o60
0,서울중부경찰서,2017(상반기),63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
17,서울남대문경찰서,2017(상반기),63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
34,서울중부경찰서,2017(하반기),63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
51,서울남대문경찰서,2017(하반기),63948.0,5132.5,8387.0,21310.0,20143.0,14108.0,446.5,2436.0,1651.0,599.0
68,서울종로경찰서,2017(상반기),78638.5,5489.5,11965.5,25221.5,24593.5,16858.0,558.0,3031.5,1439.0,461.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),192446.0,2871.0,32856.0,46112.0,65987.0,47491.0,124.0,1718.0,840.0,189.0
4114,진주경찰서,2019(상반기),354166.0,7152.0,66710.0,94780.0,112947.0,79729.0,424.0,4908.0,1563.0,257.0
4131,진주경찰서,2019(하반기),354166.0,7152.0,66710.0,94780.0,112947.0,79729.0,424.0,4908.0,1563.0,257.0
4148,진해경찰서,2019(상반기),190885.0,4917.0,40507.0,49459.0,62622.0,38297.0,212.0,2834.0,1570.0,301.0
4165,진해경찰서,2019(하반기),190885.0,4917.0,40507.0,49459.0,62622.0,38297.0,212.0,2834.0,1570.0,301.0

#### 성비 X

In [ ]:
df3_n = df3[df3['age'].isin(['합계', '15세미만', '15~64세', '65세이상'])]

In [107]:
for i in df3_nn['age'].unique() :
    df_bb['sx_rate_'+i] = 0

In [110]:
df_bb

,jur_stn,year,sgg_nm,date,popu_합계,popu_15~19세,popu_20~24세,popu_25~29세,popu_30~34세,popu_35~39세,...,sx_rate_55~59세,sx_rate_60~64세,sx_rate_65~69세,sx_rate_70~74세,sx_rate_75~79세,sx_rate_80~84세,sx_rate_85세이상,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상
0,서울중부경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,103.2,98.0,75.4
17,서울남대문경찰서,2017(상반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0.0,0.0,0.0
34,서울중부경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0.0,0.0,0.0
51,서울남대문경찰서,2017(하반기),중구,2017,127896,5739,10343,11113,10666,10498,...,0,0,0,0,0,0,0,0.0,0.0,0.0
68,서울종로경찰서,2017(상반기),종로구,2017,157277,10198,15098,13584,11100,10661,...,0,0,0,0,0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,마산동부경찰서,2019(하반기),창원시마산회원구,2019,192446,9858,11661,11052,9850,13549,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4114,진주경찰서,2019(상반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4131,진주경찰서,2019(하반기),진주시,2019,354166,20596,28020,22302,19777,24681,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4148,진해경찰서,2019(상반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4165,진해경찰서,2019(하반기),창원시진해구,2019,190885,8985,8638,10496,12168,18157,...,0,0,0,0,0,0,0,0.0,0.0,0.0

In [ ]:
sgg2police = {
    #seoul
'강남구' : ['서울강남경찰서', '서울수서경찰서'],
'강동구' : '서울강동경찰서',
'강북구' : '서울강북경찰서',
'강서구' : '서울강서경찰서',
'관악구' : '서울관악경찰서',
'광진구' : '서울광진경찰서',
'구로구' : '서울구로경찰서',
'권선구' : '수원서부경찰서',
'금천구' : '서울금천경찰서',
'노원구' : '서울노원경찰서',
'도봉구' : '서울도봉경찰서',
'동대문구' : ['서울동대문경찰서', '서울혜화경찰서'],
'동작구' : '서울동작경찰서',
'서대문구' : '서울서대문경찰서',
'서초구' : ['서울서초경찰서', '서울방배경찰서'],
'성동구' : '서울성동경찰서',
'성북구' : ['서울성북경찰서', '서울종암경찰서'],
'마포구' : '서울마포경찰서',
'송파구' : '서울송파경찰서',
'양천구' : '서울양천경찰서',
'영등포구' : '서울영등포경찰서',
'용산구' : '서울용산경찰서',
'은평구' : ['서울은평경찰서', '서울서부경찰서'],
'종로구' : '서울종로경찰서',
'중구' : ['서울중부경찰서', '서울남대문경찰서'],
'중랑구' : '서울중랑경찰서',
    
    #changwon
'마산합포구' : '마산중부경찰서',
'마산회원구' : '마산동부경찰서',
'성산구' : '창원중부경찰서',
'의창구' : ['창원중부경찰서', '창원서부경찰서'],
'진해구' : '진해경찰서',
'창원시' : ['진해경찰서', '창원서부경찰서', '창원중부경찰서', '마산중부경찰서', '마산동부경찰서'],
'창원시 마산합포구' : '마산중부경찰서',
'창원시 마산회원구' : '마산동부경찰서',
'창원시 성산구' : '창원중부경찰서',
'창원시 의창구' : ['창원중부경찰서', '창원서부경찰서'],
'창원시 진해구' : '진해경찰서',
'창원시마산합포구' : '마산중부경찰서',
'창원시마산회원구' : '마산동부경찰서',
'창원시성산구' : '창원중부경찰서',
'창원시의창구' : ['창원중부경찰서', '창원서부경찰서'],
'창원시진해구' : '진해경찰서',
    
    #sejong
'세종시' : '세종경찰서',
'세종특별자치시' : '세종경찰서',
    
    #suwon
'수원시' : ['수원남부경찰서', '수원서부경찰서', '수원중부경찰서'],
'수원시 권선구' : '수원서부경찰서',
'수원시 영통구' : '수원남부경찰서',
'수원시 장안구' : '수원중부경찰서',
'수원시 팔달구' : '수원서부경찰서',
'수원시권선구' : '수원서부경찰서',
'수원시영통구' : '수원남부경찰서',
'수원시장안구' : '수원중부경찰서',
'수원시팔달구' : '수원서부경찰서',
'영통구' : '수원남부경찰서',
'장안구' : '수원중부경찰서',
'팔달구' : '수원서부경찰서',

    #jinju
'진주시' : '진주경찰서'
}